### ISSUE TITLE
Sliders do not function properly

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#1]
I am currently testing on OSX 10.9.5. The sliders corresponding to indices of refraction does not function properly. When grabbing the slider node and lifting the cursor above the slider bar, the slider node will slide between the minimum and maximum values. After the node slides between 1.00 and 1.60 I noticed that if you click a position on the slider bar, the value of the index of refraction will not change until the user slides the slider node. Nothing severe, just thought I should report.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in HTML . Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Looks good, closing.
