### ISSUE TITLE
Convert laser color property to a derived property and improve its place for initialization.

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#100]
During #44 I saw the last few lines of the BendingLightModel constructor

```js
    this.laser = new Laser( laserDistanceFromPivot, laserAngle, topLeftQuadrant );
    this.wavelengthProperty.link( function( wavelength ) {
      bendingLightModel.laser.colorProperty.set( new LaserColor.OneColor( wavelength ) );
    } );
```

What do you think about creating the laser color property as a DerivedProperty and passing it to the laser in its constructor call?  Or possibly passing the wavelengthProperty to the laser and letting it create its own DerivedProperty?

**Comment by ChandrashekarBemagoni** [comment]
Followed second suggestion. Assigning to @samreid for review

**Comment by samreid** [comment]
Putting wavelength as a BendingLightModel property and passing it to the laser seems reasonable, closing.
