### ISSUE TITLE
Remove extraneous getters

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#101]
During #44 I saw several extraneous getters in BendingLightModel.js.  For instance:

```js
      /**
       * @public
       * @returns {number}
       */
      getWidth: function() {
        return this.modelWidth;
      },

      /**
       * @public
       * @returns {number}
       */
      getHeight: function() {
        return this.modelHeight;
      },

      /**
       * @public
       * @returns {Laser}
       */
      getLaser: function() {
        return this.laser;
      },

      /**
       * @public
       * @returns {IntensityMeter}
       */
      getIntensityMeter: function() {
        return this.intensityMeter;
      },
```

What is the reason for providing these getters instead of just accessing the variables such as model.intensityMeter directly?  Can these getters be removed?  Are there other places where extraneous getters can/should be eliminated?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
I can see that ~30 lines of getters are gone.  Looks good, closing.
