### ISSUE TITLE
How should we format percentages?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#103]
I saw this code during bending light review #44:

```js
      /**
       * @public
       * @param {number} value
       * @returns {string}
       */
      format: function( value ) {
        return Util.toFixed( value, VALUE_DECIMALS ) + '%';
      },
```

@pixelzoom is this how we normally i18nize percentages, or should this be done with a StringUtils.format?

**Comment by pixelzoom** [comment]
This should be done with a pattern.  The something like:

```js
// JSON
"pattern_0value_percent": {
   "value": "{0}%"
}

//  JavaScript
var valuePercentString = require( 'image!BENDING_LIGHT/pattern_0value_percent' );
return StringUtils.format( valuePercentString , Util.toFixed( value, VALUE_DECIMALS ) );
```

**Comment by samreid** [comment]
Thanks @pixelzoom.  @ChandrashekarBemagoni can you implement this as @pixelzoom has described?

**Comment by ChandrashekarBemagoni** [comment]
Followed above suggestion . Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
