### ISSUE TITLE
DivergingLens and Polygon duplicate a lot of code

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#107]
DivergingLens and Polygon only have about 20 differences over 200 lines of code--there are several duplicated methods and some methods that only differ by some added logic.  Can/should these files be unified?

**Comment by samreid** [comment]
Linking back so it will appear in the code review parent issue #44

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
I added a little bit of commenting above.  Looks great, thanks.  Closing.
