### ISSUE TITLE
TODOs marked in the code

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#109]
I'm seeing a few TODO's marked in the code.  @ChandrashekarBemagoni what is the status of these?

```js
// TODO: why is this backwards by 180 degrees?

// Todo : need to find out , why firefox behaving differently

// future TODOs could investigate using standard model creation/notification scheme

// TODO: add ray color without creating new Color object.
```

**Comment by samreid** [comment]
Linking back so it will appear in the code review parent issue #44

**Comment by ChandrashekarBemagoni** [comment]
Removed all  TODO's  statement .In that some them carried from java simulation and some are already addressed

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks good, thanks. Closing.
