### ISSUE TITLE
Should this sim be removed from the active-sims file for now?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/bending-light#11]
I was building all sims, and the lint (auto-Java-ported bits) filled my scrollback.

**Comment by jonathanolson** [comment]
Removed for now.

**Comment by samreid** [comment]
I'd rather keep it in active-repos and just comment out the offending code (will be several files).  @ChandrashekarBemagoni or @notsiddhartha can you take care of this?

**Comment by jonathanolson** [comment]
It is still in active-repos. Do you mean active-sims?

**Comment by samreid** [comment]
> It is still in active-repos. Do you mean active-sims?

Yes.

**Comment by samreid** [comment]
@notsiddhartha after you have completed the work, can you make a comment in this issue or email me or @jonathanolson, so we can update the active-sims list?  Thanks!

**Comment by ChandrashekarBemagoni** [comment]
Fixed all grunt issues.
