### ISSUE TITLE
Duplicated code in IntensityMeterNode

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#110]
I saw very similar code for the bodyNode and sensorNode in IntensityMeterNode.  Not sure of the best way to show a diff here, but I'll try with a PNG (click to enlarge photo):

![image](https://cloud.githubusercontent.com/assets/679486/8958558/d056f022-35c2-11e5-88d1-dab19b1de386.png)

Should these input listeners be unified?  If not, why not?

**Comment by samreid** [comment]
Linking back so it will appear in the code review parent issue #44

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great, thanks.  Closing.
