### ISSUE TITLE
Missing implementation-notes.md

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#111]
doc/implementation-notes.md was empty and I removed it.  However, I realized we should actually add content to that file.  It would be great if @ChandrashekarBemagoni could review 4-5 of the implementation-notes.md files from other PhET repositories and document bending-light accordingly.  This is an important file to help us understand the overall implementation of the simulation and would be difficult for our team to "reverse engineer" from looking at the code alone.  I'll resurrect the blank file shortly.

**Comment by samreid** [comment]
I restored the blank file above, reassigning to @ChandrashekarBemagoni

**Comment by samreid** [comment]
Linking back to the parent review issue #44

**Comment by ChandrashekarBemagoni** [comment]
Added implementation notes in above commits. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks good, thanks!
