### ISSUE TITLE
In IntroModel.js should getN1() and getN2() be derived properties?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#112]
I noticed this implementation of getN1() and getN2() in IntroModel.js as part of #44 

```js
    /**
     * Get the top medium index of refraction
     * @public
     * @returns {number}
     */
    getN1: function() {
      return this.topMediumProperty.get().getIndexOfRefraction( this.laser.colorProperty.get().wavelength );
    },

    /**
     * Get the bottom medium index of refraction
     * @public
     * @returns {number}
     */
    getN2: function() {
      return this.bottomMediumProperty.get().getIndexOfRefraction( this.laser.colorProperty.get().wavelength );
    }
```

This has the effect that when the laser is being dragged, each of these values are computed in every frame, even if they are unchanged.  I'm wondering what @ChandrashekarBemagoni thinks about converting each of these to an axon derived property, which would update eagerly when the medium or wavelength changes, but then does not need to be recomputed as the laser is being dragged.  This would make it smoother for dragging the laser while it is on though less smooth when changing the index of refraction *with the laser off* (since in that latter case getN1 and getN2 wouldn't need to be called at all).  But in my opinion we should be optimizing for the case when the laser is on.

Each getIndexOfRefraction call cascades to 2 calls to getAirIndex and getSellmeierValue, which are primarily arithmetic, but I still think it might be a good plan to convert getN1 and getN2 to derived properties to minimize the amount of work required by the CPU when dragging the slider, and to make it clear what values they depend on.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
This seems much better, thanks.  I think another improvement would be to use PropertySet.addDerivedProperty.  I'll do that shortly.

**Comment by samreid** [comment]
Fixed above, @ChandrashekarBemagoni can you please review my change and make sure it is OK?

**Comment by samreid** [comment]
I had to bail on using addDerivedProperty in order to solve #144, so I think this issue is complete.  Closing.
