### ISSUE TITLE
laser.png is loaded from several places

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#113]
During #44 I saw that laser.png is loaded in 3 places: LaserNode.js, RotationDragHandle.js and TranslationDragHandle.js.  It would be better to just load it once and pass it in to the appropriate places.  Loading the same image 3 independent times could cause confusion or maintenance problems--for instance, say the filename is changed, then the code would have to be updated in several places instead of one.  As far as I know, the DragHandles just need to know about its dimension (not the image itself), so another good option would just be to pass in the laserImageWidth and laserImageHeight.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Nice work @ChandrashekarBemagoni, closing.
