### ISSUE TITLE
What is EPSILON and why is it 0.6?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#114]
During #44 I saw this code in RotationDragHandle.js

```js
    var image = new Image( laserImage, { scale: 0.58 } );
    var dragArrow = new Path( null, { fill: '#33FF00', stroke: 'black' } );
    this.addChild( dragArrow );
    var EPSILON = 0.6;
    var arrowHeadHeight = deltaAngle > 0 ? -7 : 7;
    var isArrowDirectionAntiClockWise = deltaAngle > 0;
    var startAngleOffset = deltaAngle * (1 - EPSILON);
    var endAngleOffset = deltaAngle * 1.1;
```

Can you please document EPSILON, what the value is, what the units are and why that is a good value?  Also, for local vars like this we should use lowercase, even if they are constant.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
I'm not sure where EPSILON went in the diff, but it looks much simpler.  Closing.
