### ISSUE TITLE
Change LightRayNode.js to use scenery.Line instead of scenery.Path

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#115]
During #44 I observed that LightRayNode is using scenery.Path like so:

```js
    var lightRayPath = new Path( new Shape().moveToPoint( this.viewStart )
      .lineToPoint( this.viewEnd ), {
      lineWidth: modelViewTransform.modelToViewDeltaX( lightRay.getRayWidth() ),
      stroke: rayColor
    } );
```

It is my understanding that creating Shapes like so is much more CPU and memory intensive than creating a Line.  Can we use a Line in this context?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great @ChandrashekarBemagoni, closing.
