### ISSUE TITLE
Change LightRayNode from composition to inheritance

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#116]
During the review #44 I noticed that LightRayNode extends node and contains a Path node (see also #115 for converting this to Line).  But would it be possible and good for LightRayNode to extend Line instead of adding one through composition?  Adding more Nodes in the hierarchy is sometimes necessary to create additional independent transforms but increases overhead.  I'm not sure if the additional level is required in this case.

**Comment by ChandrashekarBemagoni** [comment]
Fixed here https://github.com/phetsims/bending-light/commit/8df18c49ea15d6f9e631b117723c507bcd898299. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great, closing.
