### ISSUE TITLE
Wavelength is different on iPad vs Mac Chrome

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#118]
During the code review #44 I noticed discrepancies between the wave view on retina iPad vs Mac Chrome (see #117).  I also observed that on the retina iPad the wavelength is much shorter than on Mac Chrome.  Here is a screenshot of the default settings for the simulation, simply enabling "wave" mode and turning the laser on:

![image](https://cloud.githubusercontent.com/assets/679486/8971134/1db4ac9a-360b-11e5-88c5-1e1074c615c7.png)

Here is the same situation but on Mac Chrome (non-retina):

![image](https://cloud.githubusercontent.com/assets/679486/8971163/5daf0ca0-360b-11e5-8d3f-1a2f5ddc095d.png)

In the retina case I count 26 wave crests before the beam hits the surface.  In the non-retina case I count 13 wave crests before the beam hits the surface.  Since this is a multiplier of exactly 2x, it may have something to do with retina vs non-retina.  I recommend to look into this issue before #117 since fixing this may fix that.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for verification

**Comment by samreid** [comment]
I confirmed that the changes above give the same wavelength on iPad as on non-retina OS X.  However, now on retina devices the wave crests don't match at the interface, see this screenshot from the iPad3:

![image](https://cloud.githubusercontent.com/assets/679486/9393973/a1261d3c-4742-11e5-9960-e99336ced08e.png)

I did not observe this problem on my non-retina OS X chrome, but this is problematic for the retina device.

**Comment by ChandrashekarBemagoni** [comment]
Fixed here https://github.com/phetsims/bending-light/commit/c7e7ea084b7edf3e9c82c776a1bf2352664d1655. Assigning to @samreid for verification

**Comment by samreid** [comment]
I think the wave crests matching at the interface is being handled in #117, so this issue can be closed.
