### ISSUE TITLE
Wave view gets disassociated from laser

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#119]
When dragging on iPad 3, the wave view lags behind the laser position, like so:

![image](https://cloud.githubusercontent.com/assets/679486/8971256/0aba63e0-360c-11e5-8770-7a2eab61e98f.png)

It may be that addressing other performance concerns helps with this.

**Comment by samreid** [comment]
I can look into this issue, I'll reassign it.

**Comment by samreid** [comment]
In the new version, the wave webgl view *precedes* the laser.  This is only a problem for webgl--the canvas version (?webgl=false) is perfectly synchronized.  @jonathanolson can you think of how the webgl version is moving *ahead* of the laser?

**Comment by samreid** [comment]
This issue can be seen slightly for the webgl ray mode as well.

**Comment by jonathanolson** [comment]
Not sure yet. Does this happen on all browsers?

**Comment by samreid** [comment]
@jonathanolson only visible on iPad, but that may be because it is also our slowest platform. (I'm testing on iPad3 here).

**Comment by jonathanolson** [comment]
Using phet.joist.makeEverythingSlow() doesn't seem to be able to cause the gap on Chrome/Win. I'll be able to test on Safari tomorrow on campus.

**Comment by jonathanolson** [comment]
Also can't seem to cause it on Safari, even with the slow-downs.

**Comment by jonathanolson** [comment]
I can occasionally just barely see this on the iPad 2. I'm more concerned about graphics quality though:

With WebGL:
![image](https://cloud.githubusercontent.com/assets/480878/9882596/b5f8875e-5b92-11e5-9b34-ee6362bd14c4.jpg)
Without:
![image](https://cloud.githubusercontent.com/assets/480878/9882603/bf776890-5b92-11e5-9326-59da0509ddf2.jpg)

**Comment by jonathanolson** [comment]
With WebGL on, the edges of the beam AND laser body are very aliased, and without WebGL, the edges of the refracted beam are very rough and edgy.

**Comment by jonathanolson** [comment]
Cursory searches online haven't led me to figure this out yet, but likely sometimes (not always) the WebGL rendering is either delayed or ahead (depending on the version). It would require more investigation into iOS's pipeline to figure out if there's a way we can prevent this.

As it was fairly rare on the iPad 2, I'm curious whether it's more serious on the iPad 3, and what priority this should be.

**Comment by samreid** [comment]
I'll move the graphics quality issue to a separate issue.

**Comment by samreid** [comment]
@ariel-phet should we punt on this?

**Comment by ariel-phet** [comment]
If it is only noticeably occurring on iPad3, it is acceptable to punt.

**Comment by samreid** [comment]
Thanks for your feedback, we'll close for now.
