### ISSUE TITLE
incorrect method of accessing properties in IntensityMeterNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#12]
While making a common-code refactor in IntensityMeterNode, I noticed this buggy code:

```js
intensityMeter.sensorPosition.reset();
intensityMeter.bodyPosition.reset();
```
intensityMeter is a PropertySet, and properties can't be accessed this way.  If this code is reached, it will cause this error:
> Uncaught TypeError: undefined is not a function

The correct code should be:

```js
intensityMeter.sensorPositionProperty.reset();
intensityMeter.bodyPositionProperty.reset();
```

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
IntensityMeter.resetAll was changed to this:

```js
 resetAll: function() {
    PropertySet.prototype.reset.call( this );
  }
```

Calling a supertype function like this is typically only done when you're overriding the supertype function and want to make sure that it's called.  For example, if your function was called `reset` and your subtype had additional thing to reset, then you'd do this:

```js
// @override
 reset: function() {
    PropertySet.prototype.reset.call( this );
    // ...then reset addition things here
  }
```

Since the supertype (PropertySet) has no resetAll function, you should implement resetAll like this:

```js
 resetAll: function() {
    this.reset();
  }
```

Perhaps a bigger question is why does IntensityMeter need a resetAll function? I also see a resetAll function in other types.  PhET typically implements a `reset` function (not a `resetAll` function) for things that need to be reset when the "Reset All" button is pressed.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @pixelzoom for review

**Comment by pixelzoom** [comment]
Getting closer... In IntensityMeter, you now have this:

```js
reset: function() {
        PropertySet.prototype.reset.call( this );
      }
```

This function can be removed entirely, since all that it's doing is calling the supertype function.  Ditto for Laser.reset and ProtractorModel.reset.

One more minor point in BendingLightModel.reset, currently implemented like this:

```js
      reset: function() {
        this.laser.reset();
        PropertySet.prototype.reset.call( this );
        this.intensityMeter.reset();
      }
```

When overriding a supertype function, the supertype function is typically called first, followed by any specialization by the subtype.  So the above would be:

```js
      reset: function() {
        PropertySet.prototype.reset.call( this );
        this.laser.reset();
        this.intensityMeter.reset();
      }
```

**Comment by pixelzoom** [comment]
Note also the use of the JSdoc `@override` annotation when you override a supertype function.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks good, closing.
