### ISSUE TITLE
TranslationDragHandle & RotationDragHandle are being updated when not used

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#120]
During #44 I observed that the translation drag handles don't appear on screen 1 "Intro" yet that shape shows up in the profiler and it is consuming CPU time.  The code in TranslationDragHandle could check whether showDragHandlesProperty is true before running the Property multilink update.  It would also need to add the showDragHandlesProperty in the multilink so that it can update & redraw when that value becomes true.

The same approach can be applied in RotationDragHandle.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Perfect, thanks.  Closing.
