### ISSUE TITLE
A lot of empty space between the word "Protractor" and the icon

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#121]
During #44 I observed there is a lot of empty space between the word "Protractor" and the icon.  This is on the "Prisms" screen on iPad3.  It makes it difficult to know that they are associated with one another.

![image](https://cloud.githubusercontent.com/assets/679486/8971515/402fdc88-360e-11e5-99f9-388600e7f428.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for verification

**Comment by samreid** [comment]
This looks much better:

![image](https://cloud.githubusercontent.com/assets/679486/9014910/9645ef2a-3782-11e5-9456-866169eea395.png)

Closing.
