### ISSUE TITLE
Update the look of the speedometer to address occlusion issues

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#122]
During the code review #44 I observed that several of the objects which can be dragged out of the toolbox are occluded by default on touch devices.  The intensity meter, speedometer and chart all have this problem.

![image](https://cloud.githubusercontent.com/assets/679486/8971638/82a2834e-360f-11e5-815f-99e3c840226b.png)

![image](https://cloud.githubusercontent.com/assets/679486/8971642/8930cdf6-360f-11e5-9251-6cb6a790ab20.png)

![image](https://cloud.githubusercontent.com/assets/679486/8971644/8eff1b48-360f-11e5-99d8-0eedf2d78887.png)

![image](https://cloud.githubusercontent.com/assets/679486/8971646/94e6fc92-360f-11e5-8444-2b8f2898cb16.png)

The objects should appear above the touch point so the user's digits do not occlude the view.  @arouinfar can you look into this and make a specific recommendation about how to position the toolbox objects that will work well for touch & mouse?  After making a recommendation, please reassign to @ChandrashekarBemagoni.

**Comment by arouinfar** [comment]
When discussing this issue with @ariel-phet, we felt that the speedometer was the only really problematic tool. A few possible options for a redesigned speedometer were discussed at the 8/13 meeting and it was concluded that 
> AR will mock up an option with the pointer on the left and the “Speed” label below the readout, no grabby knobs 

I've mocked up a new version of the speedometer:
![image](https://cloud.githubusercontent.com/assets/8419308/9315231/3c71f806-44eb-11e5-9aca-5f3384c77c84.png)

What do you think, @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar - that works for me!

**Comment by arouinfar** [comment]
@samreid, please let me know if you need an asset file for the speedometer. I'm not sure if you will end up drawing it in code or not.

**Comment by samreid** [comment]
This will be drawn in code.

**Comment by samreid** [comment]
Partial progress above, but there are many confusing parts to VelocitySensorNode that will have to be figured out to finish this.

**Comment by samreid** [comment]
Putting the hot spot at (0,0) is working great here, I just need to reposition the other things around it. Thanks to @pixelzoom and @jonathanolson for suggesting this strategy (though in some other context) earlier today.

**Comment by pixelzoom** [comment]
I use that strategy a lot to make it easy to position things. If you haven't already, highly recommend to note where the (non-standard) origin is in your Node's jsdoc.

**Comment by samreid** [comment]
Thanks I documented the origin in the jsdoc.

**Comment by samreid** [comment]
Fixed here, @arouinfar can you take it for a test drive? http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.15/bending-light_en.html

**Comment by arouinfar** [comment]
It's working great! Thanks @samreid. The only comment I have is a bit pixel-polishy. The readout window seems larger than necessary (and larger than the mockup). Is it possible to reduce the size a bit? If the padding (amount of orange) on the top of the readout window matched the amount on the sides, it would feel more balanced to me.

**Comment by samreid** [comment]
I reduced the size (old one top, new one bottom).  Assigned to @ariel-phet to see if there's anything else to do here.

![image](https://cloud.githubusercontent.com/assets/679486/9417390/12bda39a-4809-11e5-80ad-5fd8de2938e5.png)

**Comment by ariel-phet** [comment]
Final tweaks being addressed by #194 closing.
