### ISSUE TITLE
Duplicated code in LaserView.js and LaserControlPanelNode.js

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#123]
During the code review #44 I observed a lot of duplicated code between LaserView.js and LaserControlPanelNode.js

![image](https://cloud.githubusercontent.com/assets/679486/8972369/b015f0f2-3616-11e5-9cd5-1cc61fef222d.png)
(click to enlarge photo)

How can this code most efficiently be factored out?  Inheritance/composition/functions, etc?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
It's a bit difficult for me to understand everything that happened in this change set, but I no longer see the problem.  Closing.
