### ISSUE TITLE
Why is _notifyObservers used?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#125]
During #44 I observed that there are 11 occurrences of `_notifyObservers`.  This is a primarily internal method which should usually not be used by simulation code.  For instance, in IntensityMeter.js:

```js
this.sensorPositionProperty.set( this.newSensorPosition );
this.sensorPositionProperty._notifyObservers();
```

Why not set the property by:

```js
this.sensorPosition = this.newSensorPosition;
```

It should automatically notify observers.

**Comment by ChandrashekarBemagoni** [comment]
Property listeners are notifying automatically only when we set it with a new value.Some cases _notifyObservers is used because we are using single vector to reduce Vector2 allocations. We used set method to change property value because it does not change initial value.
See more :https://github.com/phetsims/fluid-pressure-and-flow/issues/46

**Comment by samreid** [comment]
If you are reusing the same instance, do you need to call `set` again?  For instance, IntensityMeter.js has this code:

```js
      /**
       * Translate sensor in model
       * @public
       * @param {number} deltaX - distance the sensor translated in the x-direction, in model units
       * @param {number} deltaY - distance the sensor translated in the y-direction, in model units
       */
      translateSensorXY: function( deltaX, deltaY ) {
        this.newSensorPosition.x = this.sensorPosition.x + deltaX;
        this.newSensorPosition.y = this.sensorPosition.y + deltaY;
        this.sensorPositionProperty.set( this.newSensorPosition );
        this.sensorPositionProperty._notifyObservers();
      }
```

But wouldn't it behave exactly the same if you removed the line:
```js
        this.sensorPositionProperty.set( this.newSensorPosition );
```

?

But perhaps I didn't completely understand what you said here:

> We used set method to change property value because it does not change initial value.

My recommendation: try removing the `set` calls for cases like this and see if the sim behaves properly.  If it does, then comment each place where _notifyObservers is used to indicate that this "mutate the same instance" sort of pattern is being employed in each of those sites.

**Comment by ChandrashekarBemagoni** [comment]
if we remove the`set` calls  in this cases then sim not working properly

**Comment by samreid** [comment]
I suspect this is because the Property must be given the newVector value at least once.  Can you try constructing the Properties with the newVector value and see if the set calls can be omitted then?

**Comment by ChandrashekarBemagoni** [comment]
Every property has 2 values initial value and present value. But if directly give a value like 
``` this.sensorPosition = this.newSensorPosition ``` it will overwrite the initial value. We can not reset to the initial value.

As per your suggestion we set the value only once in the constructor
```js
PropertySet.call( this, {
        reading: Reading.MISS, // @public, value to show on the body
        sensorPosition: new Vector2( sensorX, sensorY ), // @public,
        bodyPosition: new Vector2( bodyX, bodyY ), // @public,
        enabled: false // @public, True if it is in the play area
      }
    );
```
    // vector to store sensor position
    this.newSensorPosition = new Vector2( sensorX, sensorY ); // @private, for internal use only.

    // vector to store body position
    this.newBodyPosition = new Vector2( bodyX, bodyY ); // @private, for internal use only.

    this.sensorPositionProperty.set( this.newSensorPosition );
    this.bodyPositionProperty.set( this.newBodyPosition );

And in every other place we just update the values the this.newSensorPosition and this.newBodyPosition. This will only work until reset is done. after resetting again the values will be set to initial values. Changing the this.newSensorPosition, this.newBodyPosition the values will not have any effect on them now.
``` Alternative solution ```
The other solution for this is to store the the initial values in some instance variable and to restore them when reset function is called.

**Comment by samreid** [comment]
I see the issue.  For instance, ProtractorModel has a position property which is declared like this:

```js
    PropertySet.call( this, {
        angle: 0.0, // @public
        position: new Vector2( x, y ), // @public, position of the center
        enabled: false // @public
      }
    );

    // reusable vectors to avoid too many vector allocations
    // vector to store new Protractor position
    this.newPosition = new Vector2( 0, 0 ); // @private, for internal use only.
```

I tried revising it like so:

```js
    // reusable vectors to avoid too many vector allocations
    // vector to store new Protractor position
    this.newPosition = new Vector2( x, y ); // @private, for internal use only.

    PropertySet.call( this, {
        angle: 0.0, // @public
        position: this.newPosition, // @public, position of the center
        enabled: false // @public
      }
    );
```

and got rid of the set call in translateXY:
```
      this.newPosition.setXY( this.position.x + deltaX, this.position.y + deltaY );
      // this.positionProperty.set( this.newPosition );
      this.positionProperty._notifyObservers();
```

However, the problem is that other clients of the ProtractorModel set a different Vector value to it sometimes, and hence sometimes it needs to set back its original vector instance.

So we have the following ways to proceed:
(1) rewrite clients use a public API that encapsulates the idea of this mutable vector, to avoid even more allocations
(2) [current version] use a mixed approach where some vectors are reallocated and some are reused
(3) rewrite classes using this strategy to just allocated new Vector2 instances

I'm inclined to test (3) and see how much that changes the frames per second on iPad3.  If it is negligible, then we should just use standard axon patterns here.  If the fps is much faster, then we should investigate (1) and see if we can make it even faster.  If (1) doesn't make it even faster, then it may be ok to document what we have and remain at level (2). 

I'll investigate here.

**Comment by samreid** [comment]
I guess I'd like to see better support for this kind of pattern in Axon--allocation free messaging for cases like Vector2 but generally applicable.  I created an axon issue about it above.

**Comment by samreid** [comment]
I converted to new Vector2, tested on iPad3 in requirejs mode and did not see any significant performance changes.  I'll commit shortly.

**Comment by samreid** [comment]
Fixed above, closing.
