### ISSUE TITLE
Better way to check bounds in LightRayNode

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#127]
During #44 I saw this code in LightRayNode:

```js
    // Restricted the light ray view coordinates (start and end )within the specific window(rectangle) area to support in firefox browser
    // Note : if the values are to long rays rendering different directions
    // TODO : need to find out , why firefox behaving differently
    var shape = new Rectangle( -100000, -100000, 200000, 200000 );
    if ( !shape.getShape().containsPoint( this.viewStart ) ) {
      var intersection = shape.getShape().intersection(
        new Ray2( this.viewEnd, this.viewStart.minus( this.viewEnd ).normalize() ) );
      if ( intersection.length ) {
        this.viewStart = intersection[ 0 ].point;
      }
    }
```

It is expensive to create a throwaway scenery Rectangle for each Light Ray, would be much better to create a dot rectangle or use another way for checking bounds.

**Comment by ChandrashekarBemagoni** [comment]
Actually we no need to check bounds of LightRay.
 Restricted the light ray view coordinates (start and end )within the specific window(rectangle) area to support in firefox browser.
@samreid please can you  see it's once

**Comment by ChandrashekarBemagoni** [comment]
In dot rectangle there is no option to find out the intersection between bounds and ray.

**Comment by samreid** [comment]
It looks like kite's rectangle will work well here, @ChandrashekarBemagoni can you review the change set above?  I'll create a separate issue for looking into the firefox issue.

**Comment by ChandrashekarBemagoni** [comment]
after Using kite's rectangle It's  working  fine

**Comment by samreid** [comment]
Thanks for checking, closing.
