### ISSUE TITLE
Return an object instead of an array for the time/magnitude.

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#128]
During #44 code review I observed this code in IntroModel.getWaveValue:

```js
return [ ray.time, amplitude * Math.cos( phase + Math.PI ) ];
```

This is returning an array where the 0th element is the time and the 1th element is the magnitude.  It would be simpler if this code returned an object instead of an array, for instance:

```js
return {time:ray.time, magnitude:amplitude * Math.cos( phase + Math.PI )};
```

Unless there was a specific reason why arrays are required here, we should use the object as described above.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @samreid for review

**Comment by samreid** [comment]
Thanks, that is much nicer.  Closing.
