### ISSUE TITLE
totalPhaseOffsetInNumberOfWavelengths % 1

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#129]
During code review #44 I observed this code in IntroModel.js

```js
var phaseDiff = (totalPhaseOffsetInNumberOfWavelengths % 1) * wavelength;
```

I think any number %1 is equal to itself.  Is this left over from debugging?  Should we leave it in and make 1 a constant and document that it can be used for debugging?  Or should this be removed?

**Comment by samreid** [comment]
There are two other occurrences of %1 in the code as well.

**Comment by ChandrashekarBemagoni** [comment]
In this case %  used to find the delta or phase diff (decimal points).
        - eg: 12.1%1 == 0.1

**Comment by samreid** [comment]
Ah thanks for explaining that.  I added some docs to help in the future.  Closing.
