### ISSUE TITLE
Rename stepInternal

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#130]
I noticed that the stepInternal methods are marked as public (and in one case protected) and called from outside of the file.  Can they be given a different name since "internal" suggests for private intra-file use only?

**Comment by samreid** [comment]
Discovered during review in #44

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
This is much better, thanks!  I also renamed one in PrismsView above, can you check that it is OK and close if so?

**Comment by ChandrashekarBemagoni** [comment]
looks good . thanks
closing
