### ISSUE TITLE
Change x.yProperty.get() to x.y

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#131]
During #44 I observed many occurrences in the code with the pattern of `x.yProperty().get()` when in many cases it looks like `x.y` would work equally well.  Were there circumstances where `x.y`was too performance intensive?  Can most of these be converted to the simpler form?

**Comment by ChandrashekarBemagoni** [comment]
Non-PropertySet objects  can get the value 
`x.yProperty().get()` or  `'x.yProperty.value` 

PropertySet objects we can get the value 
`x.y`
see https://github.com/phetsims/axon/issues/42

**Comment by ChandrashekarBemagoni** [comment]
Followed Property.addProperty( this, 'visible', true ); pattern. Assigning to @samreid for review

**Comment by samreid** [comment]
It is difficult to see all of the specific changes directly related to this issue since https://github.com/phetsims/bending-light/commit/8e28ce98d18c8d5c0e7689f23c46f79c4cb92e24 was a more extensive commit. Still, I reviewed existing cases of *Property.get* and found they are all warranted.  I looked through the change set and found a case where this pattern was being properly applied.  Closing.
