### ISSUE TITLE
Can gridPoints use [{x,y},{x,y}] instead of [x,y,x,y]?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#132]
During the review #44 I noticed that gridPoints is using an interleaved array like [x,y,x,y] instead of a structured array like [{x,y},{x,y}] (an array of Vector2), and this was not documented.  Can it be converted to use the structured array?  If this decreases performance too much, please document (a) the approach taken and (b) how much performance is improved by using the flat array vs the structured array.

**Comment by ChandrashekarBemagoni** [comment]
Used object instead of array for simplification. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks much better and I also noticed gridPoints became gridLines.  This seems good. Closing.
