### ISSUE TITLE
Rename ChartNode.series to ChartNode.seriesArray

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#133]
During #44 I noticed that ChartNode.series is of type {array.<Series>}, so it is not just one series but an array of series.  

This is also leading to confusing code like this loop where a series element shadows the array of serieses:
```js
      this.series.forEach( function( series ) {
        series.keepLastSamples( minTime );
      } );
```

I recommend to rename series to seriesArray (parameter and property).  Then we could also rename s=>series in this part:

```js
    series.forEach( function( s ) {
      chartNode.addChild( new SeriesNode( s, chartNode.modelViewTransformProperty, chartNode.chartBounds ) );
    } );
```

**Comment by samreid** [comment]
My mistake, there is no shadowing happening in the first example above, since it is not in the constructor.   Still, it would be an improvement to rename series to seriesArray where it is referring to the array of serieses and just use the word "series" for a single series.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Excellent, thanks.  Closing.
