### ISSUE TITLE
Better documentation in GridCanvasNode

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#135]
During #44 I saw this documentation in GridCanvasNode:

```js
/**
 * Draw a horizontal or vertical grid line
 *
 * @author Chandrashekar Bemagoni (Actual Concepts)
 */
```

I recommend documentation be added to describe everything that is drawn in the GridCanvasNode as well as its relationship to other components in the simulation. "It is used by the ... in order to ..."

It should also be described why it is important that this be a canvas node instead of a regular node.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above  commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Thanks, that is much clearer.  Closing.
