### ISSUE TITLE
Why is the vector being negated?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#137]
During the code review #44, in Circle.getIntersections I saw this code:

```js
            if ( normalVector.dot( ray.directionUnitVector ) > 0 ) {
              normalVector = normalVector.negate();
            }
```

However, there is no explanation as to why the normal vector is negated in this circumstance. Please add documentation.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
That documentation explains it well, thanks.  Closing.
