### ISSUE TITLE
Why is there a Circle.getRotatedInstance() function?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#138]
During the code review #44 I saw this method in Circle.js

```js
    /**
     * Create a new Circle rotated by the specified angle
     * @public
     * @param {number} angle - angle to be rotated
     * @param {Vector2} rotationPoint - point around which circle to be rotated
     * @returns {Circle}
     */
    getRotatedInstance: function( angle, rotationPoint ) {

      // we create a new circle with a rotated center point
      var vectorAboutCentroid = this.getRotationCenter().subtract( rotationPoint );
      var rotated = vectorAboutCentroid.rotate( angle );
      return new Circle( rotated.add( rotationPoint ), this.radius );
    }
```

Shouldn't a rotated circle be itself?  Also in the user interface, I didn't see a rotation handle on the Circrle, so I'm wondering if this gets called at all?

![image](https://cloud.githubusercontent.com/assets/679486/8999158/b236a358-36f3-11e5-9327-576289c8c98f.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
The method was removed in the change set above.  Closing.
