### ISSUE TITLE
Duplicated code in getIntersections

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#139]
In Circle, Polygon and Semicircle the getIntersections implementations are very similar.  I saw this during #44 code review.  For instance:

![image](https://cloud.githubusercontent.com/assets/679486/8999213/4c44c1d2-36f4-11e5-8ed0-58dcf27d59de.png)

This seems like a good opportunity to factor out duplicated code.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
This looks great, thanks for factoring out this code.  In PrismIntersection.js can you rename the var in this line?

```js
var intersection1 = this;
```

Something like `intersection` or `prismIntersection` or `thisIntersection` seems like it would be better.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great, thanks.  Closing.
