### ISSUE TITLE
Properties should have `Property` suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#14]
See https://github.com/phetsims/beers-law-lab/issues/86

Examples of anti pattern (not exhaustive):

IntensityMeter: this.value = new Property( NaN )
BendingLightView: var showRotationDragHandles = new Property( false );
BendingLightView: var showTranslationDragHandles = new Property( false );
LaserView: var wavelength = new Property( model.wavelengthPropertyProperty.value * 1E9 );

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @pixelzoom for review

**Comment by pixelzoom** [comment]
Looks good, closing.
