### ISSUE TITLE
Change IntersectionNode to use Line instead of Path

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#140]
During #44 I observed that IntersectionNode has the following code:

```js
    // Show a dotted line of the normal at the interface between two mediums where the laser struck
    this.addChild( new Path( new Shape()
      .moveTo( centerX + unitNormalX * length / 2, centerY + unitNormalY * length / 2 )
      .lineTo( centerX + unitNormalX * -length / 2, centerY + unitNormalY * -length / 2 ), {
      stroke: 'black',
      lineDash: [ 10, 5 ]
    } ) );
```

Scenery's Line has better performance and memory characteristics that scenery's Path, and it should be preferred where possible.  I noticed something similar in See also https://github.com/phetsims/bending-light/issues/115

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great, thanks.  Closing.
