### ISSUE TITLE
Create a screenshot

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#142]
From the code review:

> Is the format of assets/*-screenshot.png correct? (2048x1344, PNG, 32-bit color) Has the browser chrome been stripped off of the screenshot?

This cannot be completed until #104 is complete and all pixel polishing is complete.  I'll assign this issue to @arouinfar since #104 is assigned to her.

**Comment by arouinfar** [comment]
What about something along these lines, @samreid?

![image](https://cloud.githubusercontent.com/assets/8419308/9315592/37dbf218-44ed-11e5-9ba8-bf4fa1b71a64.png)

**Comment by samreid** [comment]
This looks like a good scenario for the screenshot.  Before capturing the final screenshot, we will need to (a) provide the screen icons and (b) fix the logo to be the colorized version.

**Comment by arouinfar** [comment]
Thanks for your input @samreid. We'll also need to take care of #122 and #174 since they have implications for the look of the toolbox.

**Comment by samreid** [comment]
@arouinfar any other visual changes before we can generate the screenshot?

**Comment by arouinfar** [comment]
The only outstanding issue before the screenshot can be generated is #104 (navbar/homescreen icons). I will send @samreid the updated icons this morning.

**Comment by arouinfar** [comment]
@samreid now that the home screen icons have been taken care of, I can generate the screenshot. Can you publish a new dev version so I can take care of this? It looks like sims on phettest have "adapted by PhET" in the navbar.

**Comment by samreid** [comment]
> It looks like sims on phettest have "adapted by PhET" in the navbar.

I'm not too familiar with phettest, but if it is running a non-build version, then you can probably add `?brand=phet` to get the PhET brand.  Do you have an iPad3 or equivalent resolution for generating the screenshot?  Also, if the brand doesn't get fixed above let me know and I'll publish.

**Comment by arouinfar** [comment]
Thanks, Sam! It looks like ?brand=PhET works on phettest, so I'll be sending you a screenshot soon.

**Comment by arouinfar** [comment]
Screenshot has been sent to @samreid.
