### ISSUE TITLE
Improvements for model.md?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#143]
@arouinfar I could use your help with the model.md.  From the code review:

> Does model.md adequately describe the model, in terms appropriate for teachers?

Can you review this file and let me know if you can think of other parts in the simulation that should be discussed in the model.md?   Here's a link:
https://github.com/phetsims/bending-light/blob/master/doc/model.md

It may be helpful for you to review other model.md files as you are considering this, such as:
https://github.com/phetsims/hookes-law/blob/master/doc/model.md
https://github.com/phetsims/least-squares-regression/blob/master/doc/model.md

**Comment by samreid** [comment]
Maybe we should describe the dispersion function?  In the code this is documented as:

```js
/**
 * Models dispersion functions for each material. Uses the actual dispersion equation for air (A) and the actual
 * dispersion equation for glass (G) then interpolates between the functions n(lambda) = beta * A(lambda) + (1-beta) *
 * G(lambda) where 0<=beta<=infinity is a characteristic of the material. The material is characterized by a reference
 * wavelength, so that when light is the specified wavelength, the index of refraction takes the reference value.
```

**Comment by samreid** [comment]
We are displaying light rays with a width of 1.5992063492063494E-7 meters, should we note that in the model.md?

**Comment by samreid** [comment]
The wave is propagated according to the usual wave equation: cos(k * x - omega * t + phase)

**Comment by arouinfar** [comment]
@samreid, please add the wave equation to model.md. The dispersion equation and ray width seem like an unnecessary amount of detail when comparing to other sims. I don't have a strong opinion about whether or not they are included in model.md, so I'll defer to your judgement.

**Comment by samreid** [comment]
I added a few notes to the model.md in 72db2dd9be211a04ce817924db93e87b8f9035d2

Closing.
