### ISSUE TITLE
The light should deflect when the wavelength is changed

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#144]
During #44 I noticed that changing the wavelength does not deflect the light ray.  The index of refraction is a function of the wavelength (this is correct in the code) but it looks like the index of refraction is not updated when the wavelength is changed.  I'll look at adding this dependency shortly.

**Comment by samreid** [comment]
Fixed above, @ChandrashekarBemagoni please review my change.

**Comment by ChandrashekarBemagoni** [comment]
Thanks @samreid . it's good

**Comment by ChandrashekarBemagoni** [comment]
closing #144
