### ISSUE TITLE
Add @private @public annotations for member variables

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#145]
The Bending Light code has good `@private/@public` annotations for methods, but I don't see them for the member variables.  For instance, in IntensityMeter.js the constructor concludes like so:

```js
    // vector to store sensor position
    this.newSensorPosition = new Vector2();

    // vector to store body position
    this.newBodyPosition = new Vector2();

    // accumulation of readings
    this.rayReadings = [];
```

It would be very helpful to know whether each of these is private (use by the file only) or public (part of the public external API).  I think every file would benefit from these annotations. Each can be a line comment like so:

```js
// @public
```

**Comment by samreid** [comment]
Linking back to #44

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid  for review

**Comment by samreid** [comment]
Skimming through the change set above, this looks excellent.  Closing.
