### ISSUE TITLE
Pass beforeLightLayer and beforeLightLayer2 to IntensityMeterNode instead of the bendingLightView

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#148]
During #44 I observed that the IntensityMeterNode takes the bendingLightView as an argument.  However, passing the entire view into the IntensityMeterNode breaks modularity to some degree.  What the IntensityMeterNode actually uses is the bendingLightView.beforeLightLayer and bendingLightView.beforeLightLayer2.  I recommend passing these 2 layers into the IntensityMeterNode instead of the entire view to reduce coupling.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in  above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great, thanks.  Closing.
