### ISSUE TITLE
Pass layers instead of the entire view to ProtractorNode

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#149]
Same as #148 but for the ProtractorNode.  See #44

**Comment by samreid** [comment]
Same issue for ExpandableProtractorNode

**Comment by samreid** [comment]
Same issue for VelocitySensorNode

**Comment by samreid** [comment]
Same issue for WaveSensorNode

**Comment by samreid** [comment]
Same issue for PrismToolboxNode

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great, thanks.  Closing.
