### ISSUE TITLE
Should sensors be draggable when behind the control panels?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#152]
In this screenshot, the intensity meter readout is behind a control panel:

![image](https://cloud.githubusercontent.com/assets/679486/9024489/e128447c-388e-11e5-9f96-917b45244dee.png)

However, I can still grab + drag it with the mouse (say, if I click through the word "material").  Should the control panel intercept these mouse events, or is this by design?  Or is this bug a feature?

**Comment by arouinfar** [comment]
@samreid, the tools should be layered above the panels. The current layering matches the Java version, but we've decided to address it internally before publication. This will be taken care of in #66, so closing this issue.
