### ISSUE TITLE
Performance issues for various scenarios on iPad3

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#153]
During #44 I was reviewing the performance.  There are a number of specific performance issues such as #53 #29 #22 etc but I am seeing more general performance problems in the user interface on iPad3 running iOS8.  

* Intro screen, dragging the laser pointer back and forth (with it off): 10fps
* Intro screen, dragging the laser pointer back and forth (with it on): 5fps
* Intro screen, dragging the protractor with the laser off: 10fps
* Intro screen, dragging the material slider back and forth: 8fps
* Prisms screen, dragging the circle prism with the laser off: 10fps

@ariel-phet can you ask someone with an iPad2 to check these same scenarios by running this link:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.5/bending-light_en.html?profiler

**Comment by samreid** [comment]
After fixing #160 (and several other things) the performance on iPad3 is:

* Intro screen, dragging the laser pointer back and forth (with it off): 22fps
* Intro screen, dragging the laser pointer back and forth (with it on): 16fps
* Intro screen, dragging the protractor with the laser off: 30fps
* Intro screen, dragging the material slider back and forth: 16fps
* Prisms screen, dragging the circle prism with the laser off: 11fps

**Comment by phet-steele** [comment]
iPad 2, iOS 8.3 (Witten). 1.0.0-dev.5 --> 1.0.0-dev.6
    Intro screen, dragging the laser pointer back and forth (with it off): 27fps --> 27fps
    Intro screen, dragging the laser pointer back and forth (with it on): 15fps --> 16fps
    Intro screen, dragging the protractor with the laser off: 40fps --> 45fps
    Intro screen, dragging the material slider back and forth: 25fps --> 25fps
    Prisms screen, dragging the circle prism with the laser off: 15fps --> 15fps

iPad Air 2, iOS 8.3 (Leibniz). 1.0.0-dev.5 --> 1.0.0-dev.6. Generally has great performance.
    Intro screen, dragging the laser pointer back and forth (with it off): 54fps --> 54fps
    Intro screen, dragging the laser pointer back and forth (with it on): 31fps --> 32fps
    Intro screen, dragging the protractor with the laser off: 60fps --> 60fps :+1:
    Intro screen, dragging the material slider back and forth: 60fps --> 60fps :+1:
    Prisms screen, dragging the circle prism with the laser off: 55fps --> 55fps

**Comment by samreid** [comment]
After reimplementing the circle prism node from immutable->mutable, using deltas for translation, tested on iPad3 with a built version
Prisms screen, dragging the circle prism with the laser off: 12fps

**Comment by bryo5363** [comment]
iPad 2 iOS 8.4.1 (Lave) 1.0.0-dev.7 

Intro screen, dragging the laser pointer back and forth (with it off): 41fps
Intro screen, dragging the laser pointer back and forth (with it on): 18fps
Intro screen, dragging the protractor with the laser off: 33fps
Intro screen, dragging the material slider back and forth: 26fps
Prisms screen, dragging the circle prism with the laser off: 29fps

**Comment by samreid** [comment]
Comparing the original report to latest version:

Intro screen, dragging the laser pointer back and forth (with it off): 10fps => 27fps
Intro screen, dragging the laser pointer back and forth (with it on): 5fps => 20fps
Intro screen, dragging the protractor with the laser off: 10fps => 30fps
Intro screen, dragging the material slider back and forth: 8fps => 20fps
Prisms screen, dragging the circle prism with the laser off: 10fps => 26fps.

These are huge advantages and in my opinion good enough to publish with.  Performance issues for more complex scenarios are addressed in other issues.  I'm going to close this one.
