### ISSUE TITLE
Check for memory leaks

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#155]
#44 suggested we check for memory leaks.  I used the timeline view in chrome and dragged the activated laser on the intro screen and saw this result:

![image](https://cloud.githubusercontent.com/assets/679486/9027870/0a9e6be4-3923-11e5-8323-6804a51eac06.png)

So it looks like there is a memory problem--the js heap is tracking with the number of nodes created.  What are all these nodes?  Why aren't they being cleaned up?

**Comment by samreid** [comment]
I did a heap comparison after dragging the activated laser for 20+ seconds and saw this result:

![image](https://cloud.githubusercontent.com/assets/679486/9027888/cf2d8698-3923-11e5-9703-7dadb659e0a9.png)

According to https://groups.google.com/forum/#!topic/google-chrome-developer-tools/517M_CIytbA the values are in bytes, so this just adds up to around 10kb--doesn't seem like that much of a problem from this perspective.  Not sure how to reconcile this with the range 38-111MB from the previous pic.

Can @jonathanolson @jbphet @pixelzoom @aaronsamuel137 or @jessegreenberg help me look into this?  I could use some help.

**Comment by jonathanolson** [comment]
The 'nodes' part of the chart indicates the count of DOM nodes is steadily increasing, and might explain the missing (significant) gap. I can help look into it.

**Comment by samreid** [comment]
@jonathanolson I'd love your help on this.  Let me know when it's a good time for you.

**Comment by jonathanolson** [comment]
Skype me sometime tomorrow during normal hours, or recommend a time tomorrow?

**Comment by samreid** [comment]
Does 9:30am Wednesday work for you?

**Comment by jonathanolson** [comment]
After testing for a longer time:
![bending-light-gc](https://cloud.githubusercontent.com/assets/480878/9094694/8d5a7aa6-3b70-11e5-93a0-0395836d8963.PNG)

Looks like we aren't permanently leaking, it's just that the nodes hadn't been collected yet.
