### ISSUE TITLE
PrismNode Listeners need to be unlinked

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#156]
During #44 I looked through the link calls in the simulation and the only one for dynamic components seemed to be in PrismNode.  In PrismNode, there are two links calls for dynamically created Prism model elements.  The link calls should be unlinked when the node is destroyed, otherwise memory will leak.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
I think the listener at the end of the constructor needs to be unlinked too.

```js
    prismsBreakModel.prismMediumProperty.link( function( prismMedium ) {
      var color = prismMedium.color;
      prismTranslationNode.fill = color;
      prismTranslationNode.stroke = color.darkerColor( 0.9 );
    } );
```

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Thanks, this is unlinked properly now.   My only remaining recommendation for PrismNode is to change the listeners from
 `this.updatePrismColor` and `this.updatePrismShape` 

to
`var updatePrismColor` and `var updatePrismShape`

Since everything is happening in the constructor, I think these can just be safe closure variables instead of exposed publicly as instance variables.

**Comment by ChandrashekarBemagoni** [comment]
`this.updatePrismColor` and `this.updatePrismShape`  are also used in the prismToolboxNode. So these are declared as instance variables

**Comment by samreid** [comment]
I added docs to indicate that these variables are used in prismToolboxNode.  Closing.
