### ISSUE TITLE
<after code review> QA Testing

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#157]
Numerous beneficial changes to the Bending Light code are being made as part of the code review.  I would recommend once the review is complete or nearing completion, we assign a single QA tester to test a single platform to make sure no new bugs have been introduced during review changes, before AC invoices (as part of a "confirming that the review changes are good" step).

Still several days until we would be ready for this but I wanted to give you a heads up about this recommendation. 

@ariel-phet replied:

> Hey Sam,

> Sounds good. When the time comes, just make a tasks issue, describe what you think should be done (choosing the platform etc), and assign it to me.

> Ariel 

This issue is to help me remember the QA step when it is time. See #44

**Comment by samreid** [comment]
I'm going to assign this to @ChandrashekarBemagoni.  @ChandrashekarBemagoni after you have finished working on the review issues from #44 can you let me know and I will request QA testing once more?

**Comment by ChandrashekarBemagoni** [comment]
Done with code review issues. Assigning to @samreid to proceed further

**Comment by samreid** [comment]
@ariel-phet the code review is complete and I'd like to request a QA test to see if any additional work is required from Actual Concepts for follow-up from the code review.  This will be a bit trickier than a normal QA test because there are several in-progress issues by @samreid where things are broken--so QA testers will need to be careful to search through open issues before creating new issues.  We are doing the code review now instead of after all work is complete so that Actual Concepts will be able to invoice for their final work.  I published http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.29/bending-light_en.html and would like to take it for a test drive on a number of platforms before reassigning to our QA team for testing.  Also, a reminder to myself for setting up the tasks issue, that testing should be done with ?webgl=false on at least one platform.

**Comment by samreid** [comment]
Testing on the following platforms:

OSX El Capitain Firefox
OSX El Capitain Safari
OSX El Capitain Chrome
iPad3 Safari
Windows 8 IE
Windows 8 Firefox

OSX El Capitain Firefox wave view looks jagged:
![image](https://cloud.githubusercontent.com/assets/679486/9853812/d22675ce-5ac2-11e5-90b6-7c1016afac13.png)

Speedometer sometimes obscured:
![image](https://cloud.githubusercontent.com/assets/679486/9853864/1c35fbda-5ac3-11e5-8751-1bd3b4bc7616.png)

Still seeing phase issues (I think this is noted elsewhere)
![image](https://cloud.githubusercontent.com/assets/679486/9853900/5059324c-5ac3-11e5-9d20-23922f9f9b93.png)

Safari: I'm seeing huge discrete color jumps instead of a continuous spectrum when dragging the wavelength slider.

Controls are floating left/right, shouldn't they also float north/south?
![image](https://cloud.githubusercontent.com/assets/679486/9853999/bf196184-5ac3-11e5-9881-ded57137ae7d.png)

More Tools Protractor doesn't reset on reset all

I'll test the Windows platforms in the next issue comment.

**Comment by samreid** [comment]
@ariel-phet let's discuss whether we should really QA test the sim at this point.  There are many open issues and I'm not sure how many issues would be assigned to @ChandrashekarBemagoni or our team after the review is done.  Please review all comments above and let's discuss.

**Comment by ariel-phet** [comment]
@samreid - I think that can be your call. If you feel the sim is in a place where enough changes have been made, and we are basically driving it, we could close our contract with Actual Concepts, accept delivery, finish fixes ourselves, and go through our normal internal cycle.

**Comment by samreid** [comment]
I haven't seen any issues yet that Actual Concepts should solve.  If I see one in the future, I will create an issue for it (I believe there is still one platform left to test).  But for now, this seems good to close.
