### ISSUE TITLE
Error when using Wave Mode

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#16]
When selecting wave mode with the chrome dev tools open, I see this error
`TypeError: undefined is not a function`

```js
//IntroView.js line 280
lightWaves[ i ].step();
```

**Comment by ChandrashekarBemagoni** [comment]
Fixed in  latest code. Assigning to @samreid  for review.

**Comment by samreid** [comment]
I no longer see that error in the console, closing.
