### ISSUE TITLE
Solid rays should be rendered with canvas on the Prisms screen to improve performance 

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/bending-light#162]
For Prisms screen, it would probably be a major performance gain, and potentially be a bit simpler.

For the Intro/More Tools screens, leaving 3 SVG lines is probably best.

@ariel-phet, who should potentially work on this?

**Comment by samreid** [comment]
The CanvasNode implementation appears above.  It is working remarkably well on iPad3.  After other performance optimizations, we will have to decide if canvas is good enough or if we need a webgl variant as well.  The webgl implementation would not be complicated here, just drawing lines or pairs of triangles.  Line caps may make things a bit more complicated, if necessary.

**Comment by samreid** [comment]
I'll retitle this issue to be about canvas, and open a new one about WebGL.
