### ISSUE TITLE
Simpler creation of circle shapes

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#164]
Circles are currently created like;

```js
    this.shape = new Shape().ellipticalArcPoint( this.center, this.radius, this.radius, 0, 0, Math.PI * 2, false );
```

But perhaps it would be better to create them like so:
```js
this.shape = Shape.circle( this.center.x, this.center.y, this.radius );
```

I tested that in my working copy and it seemed to behave properly.  I'll commit then reassign to @ChandrashekarBemagoni to verify.

**Comment by samreid** [comment]
Fixed above, @ChandrashekarBemagoni can you verify?

**Comment by ChandrashekarBemagoni** [comment]
Now it's much simpler.

**Comment by ChandrashekarBemagoni** [comment]
Thanks
Closing #164
