### ISSUE TITLE
Generalize the IntensityMeter

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#165]
From #151, @ariel-phet said:

> The intensity meter should definitely be common code since it is used in this sim, and beers law lab. (and likely will appear in other sims).

**Comment by samreid** [comment]
@ariel-phet suggested making it a developer-meeting topic for whether this should be factored out.

It looks like Beers Law Lab uses ATDetectorNode.js which appears pretty similar.  

Differences:
1. The body has a different readout
2. BLL body not draggable

**Comment by pixelzoom** [comment]
The piece that looks worth generalizing is the probe.  The rest is sim-specific.  Note that bending-light draws the probe programmatically (IntensiteMeterNode.js), beers-law-lab uses an image (at-detector-probe.png).

**Comment by samreid** [comment]
@samreid will work on factoring out the code that draws the probe shape and reusing it for beers law lab.

**Comment by samreid** [comment]
It belongs in scenery-phet.

**Comment by samreid** [comment]
I have done the generalization and migration of the LightSensorNode in this issue, with outstanding issues noted above.  I'll create an issue in Beers Law Lab to use this sensor.

**Comment by samreid** [comment]
I've completed my preliminary draft of LightSensorNode and it is ready for a reviewer.  After generalization and review is complete, we should use this node in Beers Law Lab in https://github.com/phetsims/beers-law-lab/issues/111 .  @pixelzoom may wish to be involved since he is the primary developer for Beers Law Lab, so I'll assign to him for now.  @pixelzoom if you are too busy or would prefer to defer or have someone else work on this, please let me know.

**Comment by samreid** [comment]
Another question for the reviewer.  This is currently "LightSensorNode", but I'm wondering if we want to put the word "Probe" in there somewhere.

**Comment by pixelzoom** [comment]
I'll have a look, but probably not until next week.

**Comment by pixelzoom** [comment]
This bit of code in LightSensorNode is buggy:

```js
 // constants
  var DEFAULTS = {
    width: 100,
    height: 151 
  };

function LightSensorNode( options ) {
    options = _.extend( DEFAULTS, options );
```

`_.extend( object, options )` modifies `object`.  So the first call to LightSensorNode that specifies `options.width` or `options.height` will modify the defaults used for all subsequent instantiations.

**Comment by pixelzoom** [comment]
Fixed above by cloning DEFAULTS, i.e.:

`options = _.extend( DEFAULTS.clone(), options );`

**Comment by pixelzoom** [comment]
Review comments:

(1) Why is this called LightSensorNode? It could be used as other types of probes. Perhaps SensorNode or ProbeNode?

(2) #178 needs to be addressed: there's something wrong with the Path

(3) #179 needs to be addressed. This is not "generalized" until the colors can be tailored to the simulation. bending-light and beers-law-lab happen to be the same, that's unlikely to be true in general.

(4) #180 needs to be addressed. This is clearly broken with what are very legitimate values for width and height.

(5) Add an option to adjust the width of the probe's handle. 

(6) Add an option to show crosshairs in the center of the probe. 

#179, (4) and (5) would allow this to be reused for the Concentration probe in beers-law-lab, the pH probe in ph-scale, etc.  Compare:

![screenshot_597](https://cloud.githubusercontent.com/assets/3046552/9693314/a2a83a5c-530c-11e5-81e4-d8a84db18801.png)
![screenshot_598](https://cloud.githubusercontent.com/assets/3046552/9693319/a66d4bf0-530c-11e5-8696-918e5e5807e0.png)

**Comment by pixelzoom** [comment]
Additional comments:

(7) This probe should work in various orientations (see Concentration and pH Scale probes).  Simply rotating the node will result in incorrect lighting cues.  So probably need an option for specifying orientation?

**Comment by samreid** [comment]
(1) ProbeNode sounds great to me, I'll convert to that.

**Comment by samreid** [comment]
Renamed to ProbeNode above.

**Comment by samreid** [comment]
Also renamed instance vars above.

**Comment by samreid** [comment]
> (7) This probe should work in various orientations (see Concentration and pH Scale probes). Simply rotating the node will result in incorrect lighting cues. So probably need an option for specifying orientation?

Rather than trying to vectorify all of the geometry, a simpler approach may be to just rotate the gradients.  @pixelzoom how does that sound to you?

**Comment by samreid** [comment]
(1)-(4) are addressed above, and some reassigned to @pixelzoom for review/discussion in separate issues.  (7) is under discussion in the above comment. For (5) I have done the following:

1. Made the shape circular instead of ellptical
2. Parameterized these options (and defaults):

```js
{
    radius: 50,
    handleWidth: 50,
    handleHeight: 30,
    handleCornerRadius: 30,
    color: '#008541' // darkish green
  }
```

I have also temporarily linearized the probe handle segments for simplicity so we can discuss what the behavior should be as a function of radius, handleWidth/handleHeight before I curve everything again.  @pixelzoom please run the latest scenery-phet demo and play with those 3 sliders and let me know if you have recommendations for how they should behave for the simplified linear case.  If this is agreeable, then I'll take the next step to smooth and round the corners.

**Comment by pixelzoom** [comment]
> Rather than trying to vectorify all of the geometry, a simpler approach may be to just rotate the gradients. @pixelzoom how does that sound to you?

Sounds great if it provides the desired lighting effect.

**Comment by pixelzoom** [comment]
Bugs, see demo screenshot below:
• Handle corner radius is not working, the corners are square at all positions of the slider. 
• The bottom portion of the glass surround is straight lines, shouldn't it be rounded?

![screenshot_606](https://cloud.githubusercontent.com/assets/3046552/9768216/830424a0-56df-11e5-8d92-61d76f5286c5.png)

**Comment by pixelzoom** [comment]
It would be nice to show values and range (ticks) for the sliders. Consider using NumberControl, see examples in SpringControls.

**Comment by pixelzoom** [comment]
I switched the controls in the demo from HSlider to NumberControl.

**Comment by samreid** [comment]
From https://github.com/phetsims/bending-light/issues/165#issuecomment-138772452 above, @samreid said:

> I have also temporarily linearized the probe handle segments for simplicity so we can discuss what the behavior should be as a function of radius, handleWidth/handleHeight before I curve everything again. @pixelzoom please run the latest scenery-phet demo and play with those 3 sliders and let me know if you have recommendations for how they should behave for the simplified linear case. If this is agreeable, then I'll take the next step to smooth and round the corners.

**Comment by pixelzoom** [comment]
Replaced the WavelengthSlider with RGB controls.

**Comment by pixelzoom** [comment]
> ... @pixelzoom please run the latest scenery-phet demo and play with those 3 sliders and let me know if you have recommendations for how they should behave for the simplified linear case. 

Sorry, I missed that.  

Based on the linearized demo, I think that options.handleWidth should be constrained to be <= (2 * options.radius).  When options.handleWidth === ( 2 * options.radius ), the probe will have no "waist", since the handle will be as wide as the glass surround.

**Comment by pixelzoom** [comment]
Also sorry if I didn't associate a few commits with this issue. I forgot that this issue is in bending-light and the other associated issues are in scenery-phet, so may not have mentioned the issues correctly in the commits.

**Comment by samreid** [comment]
> Based on the linearized demo, I think that options.handleWidth should be constrained to be <= (2 * options.radius). When options.handleWidth === ( 2 * options.radius ), the probe will have no "waist", since the handle will be as wide as the glass surround.

How to capture this relationship in the sliders in the demo, if at all?  Some options: (a) when the radius gets smaller, the handleWidth slider will shrink to compensate.  (b) just clamp the values before sending them to the ProbeNode constructor.  @pixelzoom do you have a preference here?

> I forgot that this issue is in bending-light and the other associated issues are in scenery-phet.

In retrospect, I should have moved this to scenery-phet long ago.  Will do for future ones.

**Comment by pixelzoom** [comment]
> How to capture this relationship in the sliders in the demo, if at all? 

(b) just clamp the values before sending them to the ProbeNode constructor.

**Comment by pixelzoom** [comment]
.. or perhaps (c) clamp options.handleWidth internally in ProbeNode.  If it's not clamped internally, then there should be an assertion at line 44:

`assert && assert( options.handleWidth <= ( 2 * options.radius ) );`

**Comment by pixelzoom** [comment]
Doc (line 4) in ProbeNode still refers to this as being specific to light:

> A light sensor probe, used in simulations like Bending Light and Beer's Law Lab to show how much light is being

**Comment by pixelzoom** [comment]
Recommended to rename DEFAULTS to DEFAULT_OPTIONS.

**Comment by samreid** [comment]
> (c) clamp options.handleWidth internally in ProbeNode.

This seems the most friendly to me, let's go for it.

**Comment by samreid** [comment]
Summarizing outstanding work from above:

- [ ] Add an option to show crosshairs in the center of the probe. 

- [ ] Option to just rotate the gradients so the probe can be used at different angles.

- [ ] options.handleWidth should be constrained to be <= (2 * options.radius)

- [ ] Doc (line 4) in ProbeNode still refers to this as being specific to light:

- [ ] Recommended to rename ProbeNode.DEFAULTS to DEFAULT_OPTIONS.

**Comment by samreid** [comment]
For crosshairs, we will need to cut a hole out of the sensor shape.  This will make the Shape creation significantly more complicated.

**Comment by samreid** [comment]
> Based on the linearized demo, I think that options.handleWidth should be constrained to be <= (2 * options.radius). When options.handleWidth === ( 2 * options.radius ), the probe will have no "waist", since the handle will be as wide as the glass surround.

Here is a waist-less ProbeNode:
![image](https://cloud.githubusercontent.com/assets/679486/9771778/7a284dd2-56f5-11e5-87d5-47432b4fde0b.png)

I'm not sure why we must prevent this situation?  Perhaps some sim will want a probe shaped like that?

**Comment by samreid** [comment]
@jonathanolson what is the best way to create a shape with a hole in it?  Trace the outside then jump to the inside and trace it in the opposite direction?  Is there danger of a seam appearing?

**Comment by jonathanolson** [comment]
> @jonathanolson what is the best way to create a shape with a hole in it? Trace the outside then jump to the inside and trace it in the opposite direction? Is there danger of a seam appearing?

Yes, tracing it in the opposite direction is the perfect way to do it (Scenery uses SVG/Canvas default 'nonzero' fill rule, see https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule).

There should be no seam if there is a moveTo equivalent between inside/outside. I'd recommend both the inside and outside should be closed.

If you are drawing a circular hole, this may require a moveTo to the location at angle 0 along the circle, before calling shape.circle().close(). It seems annoying to do so, and if it would be used much should be replaced with a Kite feature for preventing shapes from being connected (it mirrors the Canvas API, and drawing two circular arcs would cause them to be connected in Canvas if there is no moveTo in-between).

**Comment by samreid** [comment]
Thanks @jonathanolson, I cut a hole out of the probe node in this commit:
https://github.com/phetsims/scenery-phet/commit/c1e3b95238bf7c62c846b00264cbfc4188ccba69

**Comment by samreid** [comment]
I added an option for sensorType in the above commit, documented like so:

```js
    // The circular part of the ProbeNode is called the sensor, where it receives light or has crosshairs, etc.
    sensorType: 'glass' // {'glass'|'empty'|'crosshairs'}
```

However, each of the sensor types have their own parameters.  For instance, the line width of the crosshairs, or the color of the glass.  I'm looking for the best pattern to use here.  I think we have faced this issue before (nested options), in scenery nodes or the like.

**Comment by samreid** [comment]
I updated the interface for the sensor type (such as empty/glass/crosshairs) so they are parameterized, with defaults.  To get the default crosshairs, you use:

```js
probeType:ProbeNode.crosshairs()
```

To customize, you pass options like so:
```js
probeType:ProbeNode.crosshairs({stroke:'green',lineWidth:6,intersectionRadius:4})
```

@pixelzoom I have tested a few configurations manually and it seems good.  I was hesitant to put all of these features into the scenery-phet example because it would mean creating radio buttons to choose sensor type, then several more controls for each customizable feature.  And the example is already getting pretty full.  Thoughts?

**Comment by samreid** [comment]
I just pushed options for glass above.

**Comment by samreid** [comment]
Should the crosshairs and glass default options be public?

**Comment by samreid** [comment]
@pixelzoom I'm trying to make a number control for the highlight angle, but its coming out like this:

![image](https://cloud.githubusercontent.com/assets/679486/9792765/11a592ba-579f-11e5-977a-0bd23a79827b.png)

and snapping to integer.  Is NumberControl primarily for integers?  I didn't see options for `snap` in that file.

**Comment by pixelzoom** [comment]
See options.decimalPlaces

**Comment by pixelzoom** [comment]
If you want the max tick to be labeled 2π, you'll need to set that yourself via options.majorTicks.

**Comment by pixelzoom** [comment]
> @pixelzoom I have tested a few configurations manually and it seems good. I was hesitant to put all of these features into the scenery-phet example because it would mean creating radio buttons to choose sensor type, then several more controls for each customizable feature. And the example is already getting pretty full. Thoughts?

I don't think it's necessary to have controls in the demo for all options.  If you wanted to demonstrate the 3 sensor types, a combo box would use the least amount of space, and you could use some specific sensor-options for the 3 choices.

**Comment by samreid** [comment]
@pixelzoom can you respond to this comment?
https://github.com/phetsims/bending-light/issues/165#issuecomment-139019886

**Comment by pixelzoom** [comment]
I was thinking that this (see screenshot below) would be a more useful shape, when options.handleWidth === 2 * options.radius.  But your hypothetical need is as valid as mine, so proceed with what you think is best.

![screenshot_75](https://cloud.githubusercontent.com/assets/3046552/9806058/4a11b22e-57fd-11e5-8a4a-da0a4c0cad31.png)

**Comment by samreid** [comment]
Based on the above discussions, here's a fresh "todo for this issue" checklist:

- [ ] Option to just rotate the gradients so the probe can be used at different angles.

- [ ] Add a control to test the gradient angle, use options.decimalPlaces for snapping and options.majorTicks for 2pi label.

- [ ] round the shapes again

- [ ] Make the crosshairs and glass default options public

- [ ] Let's add more controls for the other probe node options while we are here.

**Comment by samreid** [comment]
In retrospect, I feel this is a good time to split the outstanding work into separate issues in the appropriate repos and close this parent issue.

**Comment by samreid** [comment]
I bundled the outstanding issues into the 3 above related issues.  @pixelzoom did I capture everything and may I please close this parent issue?

**Comment by pixelzoom** [comment]
I don't see an issue for how to address the relationship (if any) between options.handleWidth and options.radius.

**Comment by samreid** [comment]
Based on https://github.com/phetsims/bending-light/issues/165#issuecomment-139435362 and https://github.com/phetsims/bending-light/issues/165#issuecomment-139019886 let us not constrain the relationship between handleWidth and radius.  OK?

**Comment by pixelzoom** [comment]
OK, we'll address constrain the relationship between handleWidth and radius if/when it comes up.

All sub-issues moved elsewhere. Closing this issue.
