### ISSUE TITLE
Unify prisms in toolbox with prisms dragged out of toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#166]
The prism icons in the toolbox have a completely different icon and input listener than the prism nodes dragged in the play area.  I noticed this when I changed the renderer for play area prism nodes to scenery.Circle, and the icons didn't change.  These should be unified.  Note this relates significantly to #7

**Comment by samreid** [comment]
Unifying these into the same node would also mean that prisms need a flag for enabled/disabled and the ability to change size.  One option (perhaps the best option?) would be just to unify their renderers (same function, different instance).

**Comment by samreid** [comment]
I was able to unify the implementations in the above commit.  There is now an issue that when dragging a certain prism from the toolbox, another of the same type cannot be dragged from the toolbox.  You have to release the first prism before another prism of the same type can be dragged from the toolbox.  This behavior is undesirable, but it could take 2-4 hours to address it.  @ariel-phet will you please make the call here about whether it is worth the effort to try to fix it?

**Comment by samreid** [comment]
@ariel-phet here's a link you can review:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.23/bending-light_en.html

**Comment by ariel-phet** [comment]
@samreid, I am not sure I understand the issue. Do you mean if you are dragging one prism out and then with *multitouch* you want to drag the same one out you cannot? It seems totally acceptable to have the constraint of only be able to drag out one thing at a time. Why is that behavior undesirable?

**Comment by samreid** [comment]
> Do you mean if you are dragging one prism out and then with multitouch you want to drag the same one out you cannot?

Yes, that is the behavior I described.  I have seen too many occurrences where 2 people want to use the iPad at the same time and it is possible to envision a classroom with 2 student/iPad ratio.

It sounds like you are saying this not worth the effort to fix?  I'd be fine with that decision.

**Comment by ariel-phet** [comment]
Not worth the effort to fix, and in fact I think the current behavior is a desirable constraint for the sim. Closing.
