### ISSUE TITLE
Performance dragging a single prism is abysmal

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#167]
When just dragging a single prism (tests done with Circle), the performance on iPad3 is abysmal, coming in at <15fps.  I tried converting to a mutable pattern, see notes #153 and even changing the renderer from Path(circle) to Circle() and it still was <15fps on iPad3.  This is all with the laser off and will need to be much faster.

**Comment by samreid** [comment]
I'm wondering if we could drag these with WebGL, and what performance that would give.  Note: the objects currently have an outline, which is a bit harder to do with WebGL at the moment.

**Comment by samreid** [comment]
@ariel-phet suggested just creating a Circle node all by itself (in the context of the sim) and seeing what dragging performance it gets.  Maybe try opaque vs transparent.

**Comment by samreid** [comment]
Performance dragging a single opaque rectangle in front of everything is great on iPad3:

```js
var rectangle = new Rectangle( 0, 0, 100, 100, { fill: 'blue' } );
    rectangle.addInputListener( new SimpleDragHandler( {
      translate: function( a ) {
        rectangle.translate( a.delta );
      }
    } ) );
    this.addChild( rectangle );
```

**Comment by samreid** [comment]
Performance still great (for iPad3) with opacity:0.5

**Comment by samreid** [comment]
Changing the PrismNode translate to just setTranslation() on the view (skip model step) and moving it to the front layer still has pretty bad performance (worse than the rectangle above).  Not sure what is going on here.

**Comment by samreid** [comment]
I tried setting renderer:webgl and things are very smooth, but there are the following issues:
1. Regenerating the prism shapes when color changes is unusably slow
2. There is a long 4-5 second lag when dragging the first object.  Perhaps WebGL is "warming up"?

**Comment by samreid** [comment]
Changing to renderer:canvas and removing the stroke seems like somewhat of an improvement.  I'm really wondering if we can discuss scheduling time to work on scenery's WebGL renderer for Paths to get this to work.  The prisms are opaque, and many of them are just 2 triangles.  Using renderer:webgl for this would mean (a) no separate implementations for non-webgl platform and very smooth performance for dragging these shapes.  @ariel-phet and @jonathanolson can we talk about working on the scenery webgl path support?

**Comment by samreid** [comment]
See my notes in #176 about using cssTransform:true.  It is a miracle worker for the prisms on the iPad3 as well.

**Comment by samreid** [comment]
From #74:

> Testing one circle prism with a 5-ray, and dragging the circle in the 5-ray, I see 7fps on iPad3 running iOS 8.4. Commenting out the rays ObservableArray only bumps this up to 12fps, so there is surely something else at play here.

> Putting cssTransform:true on the prisms rockets this up to 15fps, which somehow feels fast enough. (Maybe my standards have been lowered?)

**Comment by samreid** [comment]
We are using cssTransform:true for prisms at the moment and the prisms are getting truncated on the top and left of the play area, see https://github.com/phetsims/scenery/issues/454

**Comment by samreid** [comment]
We are up to around 19-20fps for dragging the circle on iPad3, on iPad2 it will likely be 20-30% faster faster based on https://github.com/phetsims/bending-light/issues/153  In my opinion this is good enough to publish for iPad3.  If others think this is too slow, the next optimization step would be working on Shape support for WebGL in scenery.

**Comment by samreid** [comment]
@arouinfar and/or @ariel-phet can you review performance dragging a single prism with the laser off in this version and let me know if we can close this issue or if we should open discussions about integrating Shape support in WebGL (the latter would be a long process that heavily involves @jonathanolson)?

http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.13/bending-light_en.html

**Comment by arouinfar** [comment]
@ariel-phet can you test this (or reassign to the appropriate QA tester)? I won't have access to an iPad while out of town.

**Comment by ariel-phet** [comment]
Tried iPad2, performance looked good to me! Closing
