### ISSUE TITLE
Use PropertySet.addProperty instead of Proprety.addProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#168]
PrismsScreenModel subclasses PropertySet but it is adding the properties through Property.addProperty(this,....).  I wonder if it would be possible to use this.addProperty(....).  I'll take a look and if it seems like it is working properly I'll reassign to @ChandrashekarBemagoni to verify my work.

**Comment by samreid** [comment]
Fixed above, @ChandrashekarBemagoni can you take a look at my change and let me know if you suspect any issues?  Close if everything seems ok.

**Comment by ChandrashekarBemagoni** [comment]
Reviewed , no issues with latest changes.

**Comment by ChandrashekarBemagoni** [comment]
closing #168
