### ISSUE TITLE
Float the control panels to the sides

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#171]
For all 3 screens.

**Comment by samreid** [comment]
Fixed above, but I will need to test more broadly and post a dev version for review.

**Comment by samreid** [comment]
I used 1.5 of the layout bounds as the max for the rightmost edge of the control panels, so this is as far as they will get away:

![image](https://cloud.githubusercontent.com/assets/679486/9376516/57708cc6-46cb-11e5-97d2-d5899180df6b.png)

Here is a version for testing:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.12/bending-light_en.html

@arouinfar please test and let me know if the 1.5 rule is good, or if you want to start constraining them at a different value.

**Comment by arouinfar** [comment]
The 1.5 rule seems good to me, though only floating the menus on the right feels a little unbalanced. Can you chime in @ariel-phet?

**Comment by ariel-phet** [comment]
Agreed, @samreid lets float the left control panels to the left as well for balance.

**Comment by samreid** [comment]
All of the draggable sensors are written with the assumption of a non-moving control panel.  I can change that, but it will take 6+ hours to get it working for all sensors and will increase the complexity of the code slightly, so I wanted to confirm with @ariel-phet before proceeding.

**Comment by ariel-phet** [comment]
@samreid Performance issues are definitely the priority, but considering the cramped play area, and the very unbalanced view you get with the normal active and the controls floated to the right, I think it is worth the effort.

**Comment by samreid** [comment]
Looks like the prisms screen is done here.  I'll start on the Protractor drag bounds next.

**Comment by samreid** [comment]
Protractor is good now and the intensity meter got coalesced drag handlers.  The intensity meter needs a lot more work.

**Comment by samreid** [comment]
All that remains to be done here is fixing the time sensor and velocity sensor on the more tools screen.  We can use the same strategy as in the other sensors.

**Comment by samreid** [comment]
Also, I'm not sure how the protractor is detecting the right toolbox bounds, unless it is using a mutable value???

**Comment by samreid** [comment]
I think it's using a mutable node bounds2, which is a relatively new feature in scenery.  @jonathanolson is that okay to rely on?

**Comment by samreid** [comment]
Everything is complete here except for what is noted in other issues above.  Closing.
