### ISSUE TITLE
Modularize BendingLightView

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#175]
BendingLightView is the parent class for PrismsView and IntroView.  However, it adds the wave layer node and white light node and *many* other nodes.  Each of these nodes is only used by one of the screens, and since performance is a serious problem in this sim, we should (a) prune down what is happening in BendingLightView or refactor things so that each screen gets only what it needs.

@ChandrashekarBemagoni I'm thinking of assigning this to myself but would love to hear your thoughts on the matter.

**Comment by samreid** [comment]
It looks like a WaveWebGLNode is created even for the Prisms screen, which shouldn't have a WaveWebGLNode

**Comment by samreid** [comment]
```js
    // if WebGL is supported add WaveWebGLNode otherwise wave is rendered with the canvas.
    if ( bendingLightModel.allowWebGL ) {
      var waveWebGLNode = new WaveWebGLNode( bendingLightView.modelViewTransform,
        bendingLightModel.rays,
        bendingLightView.layoutBounds.width,
        bendingLightView.layoutBounds.height );
      bendingLightView.incidentWaveCanvasLayer.addChild( waveWebGLNode );
    }
```

**Comment by samreid** [comment]
I moved the wave view to the intro view above.

**Comment by samreid** [comment]
Across the above changes, BendingLightView is much more modular.  Reassigning to @ChandrashekarBemagoni to make him aware of the changes and to review if desired.

**Comment by ChandrashekarBemagoni** [comment]
Thanks @samreid . Now BendingLightView is much more modular.
