### ISSUE TITLE
The laser gets away from the mouse cursor

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#177]
After dragging against the edge of the window, the laser gets disassociated from the cursor.  Discovered in https://github.com/phetsims/bending-light/issues/176.

This is not a problem in the Java version and should be resolved.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in commit . Assigning to @samreid for verification

**Comment by samreid** [comment]
The behavior looks good, thanks.  Closing.
