### ISSUE TITLE
Prisms, laser and light should go behind the top-right control panels

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#178]
At this week's design meeting, we decided that the prisms, laser and light should go behind every control panel, and we'll use a rule like #71 for bumping objects to the side if they are dropped entirely behind a control panel.

**Comment by samreid** [comment]
I just realized why prisms go in front of the south control panel.  It is so when you try to drag them back to the control panel, they go in front of it (which is good).  Likewise, when you drag them out of the control panel, they don't immediately pop behind it (if they did, they would be invisible for a moment while dragging out).  @arouinfar can you discuss these issues with me?  Should we try to find workarounds that will allow us to keep the prisms behind all of the control panels, or should we keep them in front of their toolbox?

**Comment by arouinfar** [comment]
@samreid, I think it's fine for prisms to go above the bottom panel, since that is their home location. It seems natural to me that they would go above the bottom panel, but behind the side panels.  It is also impossible to lose prisms behind the bottom panel, since they will instead be removed from the playspace. Laser light, however, does not originate in either panel, so its behavior in the bottom and side panels should be consistent.

**Comment by samreid** [comment]
The laser is currently always in front of the prisms.  If we keep that as a constraint, then with the additional constraint that prisms are in front of the prism toolbox, the laser must also be in front of the prism toolbox.  Should we change one of these assumptions, or leave the laser in front of the prism toolbox?

**Comment by arouinfar** [comment]
@samreid I think we can leave the laser in front of the prism toolbox. It's currently layered above all panels.

**Comment by samreid** [comment]
Ok, I'll retitle the issue as such.

**Comment by arouinfar** [comment]
@samreid, to make sure we're on the same page, here's a summary of the layering decisions:
- [ ] Prisms, laser, and light behind top-right (side) control panels 
- [ ] Laser above prisms, and both above bottom control panel (for usability)
- [ ] Light behind the bottom control panel (for consistency)

**Comment by samreid** [comment]
With the light behind the bottom control panel, and the laser in front of the bottom control panel, it would look like this:

![image](https://cloud.githubusercontent.com/assets/679486/9315999/bbafe2e6-44ef-11e5-903f-9181ed9cf7ca.png)

Is that really what you intended?  Why not put the light in the same layer as the laser?  I think the light must technically be in front of the prisms so that it won't be obscured by them.

**Comment by arouinfar** [comment]
I think the current layering (dev.15) will do. The prisms need to be layered above the bottom panel for usability reasons, which then requires the laser and beam to also be layered above the bottom panel. I don't think we thought about this issue when deciding that the beam should be layered behind both the bottom and side panels. I'm going to go ahead and close this issue.

**Comment by samreid** [comment]
I thought we were still going to move the laser behind the top-right control panels, so we don't see this issue in that case:

![image](https://cloud.githubusercontent.com/assets/679486/9408745/86bdcd10-47d2-11e5-8672-caf356f89d13.png)

Should we still do this, or not?

**Comment by samreid** [comment]
Reassigned to @ariel-phet for feedback.

**Comment by ariel-phet** [comment]
Discussed with @samreid reassigning for him to move laser under right control panels.

**Comment by samreid** [comment]
Note: https://github.com/phetsims/bending-light/issues/178#issuecomment-134385670 will be difficult to test while #206 is broken.
