### ISSUE TITLE
White light is doing extra work

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#179]
I noticed extra beginPath/fill/closePath commands in WhiteLightNode.js.  Can these be removed?

**Comment by samreid** [comment]
Fixed above and the rendering seems the same.  Can @ChandrashekarBemagoni take a look and see if he sees any problems with this solution?

**Comment by ChandrashekarBemagoni** [comment]
There is no problem with the above solutions.

**Comment by samreid** [comment]
Thanks for reviewing, I'll close the issue.
