### ISSUE TITLE
Decide if White light pixelation is acceptable in Canvas version

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#180]
From #63, @arouinfar said:

> - [ ] White light is very pixelated compared to the monochromatic beam.
![image](https://cloud.githubusercontent.com/assets/8419308/8138165/9f684772-1105-11e5-81ac-b1266ee35f49.png)    ![image](https://cloud.githubusercontent.com/assets/8419308/8138168/a8b3f484-1105-11e5-86aa-2dab00c01982.png)

**Comment by samreid** [comment]
This will be solved by the WebGLNode #53 and we will have to discuss whether it is acceptable for the canvas version to be pixellated (for devices without WebGL).  @ariel-phet thoughts?

**Comment by ariel-phet** [comment]
Yes, I think it will be acceptable for the canvas version. I am going to change the title of this issue to reflect that, but keep the issue open.

**Comment by samreid** [comment]
Since the pixellation of the white light is acceptable, I am going to close the issue.  But I wanted to add one note that if we move toward graying out the background and showing white light as white instead of gray, see #190 and #53 then we may be able to use canvas draw calls here instead of building our own pixellated histogram.
