### ISSUE TITLE
Lag in updating index of refraction on Intro and More Tools screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#183]
Playing with dev.7 in OSX 10.9.5/latest Chrome, I found a bug on the Intro and More Tools screens. There appears to be a lag in updating the index of refraction. For example:

Open More Tools Screen, turn on the laser. Light is correctly refracted to 28*. 
![image](https://cloud.githubusercontent.com/assets/8419308/9318343/0d5b5520-4500-11e5-8ef9-e3a83e142cde.png)

Choose Air. Light remains at 28* (should be 45*).
![image](https://cloud.githubusercontent.com/assets/8419308/9318355/22ba43fe-4500-11e5-88cf-f1fc98411e3f.png)

Choose Water. Light jumps to 45* (correct for Air-Air boundary).
![image](https://cloud.githubusercontent.com/assets/8419308/9318371/46b8f17e-4500-11e5-845d-4da8e922d2ec.png)

The same also happens when adjusting the upper material's index of refraction. Assigning to @samreid.

**Comment by samreid** [comment]
Fixed in this version: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.11/bending-light_en.html

Please verify.

**Comment by arouinfar** [comment]
All fixed! Thanks @samreid. Closing.
