### ISSUE TITLE
BendingLightView.js calls clear N-1 too many times

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#184]
Clear is called each time any ray is removed.   This means clear is called N-1 too many times, which can be large.  Not sure if this would show up in the profiler, but perhaps there is a better abstraction to be used here.

Look for a comment like:
```js
// As rays are removed from model clear all light ray layers
```

**Comment by samreid** [comment]
I discovered that a separate ObservableArray of white rays was being created and passed to WhiteLightNode, but it seems like using the bendingLightModel.rays will work just as well since WhiteLightNode doesn't do any work when it is invisible.  I tested with this and didn't see any issues, will commit shortly.

**Comment by samreid** [comment]
Committed above, and this cleans up the clear() calls a bit.  @ChandrashekarBemagoni are you aware of any problems with the above change?

**Comment by ChandrashekarBemagoni** [comment]
No problem with above changes.
