### ISSUE TITLE
Prisms get away from the cursor

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#188]
Similar to #177, the prism gets away from the cursor.  This only occurs when dragging a prism from the play area, the implementation in PrismToolboxNode doesn't exhibit this problem.  Discovered during #187

**Comment by samreid** [comment]
I recommend using an approach like in PrismToolboxNode, it seems like it is working very well.

**Comment by samreid** [comment]
Also #166 is partially about reusing the drag code between the prisms from the toolbox and prisms from the play area, so we will only have one input listener or drag function we have to get right.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for verification

**Comment by samreid** [comment]
It behaves properly now, thanks @ChandrashekarBemagoni!
