### ISSUE TITLE
Should white light be white instead of gray?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#190]
Currently, "white" light is gray so that will show up against the white background.  When we started investigating the WebGL renderer for white light in #53 we found that rendering white light as white is simpler than remapping it to gray.  @jonathanolson suggested that it may be possible to use a frame buffer to remap colors as a postprocessing step, but I haven't investigated it yet.  The question is whether we should change the design of bending light to make white light actually be white (by making the background darker) instead of making white light gray.  If we decide to change the background and make the white light white instead of gray, then the canvas implementation would need to be updated to match.  Reassigned to @ariel-phet for discussion.

**Comment by samreid** [comment]
One note from #180 

> But I wanted to add one note that if we move toward graying out the background and showing white light as white instead of gray, see #190 and #53 then we may be able to use canvas draw calls here instead of building our own pixellated histogram.

**Comment by ariel-phet** [comment]
@samreid will try WebGL with gray light.

**Comment by samreid** [comment]
We decided to try gray because the background color is a function of the index of refraction, and we didn't want to come up with a different color scheme just for white light.  I'll close this issue and we can continue in #53

**Comment by samreid** [comment]
@jonathanolson and I spent a few days looking into ways to improve the performance and resolution of the light rays.  The original Java version uses a line rendering algorithm + 2d histogram approach for manually blending the colors, which is very demanding for JavaScript, even on desktop.  We looked into a way to combine the rays using canvas and got a solution working well (speedy and high resolution on desktop).  However, the rays would color-shift depending on, say, the angle of the reflected light.  For instance, the gray incoming light would color shift to green for a reflected ray.  Here is a published version with this issue:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.19-gray/bending-light_en.html?webgl=false
![image](https://cloud.githubusercontent.com/assets/679486/9615071/3053ebd2-50b3-11e5-85db-582b4b9c6ca7.png)

We believe this was due to quantization of the light when added together and oversaturation of the channels. (Reducing the values to prevent oversaturation exacerbates the quantization).  @jonathanolson correct me if I am wrong about the problem here.

To overcome this problem, we moved the alpha values into the RGB channels by premultiplying them manually.  To prevent oversaturation and hence color-shifting, we are making everything fully opaque and rendering to an opaque background ( @jonathanolson correct my details here).  This will not work for a white background, but looks great if we switch to a black background, demo is here:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.20/bending-light_en.html?webgl=false
![image](https://cloud.githubusercontent.com/assets/679486/9615223/190fa8ca-50b4-11e5-9df0-7d2094505a55.png)

Note that in this version, the canvas must be opaque and hence behind everything else--that is why the rays are now going behind the control panels.  The prisms also had to be made opaque so that the light would be visible through the prisms.  We can come up with a different color-mapping scheme for showing the background as a function of index of refraction, it looks okay until a medium gray value (128,128,128) is reached, so we still have some wiggle room there: 
![image](https://cloud.githubusercontent.com/assets/679486/9615366/db16171a-50b4-11e5-82a9-3e5112626c92.png)
Another issue this will solve is that it will take an additional step to match the prism color to the background color when their indexes of refraction are the same, but @jonathanolson said he wasn't too worried about that part.

The proposed "black background" strategy would have a direct analog in WebGL.

@jonathanolson & I wanted to stop work on this until we can discuss with @ariel-phet and @kathy-phet whether a black background will be acceptable for white light mode, or if we should continue to search for alternatives.

**Comment by samreid** [comment]
I sent this email to @arouinfar @ariel-phet and @kathy-phet:

> Amy, Ariel, Kathy,

> Jon Olson & I have been working on improving the performance of drawing the white light rays in bending light.  The algorithm from Java (building a 2D histogram of colors and painting each cell independently) is too demanding for our HTML5 platforms.  A summary of the work is given in https://github.com/phetsims/bending-light/issues/53 and https://github.com/phetsims/bending-light/issues/190 .  We ran into a number of issues when using a white background (including color shifting of the ray, so that a reflected gray ray was coming out green).  The technical details are described in this comment in #190.  We found that we could avoid the quantization and saturation errors (and hence the color-shifting problem) if we blended the alpha values into the RGB values, but this will only work for a dark, opaque background.  We could continue searching for other solutions to how to render white light for HTML5 but we were both interested in pursuing the "black background" solution and wanted to pause our efforts to discuss it with you.  The comment in #190 link above has screenshots and further discussion, please take a look and let's go from there.

> Best Regards,
Sam

**Comment by ariel-phet** [comment]
@samreid - you may want to see if that email actually sent...I have not received it.

Black background is a possibility but we then want to use "vacuum" instead of "air" as the label. We will also want to think about the color mapping of the background as it goes to water and glass. We could go from a very light gray to blue.

**Comment by samreid** [comment]
> @samreid - you may want to see if that email actually sent...I have not received it.

According to my email client, it was sent at 2:49pm to your colorado dot edu address.  I'd be interested to hear if others received it or not, or if you receive it later on.

> Black background is a possibility but we then want to use "vacuum" instead of "air" as the label. 

Should we also change the index of refraction accordingly, or do you think it would be so close that it wouldn't make a difference?

**Comment by ariel-phet** [comment]
@samreid air is n=1.000293 (pretty darn close) and we almost always assume n=1 for air. Not sure if we should make that label change, it was just a thought.

**Comment by ariel-phet** [comment]
@samreid btw - I sent myself a test email and it did not work...maybe something about colorado.edu is messed up at the moment

**Comment by jonathanolson** [comment]
I did get the email sent, and the descriptions are accurate.

> Another issue this will solve is that it will take an additional step to match the prism color to the background color when their indexes of refraction are the same, but @jonathanolson said he wasn't too worried about that part.

I thought about this a bit more, and it depends exactly on the desired look. If the "outside" is filled with glass, and the "prism" is filled with air/vacuum, we'd presumably want inside the "prism" to be darker (black) than the "outside"? It might require some experiments with blending modes. But you also want the prism draggable in FRONT of the control panels? I'd change my opinion to "slightly" worried about exactly how that would be done.

**Comment by samreid** [comment]
The prisms are only supposed to go in front of the south control panel, so that you can drag a prism in front of its own toolbox to put it away.

**Comment by jonathanolson** [comment]
> The prisms are only supposed to go in front of the south control panel, so that you can drag a prism in front of its own toolbox to put it away.

Understood. It's important, because otherwise we could get away with drawing (in order into a single Canvas):
1. Background medium color
2. Prism medium colors
3. Light rays

This would allow us an easy way to handle setting the medium colors exactly, but the control panel needs to be between 1 and 2 AND after 3! Although, I guess we could render that panel in Canvas, and have other layers each be in their own CanvasNode. It gets tricky.

**Comment by samreid** [comment]
We may need to swap the navbar colors if white light is set to on?  Or at least give it an outline.

**Comment by samreid** [comment]
Summarizing outstanding work from above:

(1) Black background is a possibility but we then want to use "vacuum" instead of "air" as the label. 
  -  air is n=1.000293 (pretty darn close) and we almost always assume n=1 for air. Not sure if we should make that label change, it was just a thought.

I think we discussed that it could be confusing to change the medium when changing the light type, so perhaps we should leave this as-is.

(2) We may need to swap the navbar colors if white light is set to on? Or at least give it an outline.

(3) We will also want to think about the color mapping of the background as it goes to water and glass. We could go from a very light gray to blue.

(4) Make sure the prism/light layering order is good.

**Comment by samreid** [comment]
We have consensus that we are going to continue with black background for white light, I moved the outstanding work to the issues mentioned above, closing.
