### ISSUE TITLE
Reduce the size of the velocity sensor in the toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#193]
so that it matches the size of the intensity sensor and time graph sensor.

**Comment by samreid** [comment]
Here is a list of all of the features we need from these toolbox items:

1. The layout in the toolbox is correct, and easy to resize/reposition
2. When dragging out of the toolbox, a tool should animate to full size and drag as a unit (all items drag together) and should drag by the "hot spot"
3. When dragging in the play area, it can be dragged by any component
4. When any component is dropped into the toolbox, the entire tool animates back to the toolbox, into the correct positioning
5. The toolboxes can move around.
6. When dragging out of the toolbox or in the play area, it should be constrained to be within bounds and the cursor shouldn't get away from the component.

**Comment by samreid** [comment]
(7) The exact model coordinates and shapes are critically important.

**Comment by samreid** [comment]
For the initial layout within the toolbox, a VBox would be perfect, but I don't think we can use a VBox if the children are going to be added/removed.

Some implementations have used different nodes for the toolbox icon and for the movable object, but then you have to forward events from one to the other and they can get out of sync.

**Comment by samreid** [comment]
By the way, this is a recurring problem that comes up in a wide variety of simulations.  We normally just code custom solutions each time, but having a pattern that works in multiple simulations would be great.  A general solution should also work with items dragged out of a carousel.  I can see this strategy being used in CCK Basics, Function Builder, Balancing Act, Build a Molecule, etc.

@pixelzoom can you comment on how you typically deal with this feature set, and if you envision a common-code solution that can address the above issues uniformly and generally?

**Comment by pixelzoom** [comment]
I have not yet had to implement a toolbox or carousel, so no recommendations at the moment. I'm sure I'll have some opinions after https://github.com/phetsims/sun/issues/166.

**Comment by pixelzoom** [comment]
@samreid you said:
> By the way, this is a recurring problem that comes up in a wide variety of simulations. We normally just code custom solutions each time, but having a pattern that works in multiple simulations would be great. 

Would be useful to identify the various implementations, and compare/contrast? Or maybe that's too big a job, and we just need to identify one good pattern and commonize it?

**Comment by samreid** [comment]
I looked through the active-runnables to see what kind of drag/drop UI components we have:

acid-base-solutions: none
area-builder: **buckets** **toolboxes** **carousel**
arithmetic: none
atomic-interactions: none
balancing-act: **carousel** **objects get smaller when dragged**
balancing-chemical-equations: none
balloons-and-static-electricity: none
beaker: none
beers-law-lab: none
bending-light: **toolboxes**
blackbody-spectrum: none
blast: none
build-a-molecule: **buckets in carousels**
build-an-atom; **buckets with custom layout**
calculus-grapher: none
capacitor-lab-basics: none
chains: none
charges-and-fields: toolbox
color-vision: none
concentration: none
curve-fitting: **bucket, items get error bars when dragged**
energy-forms-and-changes
energy-skate-park-basics: **toolbox**
estimation: none
example-sim: none
faradays-law: none
fluid-pressure-and-flow: **toolbox** for sensors
forces-and-motion-basics **toolbox** pullers and items
fraction-comparison: none
fraction-matcher: **toolbox**
friction: none
function-builder: **carousel**
gene-expression-basics: **toolbox**
graphing-lines: none
graphing-quadratics: none
gravity-and-orbits: none
gravity-force-lab: none
griddle: none
hookes-law: none
isotopes-and-atomic-mass: **buckets**
john-travoltage: none
joist: none
least-squares-regression: **buckets**
making-tens: **toolbox**
molarity: none
molecule-polarity: none
molecule-shapes: pseudo-toolbox (items animate only)
molecule-shapes-basics: pseudo-toolbox (items animate only)
molecules-and-light: none
neuron: none
ohms-law: none
optics-lab: **toolbox**
pendulum-lab: none
ph-scale: none
ph-scale-basics: none
plinko-probability: none
projectile-motion: <not in html5 yet>
protein-synthesis: **toolbox w/stacks**
reactants-products-and-leftovers: none
resistance-in-a-wire: none
rutherford-scattering: none
scenery-phet: none
seasons: **toolbox**
simula-rasa: none
states-of-matter: none
states-of-matter-basics: none
sugar-and-salt-solutions: **toolbox with multiprobe**
sun: none
trig-tour: none
under-pressure: **toolbox**
vegas: none
vibe: none
wave-on-a-string: none

I may have missed something.

**Comment by samreid** [comment]
I'm going to move some of these thoughts over to scenery-phet.  I wonder how these sort of drag & drop capabilities will overlap with accessibility.

**Comment by samreid** [comment]
This work should be done after https://github.com/phetsims/scenery-phet/issues/186

**Comment by samreid** [comment]
The work about generalizing listeners and toolbox layout is now elsewhere, this particular issue is resolved in the commits above, closing.
