### ISSUE TITLE
Tone down the brightness of the highlight on the velocity sensor

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#194]
It is a bit abrupt, perhaps move the gradient a bit to the left.

**Comment by samreid** [comment]
I fixed the gradients in the above commit, made the light highlight from the top to be consistent with the rest of the lighting in the sim, and toned it down.  Now it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/9807467/ee3615a8-5810-11e5-997d-c2d78d4d5179.png)

@arouinfar @ariel-phet does that look OK to you?  Let me know if I should publish a dev version for you to see it in context.

**Comment by arouinfar** [comment]
No need to publish a new dev version. I think it looks good @samreid! Thanks.

**Comment by samreid** [comment]
Thanks for checking it out, I'll close the issue.
