### ISSUE TITLE
The ProtractorModel.position and ProtractorNode.translation are used inconsistently

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#196]
Some places translate the model, some places translate the view and ignore the model values.  We should pick one and stick with it.  Since the model location is never critical, perhaps view coordinates would be best.  On the other hand, if we ever want the protractor to "snap to" the origin, then model coordinates may be best here.  Also, model coordinates may be best for consistency with other tools, which require model coordinates.  Discovered during #171

**Comment by samreid** [comment]
I'd like to hear @pixelzoom thoughts on #193, particularly regarding whether dragging should be done in view coordinates (and update the model accordingly) or dragging should be done in model coordinates (and view updated accordingly).

**Comment by pixelzoom** [comment]
If this were a common-code component, here's the pattern that I would typically use:

```js
function ProtractorNode( locationProperty, ..., options ) {

   var thisNode = this;
   Node.call( this );

   options = _.extend( {
      modelViewTransform: ModelViewTransform2.createIdentity(),
      ...
   }, options );

  locationProperty.link( function( location ) {
    var viewLocation = options.modelViewTransform.modelToViewPosition( location );
    // ... then use viewLocation to position the node
  } );
 
  addInputListener( new SimpleDragHandler( {

      clickOffset: 0,
      clickYOffset: 0,

      start: function( event ) {
        var parentPoint = thisNode.globalToParentPoint( e.pointer.point );
        this.clickXOffset = parentPoint.x - e.currentTarget.x;
        this.clickYOffset = parentPoint.y - e.currentTarget.y;
      },

      drag: function( event ) {
           var parentPoint = thisNode.globalToParentPoint( event.pointer.point );
           var x = parentPoint.x - this.clickXOffset
           var y = parentPoint.y - this.clickYOffset
           locationProperty.set( options.modelViewTransform.viewToModelXY( x, y );
      }
  } );

  ...
  this.mutate( options );
}
```

This leaves it up to the client to decide whether locationProperty is in model or view coordinates, and whether a transform is needed.   If you're concerned about performance of using an identify transform, then options.modelViewTransform could default to null, and you could handle that accordingly elsewhere in the code (but obviously makes the implementation more complicated).

Within a sim, I think it's important to handle the coordinate frame mapping consistently.

Does that answer the question?

**Comment by samreid** [comment]
Thanks for your thoughts @pixelzoom.

Perhaps it would be best for me to make good progress on https://github.com/phetsims/scenery-phet/issues/186 before working on this.

**Comment by samreid** [comment]
The new implementation just drags the protractor node, closing.
