### ISSUE TITLE
Use Ray2 instead of tail+direction

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#197]
In many of the rays and logic, there is a tail + direction,  @jonathanolson suggested things would be simpler if we just use dot.Ray2 in those places.

**Comment by samreid** [comment]
LightRay.js uses tail & tip (it is important where the ray terminates).  In Laser.js it makes sense (to me) to track the emission point separately from the laser angle, since often one will change without the other changing.

PrismsModel.propagate and Ray() have tail+directionUnitVector.  I don't see any other places with this issue.

**Comment by samreid** [comment]
To avoid name collision, I think I should rename Ray to ColoredRay.

**Comment by samreid** [comment]
Even the simplest step of putting position & direction into a Ray2 in ColoredRay is yielding a negative radicand `cosTheta2Radicand` and hence NaNs.

**Comment by samreid** [comment]
Putting a console.log in ColoredRay like so

```js
console.log( directionUnitVector.magnitude() );
``` 
reveals a NaN when there is an internal reflection.

**Comment by samreid** [comment]
Fixed above, it was failed handling for the case of total internal reflection.

**Comment by samreid** [comment]
Fixed above, @jonathanolson can you take a look and let me know if you have any other recommendations here?

**Comment by jonathanolson** [comment]
Looks good, thanks!
