### ISSUE TITLE
Pass additional properties to the super call

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#198]
In PrismsModel.js, for example, there are many calls to `addProperty` in the subclass.  @jonathanolson suggested that it would be better to pass this group of options to the parent class BendingLightModel and create them when the PropertySet.call is made.  There are probably other places we can apply this pattern as well.

**Comment by samreid** [comment]
Fixed above, the 2 remaining .addProperty calls look warranted.  @jonathanolson thanks for the suggestion--can you review the work above and let me know if you have further recommendations?

**Comment by jonathanolson** [comment]
Looks good, thanks!
