### ISSUE TITLE
Wave view of light does not run properly

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#2]
On the intro tab, click the wave view of light and access the intensity meter. Notice that every time you move the intensity meter, the wave of light will not render properly.

**Comment by samreid** [comment]
Can you please provide a screenshot?

**Comment by bryo5363** [comment]
![bendinglight1](https://cloud.githubusercontent.com/assets/7717368/5618741/15d61cda-94d9-11e4-8ef4-b09939a7c182.gif)

**Comment by phet-steele** [comment]
I do remember seeing this in the past, and I no longer do in 1.0.0-dev.3. Closing.
