### ISSUE TITLE
Generalize the laser

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#203]
See #151

**Comment by samreid** [comment]
From #151:

> We noticed that Beer's law lab uses the laser node

Here is the image from Beers Law Lab:
![light](https://cloud.githubusercontent.com/assets/679486/9829637/0db8cfb0-58ca-11e5-95e1-11223a53373d.png)

Here is the image from Bending Light
![laser](https://cloud.githubusercontent.com/assets/679486/9829640/275e6df8-58ca-11e5-9507-b966dc3b054a.png)

Reassigning to @pixelzoom to discuss whether we should consolidate these images, and, if so, how.

**Comment by pixelzoom** [comment]
@samreid Any reason why you aren't suggesting that we include the button on the laser?  Like so:

![screenshot_618](https://cloud.githubusercontent.com/assets/3046552/9854783/cd4cc85a-5ac7-11e5-90cd-8f2a8f9b701a.png)

**Comment by pixelzoom** [comment]
bending-light has this additional variant.  What is its purpose? Should this be an options? Why or why not?

![laser_knob](https://cloud.githubusercontent.com/assets/3046552/9854863/4095ceec-5ac8-11e5-9870-cc850af97a86.png)

**Comment by pixelzoom** [comment]
My recommendation... 

If the design team says that this is a common component that we're going to use moving forward, then spend the time to generalize it, preferably with the button (with an option to make the button momentary or toggle).  Don't know about the "knob" variant above. 

If there's no consensus that we'll be reusing this heavily, then don't bother generalizing. There are 2 cases where this occurs, they are fairly simple, and the payback would be low.

**Comment by samreid** [comment]
Maybe button should be optional?  I can think of cases where the laser is always on, or controlled through some other UI control.

The knob on the back is used to rotate the laser.

I'll reassign to @ariel-phet to discuss your points about whether this will be a common component used going forward.

**Comment by ariel-phet** [comment]
There is a good chance we will have a laser in CCK Basics, although it may also have a different appearance (since it will need to look a bit more powerful than a laser pointer).

I am fine if we want to hold off on generalizing this component until another case comes up. Considering we will be making math sims for quite sometime, it is unlikely to be needed any time soon.

I will close for the moment.
