### ISSUE TITLE
Is the white light canvas performance good enough?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#215]
@ariel-phet said he will test on iPad2 and report back.

**Comment by arouinfar** [comment]
Testing with dev.29 on an iPad2, the performance seems ok. With one or two prisms in the playspace, the performance was pretty snappy. With 3-5 prisms in the playspace, the performance was a bit sluggish. The prisms would lag a little when dragged and rotated, and the frame rate dipped down to about 12 fps. It was still usable, but noticeably slower. If there is some low hanging fruit in terms of optimization, it's probably worth doing.

**Comment by samreid** [comment]
The next step that would make a significant performance improvement would be to move to a WebGL renderer for white light, which would take somewhere between 10-30 hours to get started, and probably longer to fine-tune and optimize, with assistance from @jonathanolson.  @ariel-phet and @arouinfar are probably best poised to decide if we are going to invest in this before publication.

**Comment by ariel-phet** [comment]
I think we are going to call that good. Performance in general already seems significantly better than the java version. Considering how popular this sim is in java, and applying the "80-20" rule, I think by far the majority of learning goals can be reached with a few optical elements. 3-5 elements is getting to some fairly exotic territory in terms of learning goals and the types of uses I have had in class. 

We also probably do not have the luxury of time to spend on a webgl implementation. Perhaps we should make an enhancement issue called "Try Webgl" or such and leave it as an open issue for the next time we revisit the sim.

**Comment by arouinfar** [comment]
The only performance issues I noticed were with white light and multiple prisms. Even then, it's not unusable, just a little slow. The rest of this sim is running really smoothly on iPad2.
