### ISSUE TITLE
New mapping for colors for white light

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#216]
Air = black, glass = dark gray

**Comment by samreid** [comment]
From https://github.com/phetsims/bending-light/issues/190 @samreid said 

> (3) We will also want to think about the color mapping of the background as it goes to water and glass. We could go from a very light gray to blue.

But I think:

> Air = black, glass = dark gray

was the consensus at a design meeting.

**Comment by samreid** [comment]
I changed the color scheme above and published a dev version for testing.  @kathy-phet @arouinfar @ariel-phet please take it for a test drive at your convenience:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.31/bending-light_en.html

One issue I noticed is that the transparency of the prisms makes it look like changing the environment medium also changes the prism medium.  Please take a look and advise.

**Comment by arouinfar** [comment]
@samreid I think the new color mapping for white light looks great. I was interviewing on Capacitor Lab: Basics last week and I had a little time to have students take a look at Bending Light as well. They didn't have much time to play with the sim, but from my observations the new color mapping did not cause any problems with interpretation. Neither student noticed the transparency of the prisms, however. 

That being said, the more I play with the sim, the more I prefer the opaque prisms. Comparing an air prism in a glass environment in dev.34 (left) and dev.14 (right), I find the transparency to be a bit problematic. The prism in dev.14 is clearly air, but the prism in dev.34 could be perceived as being a near-glass material.
![image](https://cloud.githubusercontent.com/assets/8419308/10670669/c9424f7e-78a3-11e5-84c1-b1ece7383952.png) ![image](https://cloud.githubusercontent.com/assets/8419308/10670680/dae29ed2-78a3-11e5-9577-5301e016effa.png)

Can we keep the new color mapping, but ditch the transparency?

**Comment by samreid** [comment]
Getting rid of the transparency will be difficult.  For the white light mode, the light rays and black background must be drawn on a single canvas.  The prisms are currently rendered in SVG, in front of this canvas.  If they were made opaque, then no light would shine through them and it would look like this:

![image](https://cloud.githubusercontent.com/assets/679486/10685714/5b2ce266-791a-11e5-8ea3-115152171f70.png)

The prisms cannot be moved into the canvas layer between the light and the black background because they would interfere with the white light summation algorithm.  And I recommend we use the same strategy for white light and monochromatic light for simplicity and uniformity.

One alternative would be to increase (but not maximize) their opacity.  The current value is 0.3 and is shown in the above comment for red light.  Here is the same situation (air prism in glass environment) with alpha = 0.5
![image](https://cloud.githubusercontent.com/assets/679486/10685775/31d6c1ce-791b-11e5-88a7-616c1abfa8e4.png)

![image](https://cloud.githubusercontent.com/assets/679486/10685777/3bd0aeba-791b-11e5-9925-d25fe8bb0d59.png)

Does this seem like a good compromise?  I can also try other alpha values if you like.

**Comment by arouinfar** [comment]
Thanks for the explanation @samreid. I hadn't realized the potential complications. Increasing the opacity to 0.5 seems like a good compromise, and I think it will help make the perceived color change of the prism less dramatic. It looks much better in your screenshots. 

Reassigning to @samreid to increase the alpha value to 0.5.

**Comment by samreid** [comment]
I increased the prism alpha to 0.5 in the above commit.  Closing since I don't see any other items in this issue (but @arouinfar please reopen if I've forgotten something.)
