### ISSUE TITLE
Normals should be black on white background and vice versa

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#217]
Check on the phet-io logo for the perfect shade of gray that works against white/black.  Do this for all screens.

**Comment by samreid** [comment]
The phet-io gray is #999999, in my opinion very faint and difficult to see:

This scene shows the defaults for More Tools:
![image](https://cloud.githubusercontent.com/assets/679486/10056321/d8a8ce9c-61f7-11e5-8cdb-a40cf561f15b.png)

How about black normals when background is white and vice versa?

**Comment by arouinfar** [comment]
I agree, it's a bit hard to see. Let's try the solution you've proposed, @samreid.

**Comment by samreid** [comment]
This looks good to me, I'll commit shortly:
![image](https://cloud.githubusercontent.com/assets/679486/10056647/4487e53e-61f9-11e5-8cc7-7ab23ae208ef.png)

**Comment by samreid** [comment]
Committed above.  But now I think we need a cleanup function to dispose of the listeners attached in IntersectionNode.

**Comment by samreid** [comment]
Leak fixed, closing.
