### ISSUE TITLE
White light rendering broken on Win/Chrome

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#219]
![image](https://cloud.githubusercontent.com/assets/679486/9670254/e0a8dd12-5248-11e5-86f4-74390b806e33.png)

From @kathy-phet machine.

**Comment by samreid** [comment]
No such issue on my Lenovo Windows 8 Running Chrome 45.0.2454.99 (m) 64-bit when testing the dev version http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.31/bending-light_en.html

I'll update my Chrome to latest and try once again.

**Comment by samreid** [comment]
Updated to 45.0.2454.101 m 64-bit and still no issues.

The next steps we should take here:

1. Figure out @kathy-phet's Chrome version
2. See if @kathy-phet has any Chrome updates available, and see if that fixes the problem
3. See if the problem is still exhibited on @kathy-phet's machine with the latest dev version (dev.31 linked above)

**Comment by samreid** [comment]
I emailed @kathy-phet:

Kathy,

I need your help to investigate the broken white light rendering we saw on your machine.  Can you paste me your Chrome version (from the chrome about dialog), see if you have updates (and if the updates fix the problem), and see if the issue is still a problem in this dev version?
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.31/bending-light_en.html

Context:
https://github.com/phetsims/bending-light/issues/219

Thanks,
Sam

**Comment by samreid** [comment]
@kathy-phet reported it is still a problem:

>  Hi Sam,

> It's still a problem. Version is below. It says it is up to date.

> Version 45.0.2454.101 m

> Good luck with this!
> Kathy 

![image](https://cloud.githubusercontent.com/assets/679486/10198506/97bdabac-6759-11e5-9737-5791fc07904f.png)

**Comment by samreid** [comment]
Grasping at straws, I noticed that @kathy-phet version was `Version 45.0.2454.101 m` and @samreid version was `45.0.2454.101 m 64-bit`.  I wonder if I can get a 32-bit version and see if I have that problem?

**Comment by samreid** [comment]
I downloaded the 32-bit version of Chrome Version 45.0.2454.101 m on my Lenovo and it renders without problems.

@ariel-phet I recommend to have testers launch http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.31/bending-light_en.html on Win/Chrome and see if they see the problem that @kathy-phet saw.  Shall I create a tasks issue?

**Comment by ariel-phet** [comment]
@phet-steele do you have a moment to check this?

**Comment by phet-steele** [comment]
Yep

**Comment by phet-steele** [comment]
All looks good on my end, is @kathy-phet machine also 32-bit? Or 64-bit?

**Comment by samreid** [comment]
@phet-steele how many machines did you test?  Were they all Windows 8?  What kind of systems were they (HP/Lenovo/etc?)

**Comment by kathy-phet** [comment]
64 bit. 

Should I look to see if there are display updates for my computer?

**Comment by samreid** [comment]
I tested on my HP HDX 16t laptop running Window 8,  No problems in Chrome 45.0.2454.93 m and also no problems on Chrome 45.0.2454.101 m.

> Should I look to see if there are display updates for my computer?

That's a good suggestion, can you give it a try @kathy-phet ?

**Comment by phet-steele** [comment]
I just did a real quick test on Win 8.1 Lenovo, in maybe 20 minutes I might be able to try a Win 7 machine.

**Comment by samreid** [comment]
Brainstorming (in case display updates for @kathy-phet don't help): we could try having @kathy-phet run the 64-bit version of chrome and see if that changes anything (though 64/32 bit may be a red herring, it would be good to rule it out).

**Comment by kathy-phet** [comment]
I tried it on firefox, and do not see this issue. Although I do see that it is much slower response.

**Comment by kathy-phet** [comment]
Tried 64-bit chrome version, and no change: 
![image](https://cloud.githubusercontent.com/assets/5096804/10199895/79c42480-6760-11e5-960e-f06d2907e408.png)

**Comment by samreid** [comment]
Thanks for ruling that out @kathy-phet, let me know if you see any graphics driver updates.

**Comment by phet-steele** [comment]
Still no problems on a Win 7 64-bit machine. It's custom built (Nvidia GTX 770 4GB, i5 3570k, Z77A-G45 MSI, 8GB RAM)

**Comment by samreid** [comment]
Thanks @phet-steele, it looks like the next step will be to see if @kathy-phet has any graphics driver updates.

**Comment by samreid** [comment]
I was seeing similar issues for monochromatic light on @jbphet machine yesterday.  @jbphet are you available to help look into this?  It is one of the only known blocking issues to Bending Light publication.

**Comment by samreid** [comment]
Thanks to @jbphet we were able to identify the problem and a potential solution, and luckily the problem is easily reproducible on @jbphet's Lenovo machine.  The problem is that Chrome introduces rendering artifacts when the geometry is too large, and we saw that some pixels were attempted to be drawn outside of (10000000,10000000) or so.  We also saw a rendering artifact issue like this for the wave view in another issue.

I pushed a fix above that reduced the length of light rays by 2E-4, @jbphet can you please pull and test it at your convenience?

**Comment by samreid** [comment]
@kathy-phet please keep your current graphics drivers so that you will be able to test this solution as well.

**Comment by samreid** [comment]
@jbphet tested this on his machine and it looks perfect.  It seems likely to fix it for @kathy-phet machine too, I'll close the issue and if anyone sees this symptom again, please reopen the issue.
