### ISSUE TITLE
Performance optimizations for single ray webgl

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#220]
Sqrt is repeated many times.  Don't create new arrays each time.

**Comment by samreid** [comment]
> Don't create new arrays each time.

I presume this is referring to the `new Float32Array` in:
```js
      gl.bindBuffer( gl.ARRAY_BUFFER, drawable.vertexBuffer );
      gl.bufferData( gl.ARRAY_BUFFER, new Float32Array( points ), gl.STATIC_DRAW );

      gl.bindBuffer( gl.ARRAY_BUFFER, drawable.colorBuffer );
      gl.bufferData( gl.ARRAY_BUFFER, new Float32Array( colors ), gl.STATIC_DRAW );
```

@jonathanolson can you describe how to implement this without reallocating those arrays each frame?  What if the number of points or colors have increased?

**Comment by samreid** [comment]
This is on hold until @arouinfar reports back on https://github.com/phetsims/bending-light/issues/234 .  @arouinfar can you reassign this issue back to me after looking into https://github.com/phetsims/bending-light/issues/234 ?

**Comment by arouinfar** [comment]
Performance looked great in #234. I don't think we need to move forward with a WebGL implementation for monochromatic light.
