### ISSUE TITLE
the tool box generally needs a bit of negative space padding

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#222]
In #174, @ariel-phet suggested:

> the tool box generally needs a bit of negative space padding (but I am sure you are already aware of that and just working on functionality first).

**Comment by samreid** [comment]
With working copy changes, here's how it currently looks for the intro screen:
![image](https://cloud.githubusercontent.com/assets/679486/10100044/334da976-634c-11e5-997b-78983412d0d9.png)

and by default on the More Tools screen:
![image](https://cloud.githubusercontent.com/assets/679486/10100089/864a03f4-634c-11e5-85af-4809d932ea5e.png)

And here it Intro with ?stringTest=double:
![image](https://cloud.githubusercontent.com/assets/679486/10100122/b898cd0e-634c-11e5-88da-63c6e00a6a00.png)

And MoreTools with ?stringTest=double:
![image](https://cloud.githubusercontent.com/assets/679486/10100166/d423469e-634c-11e5-8050-9ddc990315a3.png)

I showed the laser in the last case since it will constrain how much we can grow the toolbox in the x-direction before the laser becomes too crowded.

@ariel-phet can you look at these pictures and make a recommendation for changes, if any?

**Comment by ariel-phet** [comment]
@samreid, in the usual cases things look good. With stringTest=double, it would be nice if the check boxes did not got mashed to the side. I would grow the tool box a bit to the right (maybe 10-15 percent) to maintain a decent layout for checkboxes and icons, and then after that scale fonts down if strings grow longer.

**Comment by samreid** [comment]
Trying the simplest thing first, if I just change the default width from 100 to 120, then everything looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/10107550/1e38b364-6379-11e5-9cc6-6de1fbe02739.png)

![image](https://cloud.githubusercontent.com/assets/679486/10107555/2b75bb94-6379-11e5-8e10-d4649d54484d.png)

![image](https://cloud.githubusercontent.com/assets/679486/10107559/39e72406-6379-11e5-96e3-5481eefdfa43.png)

![image](https://cloud.githubusercontent.com/assets/679486/10107572/45bc44a0-6379-11e5-96a8-ffe05e55b6a3.png)

Is this good enough?  Resizing the toolbox based on the contents of the subclass is a bit more complex and not sure if it will look too much better.

**Comment by ariel-phet** [comment]
I might need to see it in full context. If I pull will this be latest version?

**Comment by samreid** [comment]
I have some breaking changes in my working copy, but I think (90% sure?) that what is checked in is runnable.  Try your luck :four_leaf_clover:

**Comment by ariel-phet** [comment]
So after looking at this some more, I think a better solution would be to have the check boxes not in the panel, that way the toolbox can be well sized to the tools, and the words can just grow as necessary to the right without influencing the panel. I think it will be a cleaner design overall. So reduce the panel width so there is still some padding, and shrink the panel vertically so that it does not include the check boxes. Left align the checkboxes to the left side of the control panel.

**Comment by samreid** [comment]
This looks excellent, nice thinking outside the box @ariel-phet 

![image](https://cloud.githubusercontent.com/assets/679486/10111326/7efb580c-6390-11e5-9bfa-d0deefd70e59.png)

**Comment by samreid** [comment]
A bit of crowding with the time controls, I think I'll just move them to the side a bit and make sure they have an equivalent bottom padding:

![image](https://cloud.githubusercontent.com/assets/679486/10111390/ec02e97e-6390-11e5-8663-8af74297c12c.png)

**Comment by samreid** [comment]
Bottom padding will be addressed in #235. @ariel-phet can you pull and look at the current version with respect to the toolbox/checkboxes?  Or let me know if you'd like a dev version.

**Comment by arouinfar** [comment]
Moving the checkboxes out of the toolbox looks good to me!

**Comment by ariel-phet** [comment]
Hey @samreid - looking good, we may want to tweak placement of toolboxes slightly, but I think that will best be done in person. I think this issue for the padding can be closed, nice work!
