### ISSUE TITLE
Navigation bar disappears into black background

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#224]
We need to either (a) change the navbar color when changing the light color or (b) add an outline.  We should try (a) first.

See https://github.com/phetsims/bending-light/issues/190

**Comment by samreid** [comment]
@pixelzoom I'd like to change the color of the navbar based on the settings within the sim (when the background of the sim turns black, the navbar should turn white).  Can you recommend a way for the sim to communicate with the navbar color?

**Comment by pixelzoom** [comment]
Is there an example where I can see where this would be used?  My first inclination is to ask if this is really necessary.  It seems like it could be potentially distracting, and might be addressed in other ways (e.g. a divider between play area and navbar).  Also highly related to https://github.com/phetsims/joist/issues/222.

**Comment by samreid** [comment]
> Is there an example where I can see where this would be used?

Launch Bending Light, go to the 2nd screen and select the "white light" radio button.  The background will turn black and the navbar will remain black, so it will look like so:

![image](https://cloud.githubusercontent.com/assets/679486/9860634/a965af92-5aea-11e5-9dbc-070b3425baa1.png)

After seeing this in practice, however, I am not too concerned about the problem.  The toolbox and screen icons define a very clear (though implicit) line that may be sufficient.  @ariel-phet @arouinfar @pixelzoom thoughts?

**Comment by arouinfar** [comment]
I'm not bothered by the black navbar in this situation. For clarity, we could add a thin gray line (white would be too bright) to separate the navbar from the playspace, but I'm not sure that it's necessary. Any thoughts, @ariel-phet?

**Comment by ariel-phet** [comment]
I think I would go for the thin gray line for separation if possible.

**Comment by pixelzoom** [comment]
There is currently no support too "the thin gray line".  Adding it likely more trouble than adding the ability to change the color of the navbar, since it involves adding something new to the framework (as opposed to changing something that already exists.)

**Comment by pixelzoom** [comment]
Rather than adding a line, how about adding a stroke around the existing navbar? The stoke would appear around all edges of the navbar.  Hmmm... Not sure if I like that either.  Let's think about this carefully and discuss in dev meeting before proceeding.

**Comment by ariel-phet** [comment]
@pixelzoom why can't a thin gray line be drawn at the bottom of the dev bounds in this case? It does not have to be in Joist, it can be in the play area?

**Comment by ariel-phet** [comment]
Correct me if I am wrong, but we have support for drawing arbitrary lines of any color/stroke width within the sim? And could even float this line to the bottom?

**Comment by pixelzoom** [comment]
> Correct me if I am wrong, but we have support for drawing arbitrary lines of any color/stroke width within the sim? And could even float this line to the bottom?

Indeed.  But we have no such line currently in the framework, no API to specify when it's visible, what it's properties are (stoke, lineWidth), when/if it "floats to the bottom", how we deal with it in "projector mode", (or the as-yet-unfinished "color scheme" feature), etc.  Adding a line may seem like a quick fix, but it should be added as thoughtfully as any other UI component.

**Comment by samreid** [comment]
To summarize thoughts so far:

@samreid and @arouinfar said black on black is OK
@ariel-phet suggested to try a thin gray line "if possible"
@pixelzoom offered suggestions about how this can be implemented.

I think I'll move this to `developer-meeting` so the developers can discuss the best way to implement this and how much complexity it would add to the simulation/framework.

**Comment by ariel-phet** [comment]
just to add - although black on black *might* be OK...we have some well established conventions now, and they have been proven out in interviews and such, so I would prefer not to mess with them if possible and keep the nav bar as a distinct element.

**Comment by samreid** [comment]
@pixelzoom what about accessing the navbar statically, something like:
```js
phet.joist.sim.navigationBar.background = 'white';
```

**Comment by pixelzoom** [comment]
> what about accessing the navbar statically, something like

Hard to say... We're eventually supposed to be working on a "color scheme" feature, and cleaning up the "color inversion" stuff.   My initial reaction is that if we need to resort to attaching it to sim (or worse yet, a global), then we shouldn't do it.

**Comment by pixelzoom** [comment]
@ariel-phet is suggesting adding this "line line" is sim-specific code, just for this sim.  The ScreenView would need to take care of it.

**Comment by samreid** [comment]
Fixed above, @ariel-phet took a look and said it looks good.  Closing.

**Comment by arouinfar** [comment]
While looking at the Prisms screen with @ariel-phet, we thought the horizontal gray line was a bit on the heavy side. Can you give it the thinnest possible stroke width that's still visible @samreid?

**Comment by samreid** [comment]
> Can you give it the thinnest possible stroke width that's still visible @samreid?

Generally, that is a tricky question to answer, since it depends on the ppi of the monitor and the size of the window.  But I can thin it out a bit and we can test on a few devices to make sure it didn't go <1px.

**Comment by samreid** [comment]
When I try setting 1px in the code (was previously 2px), the sim exhibits a rapid cyclic pattern of "looking great" --> "looking acceptable" --> "can hardly see it" as I scale the chrome browser window size.

**Comment by samreid** [comment]
You can see this cycling problem even for the latest dev version (dev.31) when the window size gets small enough.  Changing from 2px->1px makes this problem occur at larger window sizes.  @arouinfar or @ariel-phet can you review and advise?

**Comment by arouinfar** [comment]
Thanks for looking into this issue @samreid. Let's keep the line at 2px, given the problems with reducing the stroke weight. Closing.
