### ISSUE TITLE
vRefract is not normalized.

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#226]
Discovered in #197, sometimes the vRefract is not normalized for a total internal reflection (drag trapezoid or triangle through the light).  Here is the code:

```js
        var vRefract = cosTheta1 > 0 ?
                       (L.times( n1 / n2 )).addXY( n.x * ( n1 / n2 * cosTheta1 - cosTheta2 ), n.y * ( n1 / n2 * cosTheta1 - cosTheta2 ) ) :
                       (L.times( n1 / n2 )).addXY( n.x * ( n1 / n2 * cosTheta1 + cosTheta2 ), n.y * ( n1 / n2 * cosTheta1 + cosTheta2 ) );
```

Here is the vector form of snell's law, from https://en.wikipedia.org/wiki/Snell%27s_law#Vector_form

![image](https://cloud.githubusercontent.com/assets/679486/9819736/070966aa-586d-11e5-91bb-140894a2d1ab.png)

**Comment by samreid** [comment]
@jonathanolson do you think the last formula in the wikipedia snapshot above is normalized?  If so, can you help me look for a bug in the implementation that is causing my vectors to come out with magnitude >1.5?

**Comment by jonathanolson** [comment]
I don't see anything necessarily requiring that to be normalized from the above description ("direction vector"). You could see OpenGL's implementation at https://www.opengl.org/sdk/docs/man/html/refract.xhtml to see if it's the same.

**Comment by samreid** [comment]
It seems like this is indeed a direction vector and not normalized.  In the words of:
http://www.cs.rpi.edu/~cutler/classes/advancedgraphics/F05/lectures/13_ray_tracing.pdf

![image](https://cloud.githubusercontent.com/assets/679486/9950334/bc286032-5d76-11e5-8c65-bea470d71901.png)
