### ISSUE TITLE
Put the triangle before the square in the toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#228]
The square is the first (leftmost) item in the toolbox. However, with the default laser angle, it doesn't deflect any light:

![image](https://cloud.githubusercontent.com/assets/679486/9821409/5be4bd1e-5877-11e5-982d-c5edf75e482b.png)

@arouinfar and @ariel-phet what would you think about putting the triangle "first", since it gives a much better first impression?  What would you recommend for the ordering of the rest of the shapes?

**Comment by arouinfar** [comment]
@samreid, that's a great point. I left the ordering of the objects the same as the Java version, but perhaps it is best to swap the triangle and square. I don't have any other suggestions for reordering, but perhaps @ariel-phet does.

**Comment by ariel-phet** [comment]
@samreid and @arouinfar - not shure why that was the original design decision...maybe it was to "discover" that an angle of incidence was necessary? But I agree, the prism first seems more natural. I think a nice order might be 

prism, trapezoid, square, circle, hemisphere, diverging lens

**Comment by arouinfar** [comment]
Sounds good to me @ariel-phet!

**Comment by samreid** [comment]
Fixed as described by @ariel-phet, this seems much more natural, closing.
