### ISSUE TITLE
Speedometer sometimes obscured

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#233]
Speedometer sometimes obscured:
![image](https://cloud.githubusercontent.com/assets/679486/9853864/1c35fbda-5ac3-11e5-8751-1bd3b4bc7616.png)

Discovered in #157

**Comment by samreid** [comment]
@arouinfar and @ariel-phet can you suggest a solution here?

**Comment by arouinfar** [comment]
@samreid, I don't really see a way around this situation. At times, the vector will have to cross the display. Perhaps you could give a slight opacity to the vector to allow the text to be seen.

At 85% opacity, the text is fairly readable behind the vector.
![image](https://cloud.githubusercontent.com/assets/8419308/10112951/caf2448a-639c-11e5-8b23-dfea8f82b22a.png)

I'm not sure how a reduced-opacity vector would look elsewhere in the sim, but perhaps it's worth a shot. Care to chime in, @ariel-phet?

**Comment by ariel-phet** [comment]
That seems like a nice solution to me @arouinfar, especially since the vector is sort of an ethereal object.

**Comment by samreid** [comment]
This is the result with 0.85 transparency in scenery:

![image](https://cloud.githubusercontent.com/assets/679486/10199910/900fb66e-6760-11e5-9621-1b748e408703.png)

Still a bit difficult to read in my opinion, I'll try decreasing it a bit further.

**Comment by samreid** [comment]
0.6 seems much easier to read and still bold enough in the rest of the sim:

![image](https://cloud.githubusercontent.com/assets/679486/10199972/ec591eba-6760-11e5-9c6c-06b0ef1a9941.png)

I'll go with that and @arouinfar and @ariel-phet can review in the next dev version.

**Comment by samreid** [comment]
A wild dev version appeared!
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.32/bending-light_en.html

**Comment by arouinfar** [comment]
I think it looks great @samreid! Closing.

**Comment by phet-steele** [comment]
:+1: for the reference @samreid!

**Comment by samreid** [comment]
Thanks @phet-steele I'm glad we are on the same page :book:
