### ISSUE TITLE
Discrete color jumps for WebGL

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#234]
Discrete color jumps--there are only 4 or 5 shades of colors when dragging the wavelength slides.

Discovered in #157

**Comment by samreid** [comment]
This is only happening for the WebGL implementation--canvas is fine.

**Comment by samreid** [comment]
Since we decided the performance of white light in canvas was good enough, the performance of single colors is probably also fine in canvas--even 5x rays for single color is still many less rays than shown for white light (30).  @arouinfar can you test single color rays on iPad with ?webgl=false and reflections turned on and report if the performance is acceptable?  If so, it would be great to get rid of the added complexity of the webgl renderer for single color rays, and then we wouldn't have to figure out this issue or https://github.com/phetsims/bending-light/issues/220

**Comment by samreid** [comment]
Oops, forgot to give you a testable version:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.30/bending-light_en.html?webgl=false

**Comment by samreid** [comment]
I tested this myself in iPad3 and it seems very speedy indeed, even with WebGL disabled.  Would be great for @arouinfar to confirm on another device.  If it seems slow, please try changing to webgl=true and see if that changes the speed at all (there are other bottlenecks in the sim).

**Comment by arouinfar** [comment]
Canvas performance looks good on the iPad2! I don't think there's any need for a WebGL implementation for monochromatic light. Closing.
