### ISSUE TITLE
Float panels North & South

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#235]
Now that the panels float to the left and right, it seems a bit unbalanced that they don't float north/south as well.

![image](https://cloud.githubusercontent.com/assets/679486/9853999/bf196184-5ac3-11e5-9881-ded57137ae7d.png)

@ariel-phet or @arouinfar what do you think?

Discovered in #157

**Comment by arouinfar** [comment]
I agree, it does feel a little unbalanced. I think adding North/South float would be a great feature. Thanks for the suggestion @samreid!

**Comment by samreid** [comment]
My plan for this issue:

Intro:
1. Laser control panel will float north
2. Toolbox, checkboxes and reset-all button will float south.

Prisms:
1. Prism toolbox and reset all button will float south
2. Environment panel, laser radio buttons and laser wavelength slider will float north

More tools: Same as Intro

**Comment by samreid** [comment]
Panels are now floating as described above, @arouinfar can you take a look and discuss it with me?
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.33/bending-light_en.html

**Comment by arouinfar** [comment]
I think it looks great @samreid! I don't see the need for any changes, so I'll go ahead and close this issue. Thanks!
