### ISSUE TITLE
Reset button initializes protractor at incident point.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#237]
From initial state of sim the refresh button brings the protractor to the incident point for both Intro and More Tools Screen. Possibly related to issue https://github.com/phetsims/bending-light/issues/236

Initial state:
![unnamed-1](https://cloud.githubusercontent.com/assets/5631059/9884983/04868e54-5ba0-11e5-88e2-cf72261e71f5.jpg)
After reset:
![unnamed-2](https://cloud.githubusercontent.com/assets/5631059/9884987/0afcd766-5ba0-11e5-85e8-9b2ac4c246fa.jpg)
After reset (More Tools)
![unnamed-3](https://cloud.githubusercontent.com/assets/5631059/9884993/12e144da-5ba0-11e5-8f4d-f6bdff3f0be4.jpg)

Tested on iOS 9, iPad 2

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.29/bending-light_en.html
Version: 1.0.0-dev.29 2015-09-12 12:34:16 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_0 like Mac OS X) AppleWebKit/601.1.32 (KHTML, like Gecko) Version/8.0 Mobile/13A4254v Safari/600.1.4
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-123)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"1591786f","branch":"master"},"babel":{"sha":"98b4e313","branch":"master"},"bending-light":{"sha":"beb10522","branch":"master"},"brand":{"sha":"f2c42d7b","branch":"master"},"chipper":{"sha":"0d7e23a7","branch":"master"},"dot":{"sha":"dbe2a778","branch":"master"},"joist":{"sha":"7f37e0ce","branch":"master"},"kite":{"sha":"d5b7c07c","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"acbbf59b","branch":"master"},"scenery":{"sha":"45a29d68","branch":"master"},"scenery-phet":{"sha":"526003e4","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"382140f8","branch":"master"}}

**Comment by orejolaphet** [comment]
After testing this issue on OSX 10.10.4 on firefox different screen sizes reveal that all tools are reset to an incorrect position.

Intro Screen
Initial state:
![unnamed](https://cloud.githubusercontent.com/assets/5631059/9885530/dbf7d74c-5ba2-11e5-99ff-a7d3b813588f.png)
After reset:
![unnamed-1](https://cloud.githubusercontent.com/assets/5631059/9885572/0fb41aa0-5ba3-11e5-9f1e-f7a35b3b696c.png)

More Tools Screen
Initial state:
![unnamed-2](https://cloud.githubusercontent.com/assets/5631059/9885577/1736df88-5ba3-11e5-9f1c-16120da1d2f6.png)
After reset:
![unnamed-3](https://cloud.githubusercontent.com/assets/5631059/9885580/1b1892f4-5ba3-11e5-9ba8-bd5df4ae6622.png)

**Comment by samreid** [comment]
Fixed, closing.
