### ISSUE TITLE
Reset button leaves laser ray and wave artifacts.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#238]
Reset button leaves laser ray or wave artifacts. Artifacts disappear when laser is turned on or when laser representation changes (Ray and Wave). Occurs on all screens Intro, Prisms, More Tools.

Edit:
Reset button and turning laser off leaves artifacts.

To reproduce:
Open sim
Move laser
Hit reset

Screen shots of artifacts.
![unnamed](https://cloud.githubusercontent.com/assets/5631059/9885152/f9702894-5ba0-11e5-9bbc-22bf25d5d4dc.jpg)
![unnamed-5](https://cloud.githubusercontent.com/assets/5631059/9885215/3fce65a8-5ba1-11e5-9f22-cfd9ca9608d1.jpg)
![unnamed-6](https://cloud.githubusercontent.com/assets/5631059/9885218/450e681a-5ba1-11e5-912a-c72cd22bb61d.jpg)

Tested on iOS 9, iPad 2

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.29/bending-light_en.html
Version: 1.0.0-dev.29 2015-09-12 12:34:16 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_0 like Mac OS X) AppleWebKit/601.1.32 (KHTML, like Gecko) Version/8.0 Mobile/13A4254v Safari/600.1.4
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-123)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"1591786f","branch":"master"},"babel":{"sha":"98b4e313","branch":"master"},"bending-light":{"sha":"beb10522","branch":"master"},"brand":{"sha":"f2c42d7b","branch":"master"},"chipper":{"sha":"0d7e23a7","branch":"master"},"dot":{"sha":"dbe2a778","branch":"master"},"joist":{"sha":"7f37e0ce","branch":"master"},"kite":{"sha":"d5b7c07c","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"acbbf59b","branch":"master"},"scenery":{"sha":"45a29d68","branch":"master"},"scenery-phet":{"sha":"526003e4","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"382140f8","branch":"master"}}

**Comment by orejolaphet** [comment]
Also occurs on OSX 10.10.4

**Comment by orejolaphet** [comment]
Reflections also remain as artifact.

**Comment by orejolaphet** [comment]
Artifacts remain if laser is turned off. Not exclusively related to reset button.

**Comment by orejolaphet** [comment]
Behavior does not occur with selection of White Light.

**Comment by samreid** [comment]
Fixed in master, closing.
