### ISSUE TITLE
Laser view - Wave mode - Issue2

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#24]
1. Frequently there appears a sharp crest which is unlike the other crests in all the waves - incident wave, reflected wave and refracted wave. 
2. In reflected wave, white and red lines appear occasionally

**Comment by ChandrashekarBemagoni** [comment]
Fixed  here :https://github.com/phetsims/bending-light/commit/c6842e667c58205423f8374e396f99db6e652440  .  Assigning to @kmsravindra for verification
To Test canvas version  : http://localhost:63342/PhetSimulations/bending-light/bending-light_en.html?webgl=false.

**Comment by kmsravindra** [comment]
Closing.
