### ISSUE TITLE
Poor graphics quality for the wave view

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#240]
During #119 @jonathanolson pointed out:

> With WebGL on, the edges of the beam AND laser body are very aliased, and without WebGL, the edges of the refracted beam are very rough and edgy.

With WebGL:
![image](https://cloud.githubusercontent.com/assets/480878/9882596/b5f8875e-5b92-11e5-9b34-ee6362bd14c4.jpg)
Without:
![image](https://cloud.githubusercontent.com/assets/480878/9882603/bf776890-5b92-11e5-9326-59da0509ddf2.jpg)

**Comment by samreid** [comment]
@arouinfar is what you see above "good enough" or should I ask @jonathanolson to brainstorm ideas?

**Comment by arouinfar** [comment]
Testing on an iPad2 in canvas, the wave looks too jagged. I think it would be worthwhile to talk to @jonathanolson about this issue. 

The laser also looks a bit aliased. Is it being drawn in code or is it an image @samreid?

**Comment by samreid** [comment]
I moved the laser question to a new issue.  @arouinfar were you testing with webgl or webgl=false?  Which of the above images looks like it needs effort?

**Comment by samreid** [comment]
This wave is now looking great on iPad3 with or without webgl.  Here is the webgl=false case:

![image](https://cloud.githubusercontent.com/assets/679486/10622401/8edfd2ee-7744-11e5-8b8f-741079512c48.png)

I suspect but am not sure that the geometry changes used to fix the phase problem at the interface also fixed this problem.  In any case, I'm inclined to close the issue, but @arouinfar or others please reopen if you see this problem in a future version.
