### ISSUE TITLE
Reset button does not change laser type on Prisms Screen

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#241]
Seen on all platforms
Testing 1.0.0-dev.29

On the Prisms Screen, with either White Light or One Color (5x) selected the reset button does not change what is displayed as selected, but the behavior is that of One Color.

For an example the background of the Screen is black when White Light is selected.
<img width="295" alt="screen shot 2015-09-15 at 12 59 45 pm" src="https://cloud.githubusercontent.com/assets/5631059/9886856/b9da9026-5ba9-11e5-9e6f-8658ff03186a.png">
After the reset button the sim returns to the behavior of One Light, but displays White Light as selected. Notice the background as returned to the default white.
<img width="283" alt="screen shot 2015-09-15 at 12 57 32 pm" src="https://cloud.githubusercontent.com/assets/5631059/9886874/cda94f20-5ba9-11e5-9452-824224a6c72d.png">

Same behavior occurs when One Light (5x) is selected.

**Comment by samreid** [comment]
Fixed above, closing.
