### ISSUE TITLE
Time tool does not display anything

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#242]
Tested on OSX FF 37.01 and Chrome 42
Testing 1.0.0-dev.29

On the More Tools Screen the Time tool does not display anything when placed on light wave.

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.29/bending-light_en.html
Version: 1.0.0-dev.29 2015-09-12 12:34:16 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0
Language: en-US
Window: 1260x1235
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 16 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"1591786f","branch":"master"},"babel":{"sha":"98b4e313","branch":"master"},"bending-light":{"sha":"beb10522","branch":"master"},"brand":{"sha":"f2c42d7b","branch":"master"},"chipper":{"sha":"0d7e23a7","branch":"master"},"dot":{"sha":"dbe2a778","branch":"master"},"joist":{"sha":"7f37e0ce","branch":"master"},"kite":{"sha":"d5b7c07c","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"acbbf59b","branch":"master"},"scenery":{"sha":"45a29d68","branch":"master"},"scenery-phet":{"sha":"526003e4","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"382140f8","branch":"master"}}

**Comment by samreid** [comment]
Fixed in prior work, closing.
