### ISSUE TITLE
Prism is layered on top of Prism selection nav bar

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#244]
I noticed this on IE 11 Windows 10

<img width="590" alt="bendinglightbottombug" src="https://cloud.githubusercontent.com/assets/7717368/9999523/b2b6af18-604b-11e5-9ef0-aea24f37723d.png">

The prism is layered below the nav bar on the right.

**Comment by samreid** [comment]
This is consistent with the rest of the layering in the sim.  Items go above the south toolbox because items get dropped into it.  Items go behind the rightmost control panel so the control panel is not occluded.
