### ISSUE TITLE
Decide on the order of the tools in More Tools

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#245]
Intro screen has these tools, in this order:
* Protractor
* intensity meter
* checkboxes

More Tools screen has these tools, in this order:
* Protractor
* **Velocity sensor**
* **wave sensor**
* intensity meter
* checkboxes

So the velocity sensor and wave sensors "sneak between" the protractor and intensity meter.  It was somewhat easier to implement More Tools as:
* Protractor
* intensity meter
* Velocity sensor
* wave sensor
* checkboxes

and I realized it may also be more sensible for the user (new tools added at the bottom instead of in-between).  So I thought I'd ask where we want to have the tools for publication.  What do you recommend @arouinfar?

**Comment by arouinfar** [comment]
That's a great suggestion @samreid! The ordering you've proposed does seem more sensible to me, and given that it's easier to implement, we should do it.

**Comment by samreid** [comment]
Thanks, it is already implemented as such. Closing.
