### ISSUE TITLE
Increase size of laser touch area

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#248]
When playing withe the sim, @ariel-phet and I both felt that the laser was a bit tricky to rotate. The touch area looks pretty tight. 
![image](https://cloud.githubusercontent.com/assets/8419308/10113979/b26e2b30-63a7-11e5-857d-8c4fb0b96c2a.png)

Could the touch area be expanded to be a bit more like this?
![image](https://cloud.githubusercontent.com/assets/8419308/10114021/3ae23088-63a8-11e5-88f3-9fff27dc7826.png)

**Comment by samreid** [comment]
Sure, I'll take a look.  But I'm curious why you chose to have it be asymmetric about the x-axis?

**Comment by samreid** [comment]
Also be aware the prism screen laser has a knob there:

![image](https://cloud.githubusercontent.com/assets/679486/10409462/8173f1f8-6ede-11e5-9153-c2025d1ecde6.png)

**Comment by samreid** [comment]
Fixed above, but I'll leave this assigned to me since I still need to test the behavior on iPad.

**Comment by arouinfar** [comment]
@samreid, I originally left some extra padding on the left because I usually grab the laser behind the button to rotate it. The touch area could be made to be more symmetric, but it might not be necessary.

As for the laser with the knob, it would be good to expand the touch area a little bit more to the left to give users a bit more leeway.

**Comment by samreid** [comment]
Tested on iPad and it seemed good.  I posted a dev version for @arouinfar to review:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.34/bending-light_en.html

Please be aware of the new issues I identified this morning #259 and #258, please test the pointer areas and close if they look good.

**Comment by arouinfar** [comment]
Looks great @samreid. Thanks!
