### ISSUE TITLE
Performance optimization for Wave View

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#25]
I discussed wave view performance with @jonathanolson today and we concluded:

The approach that would yield the best performance would be to use WebGLNode and use a fragment shader that looks up the color for the pixel.
Then there would be 6 webgl triangles, 2 for each of the beams.
We could use charges-and-fields as an example (though it is doing double buffering, so it is a bit more complex)
Since canvas node cannot do repeating gradients, using canvasNode may be too slow here.
Instead, we should update scenery to make the Pattern transform mutable, and the gradient mutable, and render them using SVG.  Tests could be done outside of scenery to see if this is practical before spending time working on this.

**Comment by kmsravindra** [comment]
@ariel-phet, need your direction on this performance issue where we are currently stuck.

We have tried quite a few alternative approaches to address this performance issue – 1. Having particles on a canvas, 2. using scenery pattern , 3. moving images on a canvas, 4. moving a single large image on a canvas. None of the above options have yielded a successful result so far in terms of performance on iPad2 or IPad3. 
Coming to the above suggestion mentioned by Sam, it looks like there are 2 options to it. The first option is to try out WebGL.

If the second option of the above suggestion (updating scenery to render them as SVG)  is planned to be implemented by the PhET team, then we could go ahead with the second option.

So please let us know your direction on this.

**Comment by kmsravindra** [comment]
We did a some prototyping on WebGL node, relevant to the Bending light sim. Based on the initial set of results, the performance of the prototype turned out to be promising. So as per the direction from Ariel, WebGL implementation will be done on wave view node across 2 screens where it occurs viz., “Intro” screen and “More tools” screen.

**Comment by kmsravindra** [comment]
This has been implemented as planned and there has been a significant improvement in performance. So closing this issue.
