### ISSUE TITLE
typo in QA credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#255]
"Brian Yoelin" should be "Bryan Yoelin".

**Comment by samreid** [comment]
Same issue in Hooke's Law?

```js
qualityAssurance: 'Elise Morgan, Oliver Orejola, Brian Yoelin',
```

**Comment by samreid** [comment]
Fixed typo in bending light, I'll create a separate issue for Hooke's Law.

**Comment by pixelzoom** [comment]
FYI... It was already fixed in hookes-law. That's how I noticed the problem in bending-light.
