### ISSUE TITLE
Rendering artifacts on the Light radio buttons

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#259]
While testing Bending Light today, I noticed some extra rendering artifacts on the radio buttons on the prisms screen:

![image](https://cloud.githubusercontent.com/assets/679486/10489280/aa5eba20-7259-11e5-9fbe-1ec876c46026.png)

This appears on the iPad3 but not on OS X Chrome (for a built version out of master).  I can't think of any recent bending light code changes that would have caused this, so it may be a scenery issue.  Tagging @jonathanolson and @pixelzoom in case this is a larger issue.

**Comment by samreid** [comment]
No substantive changes have been made, but I can no longer reproduce this problem. Closing until we see it again.

**Comment by samreid** [comment]
This problem is back on my iPad3/iOS 9.0.2

**Comment by samreid** [comment]
@jonathanolson can you help me look into this at your convenience?

**Comment by samreid** [comment]
Voila, problem is gone again.  So flaky. :snowflake:

**Comment by samreid** [comment]
But this problem and #258 seem to co-occur.

**Comment by samreid** [comment]
Noticed again during #251

**Comment by samreid** [comment]
@jonathanolson & I identified that running uglify with 'none' solves the problem, with 'uglify2' we have the problem.

**Comment by samreid** [comment]
Here's a gist of the popup debug html:

https://gist.github.com/samreid/950c9ec1a33255f7af0d

**Comment by jonathanolson** [comment]
It's very weird, I'm curious about seeing the same debug output if uglify isn't run. I'm curious if it's switching to Canvas as a default (somehow?!?) as a result of the uglification, even without mangling.

Let me know if you're able to get popupDebug() output running without uglification on iOS.

**Comment by jonathanolson** [comment]
To reiterate, I'm not sure why it's displaying with Canvas as the seeming default. The only code I see that would switch things to Canvas is the Edge-browser detection, and that isn't happening (popupDebug output shows that there is no renderer override that would be set).

I'll look into tethering when on campus tomorrow to further investigate what's happening.

**Comment by samreid** [comment]
Running with ?screens=2 the problem disappears.

**Comment by samreid** [comment]
Running with ?screens=1.2 the problem reoccurs.

**Comment by samreid** [comment]
Leaving ?screens=1.2 and commenting out all of the other addChild calls in PrismsView, the problem goes away.

**Comment by samreid** [comment]
Adding in addChild calls one at a time, the problem reappears after adding in the WhiteLightCanvasNode.js

**Comment by samreid** [comment]
Commenting out the WhiteLightCanvasNode constructor body except for super call, and commenting out the paint method, the problem still occurs.

**Comment by samreid** [comment]
I no longer see this problem.  It may have been fixed by https://github.com/phetsims/scenery/issues/478 . Closing (until it happens again (!))

**Comment by samreid** [comment]
I'm still seeing this on a fresh build on the iPad3, @jonathanolson can you help at your convenience?

**Comment by samreid** [comment]
I manually cropped the laser image.  This issue is no longer blocking for publication, but still would be good to understand what is happening here.

**Comment by jonathanolson** [comment]
Presumably should be fixed with the mentioned commit (tested on my device). @samreid, can you try reproducing on your iPad?

**Comment by samreid** [comment]
I reverted the cropping above and removed the workaround. Rebuilding on iPad and testing with a fresh Safari, I no longer see any problems here.  Nice work @jonathanolson, thanks!
