### ISSUE TITLE
Prisms - The white light ray thickness

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#26]
The red light ray thickness matches but for the white light ray, the thickness in the Javascript ported sim looks 1px thicker than the Java sim. Perhaps this could also be the reason for a more diffused dispersion  - the rays suffering dispersion are not sharp unlike Java sim.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
