### ISSUE TITLE
stringTest=double fails in wavelength text box

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#262]
![image](https://cloud.githubusercontent.com/assets/679486/10543176/26501b48-73da-11e5-8f36-0fb2120617c8.png)

**Comment by samreid** [comment]
It could have performance impacts to resize things based on the text of this box while dragging.  @arouinfar @ariel-phet how do you want to proceed here?

**Comment by samreid** [comment]
Identified in #251

**Comment by ariel-phet** [comment]
@samreid - not convinced this text should be translatable? It is a number and a unit...do we normally allow translation of units?

**Comment by samreid** [comment]
I do not recall if we generally translate units.  In Java, it looks like nm is almost always nm (not sure if that is as desired or an oversight).  An exception I saw was for Arabic, where nm was translated as نانومتر

**Comment by ariel-phet** [comment]
@samreid can you look at the wavelength slider in Beer's law lab...is the nm translatable there?

**Comment by samreid** [comment]
Yes, those units all seem translateable:

```js
  "units.centimeters": {
    "value": "cm"
  },
  "units.liters": {
    "value": "L"
  },
  "units.molesPerLiter": {
    "value": "mol/L"
  },
  "units.mM": {
    "value": "mM"
  },
  "units.uM": {
    "value": "µM"
  },
  "units.nm": {
    "value": "nm"
  },
  "uv": {
    "value": "UV"
  },
```

I think the main question is whether we expect the translated string to get longer than a couple of characters.

**Comment by ariel-phet** [comment]
We do not...it should be an abbreviation. Let's not worry about rescaling text, and leave it to the translator to make the call. They will see if it is too long of a string, and I think most will leave it in english.

**Comment by arouinfar** [comment]
I agree with @ariel-phet that this is something we could leave to the translators. The Arabic translation of nm (نانومتر) literally spells out nanometer in the Arabic alphabet. There is most likely a suitable abbreviation that the translator could use in its place.

**Comment by samreid** [comment]
OK thanks for your consultation.  I'll close this one.
