### ISSUE TITLE
stringTest=long has some issues

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#263]
Here's a pic of screenTest=long:

![image](https://cloud.githubusercontent.com/assets/679486/10543252/977e051e-73da-11e5-8b1c-be21dcdb0f18.png)

@arouinfar and @ariel-phet I'm not sure how much time to spend on this.  stringTest=double is a much better indication of practical cases.  Do you want to address any of the issues in the screenshot above?

**Comment by samreid** [comment]
Discovered during #251

**Comment by ariel-phet** [comment]
@samreid remember stringTest=long does not need to be passed for publication, it just is there to reveal if anything whacky is going on. There are two issues that I see that would at least be worth understanding. Notice the the labels on tools like "Speed" and "Intensity" completely go away. That seems a little odd, but stringTest=double seems to work everywhere.

**Comment by ariel-phet** [comment]
To be clear, I do not think the labels going away necessarily needs to be addressed, but I am curious why the fonts don't seem to continue to scale down over a certain character length and just start to layout in odd ways on the tool labels.

**Comment by samreid** [comment]
Are you referring to the intensity meter?  If so, it looks like the percentage readout is internationalized like so:

```js
  "pattern_0value_percent": {
    "value": "{0}%"
  }
```
So that translators can choose where the % sign is (RTL/LTR) or whether it is a different symbol.  But this text is not scaled down since we didn't foresee the % sign or its replacement getting longer.  @ariel-phet close if this answers your question or reassign to me if you want me to get this text to scale down just in case the % symbol gets too wide in another language.

**Comment by ariel-phet** [comment]
@samreid I am referring to the label "intensity" on the intensity meter 

notice how the label starts to get uncentered with a longer string and such.

![intensity meter](https://cloud.githubusercontent.com/assets/4051174/10749494/81c2ebd2-7c30-11e5-8afd-445c2add12ff.PNG)

**Comment by samreid** [comment]
Nice catch, there was some odd layout code there.  I've got it fixed to be centered and now it looks like so:
![image](https://cloud.githubusercontent.com/assets/679486/10762090/1d91e762-7c8a-11e5-82c2-f41632a2bd75.png)

Will commit shortly.
