### ISSUE TITLE
Sim won't load in requirejs mode on iPad3

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#269]
For a week or more, the sim has just timed out when trying to load on iPad3 from requirejs mode.  Not critical to fix before publication, but would be good to understand why at some point.

**Comment by samreid** [comment]
@jessegreenberg as you are working on the review in #268 can you test requirejs loading on an iPad (if you have one) and report if it works or not?

**Comment by jessegreenberg** [comment]
Sure thing.  I have an iPad2, but I test with PhET's iPad3 for testing (I think its called diSessa).

**Comment by jonathanolson** [comment]
On my setup (iPad3, loading from Apache over wifi to ethernet), it loads in 11 seconds, and after the first 6 seconds it shows the sim title with version.

What web servers / connectivity do you have?

**Comment by samreid** [comment]
I'm using node http-server on wifi.  The logs show that it initially loads quickly and consistently then after 5-10 seconds gets stuck (stuck after a different file each time, no discernable pattern about whether they are png or js).

**Comment by samreid** [comment]
Apache seems like it solves this problem.  Therefore we can tentatively conclude this was a problem with http-server.  I'll continue with Apache and close this issue.
