### ISSUE TITLE
Mouse cursor to change to hand while hovering on Prisms shapes / Torch

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#27]
In Java sim the mouse cursor changes to hand while hovering on 1. Shapes, 2. Torch. 

Need to replicate this in javascript sim as well

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing.
