### ISSUE TITLE
RotationDragHandle flickers in chrome

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bending-light#273]
Noticed during #268, the RotationDragHandle arrows can sometimes flicker while the laser is being dragged.  I noticed this behavior in the 'More Tools' and 'Intro ' screens.  I observed this while running the sim with requirejs in Windows 7 Chrome 46.0.

![untitled screencast](https://cloud.githubusercontent.com/assets/6396244/10805763/e8d77da4-7d95-11e5-9097-5bc5fc90001b.gif)

Please excuse my janky dragging in the cast.

**Comment by samreid** [comment]
Proposed fix above, @jessegreenberg can you test it out?

**Comment by jessegreenberg** [comment]
Verified that the fix above resolves the issue.  Thanks @samreid, closing.
