### ISSUE TITLE
Clarify dissalowed WebGL comment

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bending-light#274]
Part of #268.   In BendingLightModel, the following line and comment exists:

```js
    // if WebGL support then particles creation and propagation not need else we should create particles and propagate
    // to render them on canvas. Check to see if WebGL was prevented by a query parameter
    var disallowWebGL = phet.chipper.getQueryParameter( 'webgl' ) === 'false';
```
The code is clear, but the additional comment above this line is hard to understand.  @samreid could you please clarify this documentation?

**Comment by samreid** [comment]
That comment was very confusing and unnecessary, I removed it in the above commit.

**Comment by jessegreenberg** [comment]
Sounds good, and looks good too. Thanks! Closing.
