### ISSUE TITLE
Strange static object in IntensityMeter

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bending-light#275]
In IntensityMeter, there is the following static object:

```js
    // @public static
    {
      Reading: Reading
    } );
```
Reading points to the Reading object loaded in modules.  This seems like a strange pattern to me.  The Reading object could be loaded into others with require instead of through the IntensityMeter static.  If this is a necessary static, could some documentation added to describe why?

**Comment by jessegreenberg** [comment]
Search through code reveals zero cases of IntensityMeter.Reading.  Can this public static be deleted?

**Comment by samreid** [comment]
Thanks @jessegreenberg, that does indeed appear unused.  I removed it above.

**Comment by jessegreenberg** [comment]
Thanks @samreid, looks good.  Closing.
