### ISSUE TITLE
Clamp function in MediumColorFactory already defined in Util

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bending-light#276]
Found as part of #268 consideration.  The ```clamp``` function at the top of MediumColorFactory is already defined in Dot.Util.  Is there a reason why the function in Dot.Util cannot or should not be used in this file?

**Comment by samreid** [comment]
In the above commit, I used the dot.Util.clamp implementation, but kept the 0..255 range factored out in a private closure function `clamp` in MediumColorFactory.

**Comment by jessegreenberg** [comment]
Ah, that makes sense.  I now see that it was being used to refactor the values in clamp to isolate numbers.  Looks good @samreid, closing.
