### ISSUE TITLE
'miss' should be 'missString' in Reading.js 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bending-light#277]
This was the only string in sim files that did not follow PhET string naming conventions. ```miss``` should be named ```missString``` in Reading.js.

**Comment by jessegreenberg** [comment]
```c_units``` in VelocitySensorNode should also be ```cUnitsString``` to match PhET conventions.  I find the underscore a little bit unconventional.

**Comment by samreid** [comment]
Fixed above, @jessegreenberg can you please double check the changes?

**Comment by jessegreenberg** [comment]
In the commit above, I notice that wavelengthPattern and velocityPattern restricts translation of the units 'nm' and 'c'.

@samReid was this an intentional restriction? These units are no longer translatable, and do not allow for RTL order in i18n.

**Comment by samreid** [comment]
The new strings are:

```js
  "waveLengthPattern": {
    "value": "{0} nm"
  },
  "velocityPattern": {
    "value": "{0} c"
  }
```

The translator can still specify the units and ordering in the translation (though in a different/simpler way than before).  For instance, in another language I could put 'nms {0}' for the wavelength pattern.

**Comment by samreid** [comment]
I also renamed waveLength to wavelength above.  Reassigning to @jessegreenberg for discussion.

**Comment by jessegreenberg** [comment]
@samreid, thank you for discussing this, I misunderstood the way that translatable string patterns worked for i18n.  My understanding of translatable ordering was like the following:
```js
  "someOrderedPattern": {
    "value": "{0} {1}"
  },
```
So that the order could be specified by the bracketed numbers like ```"value": "{1} {0}"``` .  It makes total sense now that 
```js
 "waveLengthPattern": {
    "value": "{0} nm"
  }
```
works just as well (if not better) since the units provide the translator with a hint of what the pattern means.

Happy to close unless you have anything else to add @samreid.

**Comment by samreid** [comment]
Thanks @jessegreenberg.  I think the only good time to use a pattern like {0} {1} is when it is essential that the string appearing in {0} or {1} must also identically match another string appearing elsewhere in the sim.  This sort of "factors it out".  I'll close this one.
