### ISSUE TITLE
Should public variables in Substance.js be @public (read-only)?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bending-light#278]
In Substance, the documentation at the top of the file states claims that the state for the medium is immutable.  This suggests that the properties of Substance should not be changed with the API.  

Should the properties of Substance be identified with ```@public (read-only)``` instead of ```@public```?

**Comment by samreid** [comment]
Fixed above, @jessegreenberg feel free to review if you wish.

**Comment by jessegreenberg** [comment]
Looks great @samreid.  Closing.
