### ISSUE TITLE
Open TODO's documented in sim code

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bending-light#279]
There are three remaining TODO's that are documented in Sim code. @samreid sorry if you are already aware of these TODO's, but I thought I would point them out as part of code review #268.

They exist in:
 - WavelengthControl (line 118 // TODO: Extend Node)
 - IntroView (line 84 // TODO: This should be different for wave mode)
 - VelocitySensorNode(line 103 // TODO: use scenery maxWidth?)

**Comment by samreid** [comment]
Fixed, thanks for finding this issue @jessegreenberg.  Can you take a look and make sure everything is OK?

**Comment by jessegreenberg** [comment]
Everything looks good and no more TODO's.  Closing.
