### ISSUE TITLE
Rotation / Translation green arrows

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#28]
1. The two arrows representing rotation are thicker and shorter in Java sim
2. The four arrows representing x-y translation in Java sim are - 
A. shorter,  B. thinner and C. and origin of all the four arrows is centered on the torch

Please refer Java sim.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
