### ISSUE TITLE
Incorrect type union in JSDoc

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/bending-light#280]
In a couple of places in the sim, I notice that params documented in the JSDoc with multiple types look like this:
```js
@param {Polygon/Circle/SemiCircle} shape
```
I think the correct style for type union in JSDoc should be
```js
@param {Polygon|Circle|SemiCircle} shape
```
using the | character.
I could not find an example of this in the PhET developer overview, but that style is suggested here:
http://usejsdoc.org/tags-type.html

**Comment by samreid** [comment]
Fixed above, @jessegreenberg please double check if you wish.

**Comment by jessegreenberg** [comment]
JSDoc is looking nice and tidy.  Closing.
