### ISSUE TITLE
Protractor icon looks bad on firefox

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#281]
![image](https://cloud.githubusercontent.com/assets/679486/10888015/1baf004e-8147-11e5-9ad7-dbd77274a36c.png)

Discovered in #271

**Comment by samreid** [comment]
It is already mipmapped.

**Comment by samreid** [comment]
Reducing the initial image size by 50% didn't seem to help too much:

![image](https://cloud.githubusercontent.com/assets/679486/10888367/0427f280-8149-11e5-97b7-1a3e0ab76e06.png)

**Comment by samreid** [comment]
Also note the jaggedness is sensitive to the window dimension.  Not sure what else we could do here other than generating a specific icon for the toolbox at a more appropriate size.  It still may be mangled a little bit and the code would be slightly more complex, but perhaps worth trying.

**Comment by samreid** [comment]
Using photoshop to bicubic downscale the image to 24% so scale can be set at 1 in the app, it looks good (smooth) in firefox:

![image](https://cloud.githubusercontent.com/assets/679486/10888721/12c21670-814b-11e5-957b-2b3f25b1d412.png)

But now it is horrible on retina iPad (compare to vector probe):

![image](https://cloud.githubusercontent.com/assets/679486/10888754/3db11a02-814b-11e5-9926-880186196674.png)

@ariel-phet and @arouinfar can you look at the protractor icon in firefox in dev.37 (linked below) and let me know if further changes are required for this issue:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.37/bending-light_en.html

**Comment by arouinfar** [comment]
I notice a slight difference between Chrome (left) and Firefox (right) on my Mac, but it looks acceptable to me.
![image](https://cloud.githubusercontent.com/assets/8419308/10895213/3f021efe-8170-11e5-990d-f922a318f5ff.png) ![image](https://cloud.githubusercontent.com/assets/8419308/10895357/fd416410-8170-11e5-8d1d-f0efa917ded2.png)

The screenshot from the retina iPad looks awful, though. @samreid, do you plan on creating a new issue to take care of it? If so, this one can be closed.

**Comment by samreid** [comment]
The code/image that generated the iPad screenshot screenshot was never checked in, se we should be good to go here, closing.
