### ISSUE TITLE
Design team testing

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#286]
@ariel-phet and @arouinfar, after finishing #271 I'm ready for the design team to take a close look at the simulation before we turn it over to the QA team for dev testing or RC testing.  @ariel-phet and @arouinfar can you test drive this version and report your findings?

http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.39/bending-light_en.html

If all is clear, then @ariel-phet can you please recommend whether we start with preliminary dev testing or full RC test as next step?

**Comment by arouinfar** [comment]
@samreid, the first two screens are looking good, with the exception of #287. I'll finish testing the More Tools screen tomorrow.

**Comment by ariel-phet** [comment]
@samreid - no matter what it should be dev tested before full RC since so many changes have occurred. I will instruct the testers however not to bother putting out ridiculous numbers of components on the prisms screen, except to get a feel for limitations.

**Comment by samreid** [comment]
Sounds like a good plan.

**Comment by arouinfar** [comment]
@samreid, everything looks good on my end.

**Comment by ariel-phet** [comment]
@samreid I think after our discussion yesterday, I am solid. Closing
