### ISSUE TITLE
Environment color mapping not updating properly

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#287]
Discovered a bug on the Prisms screen when testing dev.29 on OSX 10.9.5/Chrome. If the index of refraction of the Environment is changed while in white light mode, the background will stay black/gray when switched back to either monochromatic mode until the environment's index of refraction is changed again.

Steps to reproduce
1) Open the Prisms screen & select white light
2) Change the Environment's index of refraction using slider or drop-down menu
3) Switch to either of the monochromatic modes. The environment will stay black/gray until its index of refraction is changed again.

**Comment by samreid** [comment]
Thanks for finding this issue @arouinfar, I reproduced this problem in dev.39.
