### ISSUE TITLE
Larger "play" button.

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#289]
In discussion with @ariel-phet, we decided to make the "play" button a bit larger like in energy skate park, when the sim is paused.

**Comment by samreid** [comment]
Here is the relevant code from Energy Skate Park: Basics.  This pattern has not been "commonized" yet and I'm not sure if it should be.

```js
    // Make the Play/Pause button bigger when it is showing the pause button, see #298
    var pauseSizeIncreaseFactor = 1.35;
    playProperty.lazyLink( function( isPlaying ) {
      playPauseButton.scale( isPlaying ? ( 1 / pauseSizeIncreaseFactor ) : pauseSizeIncreaseFactor );
    } );
```

**Comment by samreid** [comment]
The above pattern works nicely in this sim.  I increased the padding between the other components (radio buttons + step button) so things look nicer when the play button is larger.  I also settled on scale=1.28 rather than 1.35 since 1.35 seemed too large in this context and the 1.28 aligned better with the size of the radio buttons.

@ariel-phet do you want to pull and verify?  Or should I publish a version?

**Comment by ariel-phet** [comment]
Pulled...looks good, closing.
