### ISSUE TITLE
Performance with white light, multiple rays

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#29]
As expected and similar to the Java sim, the performance with white light mode decreases significantly compared to the single color mode. It starts getting degraded more and more as more shapes, reflections, normal, multiple rays options are loaded. @ariel-phet, Request your direction on this.

**Comment by ariel-phet** [comment]
@kmsravindra - lets focus on just a single ray for white light mode. I think the multiple rays are not necessary for the white light mode. It would be good to get performance that matches the Java version for white light mode and a single ray.

**Comment by kmsravindra** [comment]
Performance in Single ray white light mode matches that of Java version post WebGL enabling. Closing this issue for now.
