### ISSUE TITLE
Rounding error in wavelength control

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#292]
Using the arrows to change the wavelength in the range ~477-510 nm, there is a rounding error that displays the floating points. Once the decimal places appear, they won't go away until the slider is used. This occurs on both the 2nd and 3rd screens, regardless of Ray or Wave. Tested on my personal device, Win 8.1 Chrome.

![long wavelength](https://cloud.githubusercontent.com/assets/5863899/11042291/7963b838-86d3-11e5-8151-fbb75484ed32.PNG)

Troubleshooting information:
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.40/bending-light_en.html
Version: 1.0.0-dev.40 2015-11-06 18:23:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a290c609","branch":"master"},"axon":{"sha":"2826c426","branch":"master"},"babel":{"sha":"8515ba97","branch":"master"},"bending-light":{"sha":"8864e0db","branch":"master"},"brand":{"sha":"3b236d6f","branch":"master"},"chipper":{"sha":"9682d417","branch":"master"},"dot":{"sha":"d7ae6e3f","branch":"master"},"joist":{"sha":"75c4552d","branch":"master"},"kite":{"sha":"ad37246b","branch":"master"},"phet-core":{"sha":"e669e892","branch":"master"},"phetcommon":{"sha":"9220e286","branch":"master"},"scenery":{"sha":"e79b8778","branch":"master"},"scenery-phet":{"sha":"0fb18ecb","branch":"master"},"sherpa":{"sha":"f3cf6285","branch":"master"},"sun":{"sha":"32723e9a","branch":"master"},"tandem":{"sha":"bab69e54","branch":"master"}}

**Comment by samreid** [comment]
I have reproduced the problem:

![image](https://cloud.githubusercontent.com/assets/679486/11162154/b74dd472-8a51-11e5-9c1e-3f5c4b1f7291.png)

**Comment by samreid** [comment]
Fixed above, was straightforward, no need for re-testing.
