### ISSUE TITLE
Reflection during equal indicies of refraction

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#293]
1. Go to the "More Tools" screen, it's best noticeable there.
2. Check "Angles". This is the best way to see if there is a reflection (the intensity meter works, too).
3. Turn on and drag the laser to an angle between 89.9 and 85 degrees.
4. Keeping the upper material at its default "Air" setting, use the slider to change to bottom material to air by sliding all the way left. Do not use the combo box, just the slider.
5. There will be an angle indicating a reflection that shouldn't exist, and the intensity meter reads 0.00% while hovering over the reflection as opposed to just reading "-".
6. You can flip steps 3 & 4 for a more...dramatic effect.

![phantom reflection](https://cloud.githubusercontent.com/assets/5863899/11043135/7d4f8f62-86d8-11e5-9546-0772924a0b76.PNG)

Gif to help you reproduce:

![bendli](https://cloud.githubusercontent.com/assets/5863899/11043259/18f4469c-86d9-11e5-9c8b-91c96bf91977.gif)

Tested on my personal device, Win 8.1 Chrome.
Troubleshooting information:
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.40/bending-light_en.html
Version: 1.0.0-dev.40 2015-11-06 18:23:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a290c609","branch":"master"},"axon":{"sha":"2826c426","branch":"master"},"babel":{"sha":"8515ba97","branch":"master"},"bending-light":{"sha":"8864e0db","branch":"master"},"brand":{"sha":"3b236d6f","branch":"master"},"chipper":{"sha":"9682d417","branch":"master"},"dot":{"sha":"d7ae6e3f","branch":"master"},"joist":{"sha":"75c4552d","branch":"master"},"kite":{"sha":"ad37246b","branch":"master"},"phet-core":{"sha":"e669e892","branch":"master"},"phetcommon":{"sha":"9220e286","branch":"master"},"scenery":{"sha":"e79b8778","branch":"master"},"scenery-phet":{"sha":"0fb18ecb","branch":"master"},"sherpa":{"sha":"f3cf6285","branch":"master"},"sun":{"sha":"32723e9a","branch":"master"},"tandem":{"sha":"bab69e54","branch":"master"}}

**Comment by phet-steele** [comment]
Changing to Air via the combo box and not the slider will not display an angle, but the intensity and speed meters still indicate the presence of a reflection.

**Comment by phet-steele** [comment]
....and the time meter.

**Comment by samreid** [comment]
Lots of related problems here:
(1) The minimum for the index of refraction slider is currently 1, but it should be the same as glass.

```js
var INDEX_OF_REFRACTION_MIN = Substance.AIR.indexForRed;
```
(2) In the IntroModel, if the reflected power ratio is <= 0.05 or so, then there should be no reflected ray instance.

(3) In AngleNode, we need a better way of handling the existence/non-existence of different rays.  To do this, we should add a lightType argument to the LightRay constructor, so the AngleNode can easily determine which rays are reflected and refracted.

**Comment by samreid** [comment]
Related to (2), if there is no reflected ray instance (say its power is <0.05), then the refracted power should be set to 1.0 (rather than 0.95 or so).

OH WAIT, perhaps the threshold should be 0.005 since the intensity meter shows two decimal places.

**Comment by samreid** [comment]
Another possibility: when there is no reflected ray (reflected power < 0.005), just extend the incident ray rather than having an incident and refracted ray.  At some (rare) angles you can see a tiny glitch between the rays:

![image](https://cloud.githubusercontent.com/assets/679486/11167222/99d5bf84-8b16-11e5-8a24-134697f2df24.png)

**Comment by samreid** [comment]
Not sure if the rule proposed above would result in a noticeable discontinuity in angle as a function of index of refraction.

**Comment by samreid** [comment]
Fixed above, tests seem like it is working properly, video demonstrates the new behavior:

![angles](https://cloud.githubusercontent.com/assets/679486/11167393/b2848536-8b1d-11e5-8ccd-41020fbb08c5.gif)

This change entailed numerous changes to the model and will require another dev test (single platform OK).

**Comment by samreid** [comment]
I published a dev version here:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.41/bending-light_en.html

@ariel-phet can you do a spot test on it and help decide if/when we should cease testing of dev.40 and continue with this one?  This version addresses #292 #293 and #294 and https://github.com/phetsims/tasks/issues/414 is only showing 1/4 platforms completed at the moment.  #292 and #293 are model-ish changes that could be verified on a single platform.

**Comment by samreid** [comment]
Also, it would be good for the reporter of this problem @phet-steele to verify that dev.41 is working properly.

**Comment by ariel-phet** [comment]
@samreid new (or unnoticed previously) problem with this version. Speed meter is still reading the refracted ray, even with no refracted ray.

![capture](https://cloud.githubusercontent.com/assets/4051174/11170371/82e8fb32-8b8f-11e5-9122-55af24ccc36d.PNG)

**Comment by ariel-phet** [comment]
@samreid we will want to address the bug I show above before next dev testing

**Comment by samreid** [comment]
I moved the speedometer problem to #296.   @ariel-phet or @phet-steele anything else to do for this issue?

**Comment by ariel-phet** [comment]
No, I think we are good, closing
