### ISSUE TITLE
Tools (speed meter, intensity probe, time) WAY too big

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/bending-light#295]
Tools such as the speed meter are far too large. This creates some usability issues since the tools "bounce" out from under control panels. For instance the size of the speed meter could be significangly reduced. The readout has lots of extra padding, the word speed is extremely large, the entire tool body should probably be 50 percent its current size.

![capture](https://cloud.githubusercontent.com/assets/4051174/11170389/f5262a94-8b8f-11e5-85c2-95345faff310.PNG)

**Comment by samreid** [comment]
After iteration, here's the size I settled on for the velocity sensor (about 54%), will commit shortly.

![image](https://cloud.githubusercontent.com/assets/679486/11189560/044baf08-8c4e-11e5-9aac-f00266db4cbb.png)

Next I need to update the size of the tool in the toolbox, then work on the intensity meter.

**Comment by samreid** [comment]
Fixed intensity sensor probe size above, looks like this now:

![image](https://cloud.githubusercontent.com/assets/679486/11190342/2f84fbd0-8c52-11e5-8679-6abe95354ad0.png)

Leaving assigned to @samreid to create a dev version for @ariel-phet.

**Comment by samreid** [comment]
Fixed in this version, http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.42/bending-light_en.html  @ariel-phet can you check it out and report back?

**Comment by ariel-phet** [comment]
@samreid - the physical size of these tools is looking much better. I suggest a few more polishes:

1. Make the word "intensity" the same size font as Speed (looks a bit bigger currently)
2. Same with the word "Time"
3. On the time meter make the wires the same stroke weight as the on the intensity meter (they are currently very heavy)

@arouinfar do you like the current size in dev.42?

**Comment by arouinfar** [comment]
@samreid @ariel-phet The tool size looks great! I agree with @ariel-phet's design suggestions, but otherwise have no other tweaks to suggest.

**Comment by samreid** [comment]
Also addressed in a4afab0c1440b3133149f4e48f3c4361d14e93d2

**Comment by samreid** [comment]
New version is here:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.44/bending-light_en.html

@ariel-phet can you take a look?

**Comment by arouinfar** [comment]
Looks great @samreid!

**Comment by ariel-phet** [comment]
Worked with @samreid on some final polishes, looking good, closing
