### ISSUE TITLE
Speed meter is still reading the refracted ray, even with no refracted ray.

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#296]
In https://github.com/phetsims/bending-light/issues/293#issuecomment-156843089, @ariel-phet said:

@samreid new (or unnoticed previously) problem with this version. Speed meter is still reading the refracted ray, even with no refracted ray.

![capture](https://cloud.githubusercontent.com/assets/4051174/11170371/82e8fb32-8b8f-11e5-9122-55af24ccc36d.PNG)

**Comment by samreid** [comment]
@ariel-phet I am having difficulty replicating the problem you described.  Can you provide details?

**Comment by samreid** [comment]
@ariel-phet showed that this problem can be reproduced by putting the laser at 89 degrees (almost horizontal), the positioning the sensor, then putting the laser horizontal.

**Comment by samreid** [comment]
I'm seeing the same problem with the intensity sensor.

**Comment by samreid** [comment]
Fixed, here is a movie:

![laserangle](https://cloud.githubusercontent.com/assets/679486/11188690/5c087b4a-8c49-11e5-8673-a29f1efeec40.gif)

I'll leave this open and assigned to @samreid to create a dev version for @ariel-phet.

**Comment by samreid** [comment]
Published a new dev version here: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.42/bending-light_en.html @ariel-phet can you confirm this fix?

**Comment by ariel-phet** [comment]
Looking good. Closing
