### ISSUE TITLE
Check that the wave intensity and ray intensity are the same

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#298]
You shouldn't switch view type and have the light disappear.

**Comment by samreid** [comment]
SingleColorLightCanvasNode.js has alpha = Math.sqrt( ray.powerFraction ).

The WebGL wave node has alpha = 'gl_FragColor.a = uPowerFraction;',

The canvas webglnode has waveCrest.alpha = Math.sqrt( lightRay.powerFraction ) and waveBackground.alpha = Math.sqrt( lightRay.powerFraction ).

So it looks like we just need to fix the WebGL wave node alpha to use a sqrt.  Perhaps do this in the GPU for a slight speed boost.

**Comment by samreid** [comment]
Fixed above.  Seems like this fixes the problem nicely.  I'll leave this assigned to @samreid to create a dev version for @ariel-phet to review.

**Comment by samreid** [comment]
Published a dev version here, http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.42/bending-light_en.html @ariel-phet can you confirm this fix?

**Comment by ariel-phet** [comment]
Looking really good to me. Closing.
