### ISSUE TITLE
Impossible to see wave crests at low power

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#299]
When a reflected or refracted ray has low power, it is impossible to see the wave crests.  Discovered during #298, looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/11188324/7548e2ae-8c47-11e5-99f9-96bf853e820a.png)

@ariel-phet is there anything we can/should do about this?

**Comment by ariel-phet** [comment]
@samreid I don't think this is a problem, since it is low power
