### ISSUE TITLE
Vertical boundaries are not stable

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#3]
I noticed that when finely selecting the wavelength of the light the borders between the two mediums will shift up vertically by a pixel or two. Look at the screenshot for proper setup.
![screen shot 2015-01-05 at 12 33 22 pm](https://cloud.githubusercontent.com/assets/7717368/5618553/512899b8-94d7-11e4-9df0-19cfd453e7e1.png)

**Comment by phet-steele** [comment]
Do you see this any more @bryo5363? I don't.

**Comment by bryo5363** [comment]
@phet-steele I do not notice this anymore. Closing
