### ISSUE TITLE
Introducing a prism in White light, multiple ray mode distorts the middle white ray

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#30]
To replicate the issue - 
1. Choose white light, multiple ray mode
2. Switch on the torch
3. Introducing any prism shape into the white light rays.

Notice the distortion of the middle white ray that happens somewhere in between the torch and prism.

**Comment by ChandrashekarBemagoni** [comment]
It's same in  the Java version as well.

**Comment by kmsravindra** [comment]
Now the issue looks fixed after implementing the fix for. Closing.
