### ISSUE TITLE
Move the title of the intensity meter to the bottom

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#300]
Discovered during #295, the labels on the velocity sensor and wave sensor are at the bottom.  This is good since the readout is not occluded on a touch device.  I recommend to move the label to the bottom of the intensity meter as well, for consistency with the other sensors.  Tagging @ariel-phet and @arouinfar in case there are problems with this.

**Comment by samreid** [comment]
Looks good, closing:
![image](https://cloud.githubusercontent.com/assets/679486/11190319/0eadfeac-8c52-11e5-97e3-516db7922392.png)

**Comment by arouinfar** [comment]
Looks good to me @samreid. Thanks!
