### ISSUE TITLE
"Step" when slow motion is selected is smaller than "step" when normal is selected

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#302]
I noticed that "Step" when slow motion is selected is smaller than "step" when normal is selected during #301.  It seemed a bit counterintuitive and unexpected, but @ariel-phet and @arouinfar what is the desired behavior?  Should Normal/Slow Motion have any bearing on the amount of time that passes when pressing the "step" button?  Pressing step when "slow motion" is selected yields a very small step indeed.

**Comment by ariel-phet** [comment]
Agreed, "step" should be a constant time step regardless of whether in slow motion or normal.

**Comment by arouinfar** [comment]
:+1:
> Agreed, "step" should be a constant time step regardless of whether in slow motion or normal.

**Comment by samreid** [comment]
New version is here:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.44/bending-light_en.html

@ariel-phet or @arouinfar can you verify?

**Comment by ariel-phet** [comment]
Looks good, closing
