### ISSUE TITLE
Design team testing (Part II)

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#305]
I've finished developer testing part II in #301, and published a new dev version http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.43/bending-light_en.html

We are at a good point to have @ariel-phet and @arouinfar test the new version a bit more thoroughly before we create another dev or RC version.

**Comment by ariel-phet** [comment]
review complete from me, final polishes communicated to @samreid I think we can move on to dev testing soon.

**Comment by arouinfar** [comment]
Everything looked good on my end!
