### ISSUE TITLE
Shrink the velocity sensor toolbox icon by about 15%

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#306]
@ariel-phet suggested to Shrink the velocity sensor toolbox icon by about 15%

**Comment by samreid** [comment]
New version is here:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.44/bending-light_en.html

@ariel-phet can you take a look?

**Comment by ariel-phet** [comment]
Looking good, closing
