### ISSUE TITLE
Update the wave sensor probe nodes

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#307]
@ariel-phet suggested improving the wave sensor probe nodes, they look a bit out of date.  Perhaps try ProbeNode with crosshairs?

**Comment by samreid** [comment]
New version is here:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.44/bending-light_en.html

@ariel-phet can you take a look?

**Comment by ariel-phet** [comment]
Worked on with @samreid, looking good, closing
