### ISSUE TITLE
Wave view disconnects from laser with rapid movement (currently won't fix)

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/bending-light#310]
Test device: iPad2, Witten

Operating System: iOS 9.1 (13B143)

Browser: Safari

Problem description: Wave noticeably separates from the generator if you are dragging it back and forth across the screen.

Steps to reproduce: Select wave mode. Drag generator back and forth.

Severity: Minor.

Screenshots:
https://drive.google.com/file/d/0B_TAL-jnJOoKenh5TkN2TDdXUE0/view?usp=sharing

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.45/bending-light_en.html
Version: 1.0.0-dev.45 2015-11-20 05:48:24 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"e67f1f6a","branch":"master"},"bending-light":{"sha":"51676950","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"a4994516","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"joist":{"sha":"446cc8e8","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"d9d2e688","branch":"master"},"scenery":{"sha":"a4a93afb","branch":"master"},"scenery-phet":{"sha":"5a6969fe","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"7b4a98d6","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"}}

**Comment by samreid** [comment]
There was a similar issue in https://github.com/phetsims/bending-light/issues/119 .  In that thread, the issue was reported to be rare on iPad 2.

**Comment by samreid** [comment]
@ariel-phet @arouinfar do you want to spend time investigating this before publishing bending light 1.00?

**Comment by ariel-phet** [comment]
I will need to reproduce it and see how bad it is....is it a normal use case, or does it require really quick movements of the laser pointer

**Comment by samreid** [comment]
@elisemorgan included a movie above showing the problem on a device: https://drive.google.com/file/d/0B_TAL-jnJOoKenh5TkN2TDdXUE0/view?pli=1

**Comment by arouinfar** [comment]
@ariel-phet @samreid I've never witnessed this behavior while using the sim on Mac, iPad2, or iPad3 -- even when rapidly moving the laser (though I haven't used dev.45 on iPad). I can more carefully investigate this issue to see if I can reproduce.

**Comment by ariel-phet** [comment]
@samreid I think during "normal use cases" this is either extremely minor, or not noticeable at all. Only rapid movement of the laser causes the issue, which is not such a useful pedagogical scenario.

However, could you close this issue and make an unassigned issue to the effect of "consider rendering laser in webgl" or such - whatever the eventual solution would be. So that if we are republishing the sim at some point in the future, we consider a tweak that fixes this problem.

**Comment by samreid** [comment]
It is unclear what the eventual solution would be, so how about leaving this issue open and unassigned rather than creating a new issue that refers to this one?

**Comment by ariel-phet** [comment]
Sounds good

**Comment by samreid** [comment]
@KatieWoe can you please test if this is still a problem on our current slowest supported platform?

**Comment by KatieWoe** [comment]
Wasn't able to reproduce on ChromeOS

**Comment by samreid** [comment]
Thanks.  Let's close for now and we can reopen if the problem recurs.
