### ISSUE TITLE
String Tests on iPad 2

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/bending-light#311]
Test device: iPad 2, Witten

Operating System: iOS 9.1 (13B143)

Browser: Safari

Problem description: The protractor in the prisms screen is lost during both long and double string tests. The layout gets crazy with the long string test on More Tools page.

Steps to reproduce:

Severity:

Screenshots:
![image 2](https://cloud.githubusercontent.com/assets/12610678/11318556/eefb33f6-9014-11e5-834e-d57bcc43791a.png)
![image 3](https://cloud.githubusercontent.com/assets/12610678/11318557/f90dbf6c-9014-11e5-90ac-d7d563abdc46.png)

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.45/bending-light_en.html
Version: 1.0.0-dev.45 2015-11-20 05:48:24 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"e67f1f6a","branch":"master"},"bending-light":{"sha":"51676950","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"a4994516","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"joist":{"sha":"446cc8e8","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"d9d2e688","branch":"master"},"scenery":{"sha":"a4a93afb","branch":"master"},"scenery-phet":{"sha":"5a6969fe","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"7b4a98d6","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"}}

**Comment by samreid** [comment]
@ariel-phet can you evaluate this issue and discuss what to do about it?

**Comment by ariel-phet** [comment]
Fix sliders as dicussed

For ray and wave toolbox, set limit of size so it does not interfere with the laser position

**Comment by samreid** [comment]
> Fix sliders as dicussed

I think what we discussed is that we don't know why the sliders are getting so wide, and they are a large part of the problem.  We should try to find out why the sliders are getting wide and try to prevent it if possible.

**Comment by samreid** [comment]
Fixed above, the sliders were basing their size on invisible tweaker buttons.  Much better now for stringTest=double.

**Comment by samreid** [comment]
New longStringTest on Intro:
![image](https://cloud.githubusercontent.com/assets/679486/11581917/20c3c7fa-9a05-11e5-9105-3902d39da202.png)

Doesn't seem helpful on More Tools:
![image](https://cloud.githubusercontent.com/assets/679486/11581924/36773e4c-9a05-11e5-81c1-ca99894a09e5.png)

**Comment by samreid** [comment]
Putting maxWidth on the readout seems to help this (even if it is a rare case):

![image](https://cloud.githubusercontent.com/assets/679486/11581965/d29327aa-9a05-11e5-8184-a9a005ac5c8b.png)

Commits are above.  Seemed straightforward, so I will close. @ariel-phet please reopen if you wish to test further.
