### ISSUE TITLE
misplaced responsibility for laser image

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#312]
Noted while working on https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2 (generalize LightNode).

Currently in BendingLightView:

```js
function BendingLightView( ... laserImageName ... ) {
...
    var laserImage = (laserImageName === 'laser') ? laserWithoutKnobImage : laserKnobImage;
    var laserNode = new LaserNode( this.modelViewTransform, bendingLightModel.laser, showRotationDragHandlesProperty,
      showTranslationDragHandlesProperty, clampDragAngle, laserTranslationRegion, laserRotationRegion, laserImage,
      this.visibleBoundsProperty,
      occlusionHandler
    );
```

A couple of suggestion ....

(1) Instead of passing in `{string} laserImageName` to BendingLightView, pass in `{boolean} laserHasKnob`.

(2) Instead of making BendingLightView responsible for the image used by LaserNode, pass `{boolean} laserHasKnob` to LaserNode's constructor, and let it handle the specifics of choosing the appropriate image.

**Comment by samreid** [comment]
@ariel-phet are we going to have another dev test before RC testing?  If so, I'd like to address this beforehand.

**Comment by ariel-phet** [comment]
yes there will be another dev test

**Comment by samreid** [comment]
In the above commit, I am passing the image directly rather than encoding as string/boolean and decoding.

**Comment by pixelzoom** [comment]
This is going in the wrong direction. Now the responsibility is in IntroView and PrismView.   How does this facilitate being able to use a generalized node for the laser, as mentioned above and described in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2 ?

**Comment by samreid** [comment]
> How does this facilitate being able to use a generalized node for the laser,

We are now 1 refactoring step away from changing the argument from HTMLImageElement to scenery.Node, which would let you use a generalized node for the laser.

I'm unfamiliar with https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2 .  Is the intention to move LaserNode to scenery-phet?  Or something else?

**Comment by pixelzoom** [comment]
scenery-phet.LightNode (final name TBD) will be created programmatically (no images) and will look like this:

![screenshot_87](https://cloud.githubusercontent.com/assets/3046552/11597167/2b5e1d7e-9a77-11e5-8f52-4ec0cc9e20d9.png)

There will be no "knob" feature, since that seems to be specific to bending-light.

Presuming that you think this should be reused in bending-light...  Changing bending-light will be least painful if all responsibilities for the "look" of the laser are in LaserNode - which is currently not the case.  If all responsibilities for the "look" of the laser are in LaserNode, then it can be rewritten to use LightNode, decorated with a knob if `options.hasKnob === true`.  And until LightNode is ready, you could use this same `hasKnob` option to decide which image to use *within LaserNode*.

**Comment by samreid** [comment]
I moved hasKnob to LaserNode.js in the above commit.  It is still required (as are all other LaserNode parameters at the moment).  Not sure how many LaserNode params (if any) should move into options.  @pixelzoom any other suggestions/recommendations for this issue?

**Comment by samreid** [comment]
For the record, there is only one occurrence of `new LaserNode`--in case that pertains to whether args should be required or optional.

**Comment by pixelzoom** [comment]
:+1: Closing.
