### ISSUE TITLE
laserTranslationRegion or getProtractorRotationRegion?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#313]
IntroView is a subset of BendingLightView,  and the 5th parameter to BendingLightView should be `{function} laserTranslationRegion`. But IntroView is passing in something called `this.getProtractorRotationRegion`, here's the call in IntroView:

```js
    BendingLightView.call( this,
      introModel,
      clampDragAngle,
      clockwiseArrowNotAtMax,
      ccwArrowNotAtMax,
      this.getProtractorRotationRegion,
      rotationRegionShape,
      'laser',
      centerOffsetLeft,
      0,
      // No need to handle occlusions
      function() {}
    );
```

Is this a subtle error, or just a poor choice var name?

**Comment by pixelzoom** [comment]
Similar problem in PrismView.  In that case, something called `translationRegion` is passed as the `laserTranslationRegion` arg, but it's documented as "Region for translating the protractor":

```js
/**
     * Region for translating the protractor
     * @param {Shape} fullShape
     * @returns {*}
     */
    function translationRegion( fullShape ) {

      // Empty shape since shouldn't be rotatable in this tab
      return fullShape;
    }
```

**Comment by samreid** [comment]
Issues fixed above.

**Comment by pixelzoom** [comment]
Looks good, closing.
