### ISSUE TITLE
BendingLightView has too many required constructor parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#315]
Noted while investigating #313 and #314.

BendingLightView has too many required constructor parameters, making it very difficult to read at call sites.  Any parameters that have reasonable default values should be converted to options. 

Example call site in PrismView, to demonstrate how difficult this is to grok:

```js
BendingLightView.call( this,
      prismsModel,
      clampDragAngle,
      clockwiseArrowNotAtMax,
      ccwArrowNotAtMax,
      translationRegion,
      rotationRegionShape,
      'laserKnob',
      90,
      -43,
      // occlusion handler, if the prism is dropped behind a control panel, bump it to the left.
      function( node ) {

        var controlPanels = [
          laserControlPanel, // eslint-disable-line no-use-before-define
          environmentMediumControlPanel // eslint-disable-line no-use-before-define
        ];
        controlPanels.forEach( function( controlPanel ) {
          if ( controlPanel.globalBounds.containsPoint( node.globalBounds.center ) ) {
            node.translateViewXY( node.globalToParentBounds( controlPanel.globalBounds ).minX - node.centerX, 0 );
          }
        } );
      }
    );
```

**Comment by samreid** [comment]
@ariel-phet are we going to have another dev test before RC testing? If so, I'd like to address this beforehand.

**Comment by ariel-phet** [comment]
Yes, we will have another dev test.

**Comment by samreid** [comment]
I agree 10 required arguments is longer than normal and more difficult to grok.  However, converting these to options values would also mean moving toward a non-standard documentation for the options types (is there a good way to do this?).  What about leaving them as required parameters (annotated with `@param`) and adding the var name annotations in source like so (done in commit above):

```js
    BendingLightView.call( this,

      // bendingLightModel
      introModel,

      // clampDragAngle
      clampDragAngle,

      // clockwiseArrowNotAtMax
      clockwiseArrowNotAtMax,

      // ccwArrowNotAtMax
      ccwArrowNotAtMax,

      // laserTranslationRegion
      this.getProtractorRotationRegion,

      // laserRotationRegion
      rotationRegionShape,

      // laserImageName
      'laser',

      // centerLeftOffset
      centerOffsetLeft,

      // verticalOffset
      0,

      // occlusionHandler: No need to handle occlusions
      function() {}
    );
```

**Comment by samreid** [comment]
Done for the other call site above.

**Comment by pixelzoom** [comment]
@samreid wrote:
> converting these to options values would also mean moving toward a non-standard documentation for the options types

I don't understand.  How would (for example) having options `centerLeftOffset:0` and `verticalOffset:0` be a problem? (Though I recommend replacing them with `modelViewTransform:ModelViewTransform2.IDENTITY`, see https://github.com/phetsims/bending-light/issues/316#issuecomment-162032782). 

The issue is probably that changing from constructor parameters to options is a lot of work. So if you want to proceed with constructor parameters, a few problems with the approach shown in https://github.com/phetsims/bending-light/issues/315#issuecomment-161851088.

(1) Redundant comments. For example, this tell me nothing:

```js
     // ccwArrowNotAtMax
      ccwArrowNotAtMax,
```

If the var and param have the same names, there's no need to have a comment.   A comment is helpful for situations where the var name is different, or the arg is a constant, eg: 

```js
      // verticalOffset
      0,
```

(2) Inconsistent names, for example:

```js
      // centerLeftOffset
      centerOffsetLeft,
```

Why would you name the var `centerOffsetLeft` and the parameter `centerLeftOffset`?

Example:

```js
      // laserRotationRegion
      rotationRegionShape,
```

Why is one a "RegionShape" and the other a "Region", is there a difference? 

Does `rotationRegionShape` is the region of what? The laser? If it's the laser, why not `laserRotationRegion` to be consistent? If it's something else, why not clarify?

(3) Putting comments on their own lines takes up too much space.  That would be ok if there was useful information being on those lines, but (for most of the lines) there's not.  What's wrong with this?  It clarifies the parameters that require clarification.

```js
BendingLightView.call( this,
      introModel, // bendingLightModel
      clampDragAngle,
      clockwiseArrowNotAtMax,
      ccwArrowNotAtMax,
      this.getProtractorRotationRegion,  // laserTranslationRegion
      rotationRegionShape, // laserRotationRegion
      'laser',  // laserImageName
      centerLeftOffset,
      0,  // verticalOffset
      function() {} // occlusionHandler: No need to handle occlusions
    );
```

**Comment by samreid** [comment]
> I don't understand. How would (for example) having options centerLeftOffset:0 and verticalOffset:0 be a problem?

I think it would work OK, the types would be documented like this example in Hooke's Law:
```js
  /**
   * @param {Object} [options]
   * @constructor
   */
  function RoboticArm( options ) {

    var thisArm = this;

    options = _.extend( {
      left: 0,  // {number} initial x location of the left (movable) end of the arm, units = m
      right: 1 // {number} initial x location of the right (fixed) end of the arm, units = m
    }, options );
```

> Redundant comments. For example, this tell me nothing:

> ```js
     // ccwArrowNotAtMax
      ccwArrowNotAtMax,
```

It seems like using options has a similar-looking redundancy, but perhaps this is superior:
```js
{ ccwArrowNotAtMax: ccwArrowNotAtMax }
```

I'll take a look through and see if I can resolve the issues from the previous comment.

**Comment by pixelzoom** [comment]
Imo, this would be clearer, with "doc here" for options copied down from params.

```js
/**
 * @param {BendingLightModel} bendingLightModel - main model of the simulations
 * @param {function} laserTranslationRegion - region that defines laser translation
 * @param {function} laserRotationRegion - region that defines laser rotation
 * @param {Object} [options]
 */
function BendingLightView( bendingLightModel, laserTranslationRegion, laserRotationRegion, options ) { 

options = _.extend( {
   clampDragAngle: 0, // {number}  doc here
   clockwiseArrowNotAtMax: false, // {boolean} doc here
   ccwArrowNotAtMax: false, // {boolean} doc here
   centerLeftOffset: 0, // {number} doc here
   verticalOffset: 0, // {number} doc here
   occlusionHandler: null // {function} doc here
}, options );
...
```

**Comment by samreid** [comment]
That looks nice, let's go for it!

**Comment by samreid** [comment]
As I proceed with this, I wanted to jot down 3 related questions (for @pixelzoom or other interested parties):

1. How many required constructor/function parameters is too many?  Is it context-sensitive?
2. Should we formalize a rule for our style guide about limiting the number of parameters?
3. Should we formalize a lint rule for limiting the number of parameters?

**Comment by samreid** [comment]
It looks like eslint already has a max-params rule: http://eslint.org/docs/rules/max-params.html

**Comment by samreid** [comment]
I think I'll move the above questions to chipper and just focus on bending light for this issue.

**Comment by samreid** [comment]
I followed the recommendation in https://github.com/phetsims/bending-light/issues/315#issuecomment-162043406 with the following exceptions:
1. LaserImage is still a required parameter--will be discussed/addressed as part of https://github.com/phetsims/bending-light/issues/312
2. The types for many of the things were {function} instead of {number}.  Not a problem, just wanted to point it out in case it changes any conclusions reached by @pixelzoom.

@pixelzoom can you take a look and let me know if you recommend further work here?

**Comment by samreid** [comment]
Thanks @pixelzoom, your additional fixes look great.
