### ISSUE TITLE
Make it easier to grab and rotate the laser in the prism screen.

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#320]
Move the button forward a bit, to match the other screens, or even further forward.  Then adjust the touch region for translation and rotation to make it easier to grab to rotate and translate.

**Comment by samreid** [comment]
Increased touch areas above, looks like this now:
![image](https://cloud.githubusercontent.com/assets/679486/11576132/daa0d6a6-99d1-11e5-9c20-0be74fedee5c.png)

I think this will work nicely, but I should still test on an iPad before closing or getting @ariel-phet or @arouinfar to test.

**Comment by samreid** [comment]
Touch area is not being respected here, instead we should augment the rotation touch area.

**Comment by samreid** [comment]
Fixed above, @ariel-phet tested it on iPad and says it is good.

@samreid just needs to test that the regions in Screen 1 and 3 are undisturbed.

**Comment by arouinfar** [comment]
@samreid, I'll defer to @ariel-phet's judgement when it comes to the touch area. If it's working well for him, then it's good enough for me.

**Comment by samreid** [comment]
Looks great on iPad3, closing.
