### ISSUE TITLE
Developer testing (Part III)

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#324]
Before moving to dev testing, I would like to spend some time testing Bending Light on 1-2 platforms.

**Comment by samreid** [comment]
Here's the newly published version I'll be testing:

http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.47/bending-light_en.html

**Comment by samreid** [comment]
Testing on Chrome, seems fine.  Testing fuzz test on Chrome on Firefox seems fine.

Wondering if QA credits are right... @ariel-phet can you comment?

**Comment by samreid** [comment]
The angle is shown if the light is intercepted before the interface:

![image](https://cloud.githubusercontent.com/assets/679486/11723157/03283f58-9f2a-11e5-9fe3-f0ddaf7d003a.png)

@ariel-phet do you want to fix and move to version dev.48?

**Comment by samreid** [comment]
Protractor icon still looks crummy at a few sizes on firefox:
![image](https://cloud.githubusercontent.com/assets/679486/11723219/60626374-9f2a-11e5-8a33-10352ad3b0ea.png)

**Comment by samreid** [comment]
I finished broader manual testing on firefox, no other problems noted.  Reassigned to @ariel-phet to decide if we should spend time investigating the above issues, or move forward with a dev test.

**Comment by samreid** [comment]
I'll leave the "high-priority" label on for @ariel-phet since he wanted to get this done today.

**Comment by ariel-phet** [comment]
@samreid - protractor looks fine to me on FF as we discussed and I think it is appropriate to show the incident angle.

**Comment by samreid** [comment]
In the above commit, I Adjusted environment panel margin so that prisms panels will left align and published here:

http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.48/bending-light_en.html

@ariel-phet can you take a look?

**Comment by samreid** [comment]
New credits in http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.49/bending-light_en.html

**Comment by samreid** [comment]
@samreid needs to double check before giving to @ariel-phet

**Comment by samreid** [comment]
Seems good to me, @ariel-phet can you double check that all of our changes are looking good before sending to dev testing.

**Comment by ariel-phet** [comment]
all looks good. Closing
