### ISSUE TITLE
attach probes to right side of meters?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#325]
The probes for the Intensity and Time meters are currently attached to the *left* side of the meters. Given that there's a lot of space immediately to the right of the toolbox, users will probably put the meters there. That results in the wires going behind the meters, as in the screenshot below. Wouldn't it be better to attach the wires to the *right* side of the meters?

![screenshot_93](https://cloud.githubusercontent.com/assets/3046552/11723575/5d11c334-9f2c-11e5-92c6-6be73bbe35ff.png)

**Comment by samreid** [comment]
Here is my expectation of a typical use case, in which it seems like it is nice for the wires to attach at the left (sorry for the widescreen recording, but the same argument applies at nominal aspect ratio):
![untitled 2](https://cloud.githubusercontent.com/assets/679486/11724503/ae853a66-9f31-11e5-82d9-373bf458f38e.gif)

**Comment by pixelzoom** [comment]
My use may not be typical, but that's not how I used these tools.  I pulled the tools out into the space to the right of the toolbox, then started to move the probes. Perhaps I was attracted by the large amount of blank space to the right of the toolbox.

**Comment by samreid** [comment]
@ariel-phet @arouinfar what do you think about this?  Have we done interviews that might inform this decision?

**Comment by pixelzoom** [comment]
Also note that in your use case, on tablets, the body (and readout) of the meter will be obscured while a right-handed user is dragging the meter.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/bending-light/issues/325#issuecomment-163711476, @samreid must be using a very wide (not typical) screen.  Here's what happens in that same scenario with a typical play area size.  The Time meter ends up behind the controls panel, then snaps to the left when release, covering the probes, see screenshot below.    If this is a typical use case, then you have layout problems.

![screenshot_96](https://cloud.githubusercontent.com/assets/3046552/11724832/b1288442-9f33-11e5-9a6b-02e255ac6688.png)

**Comment by samreid** [comment]
Thanks @pixelzoom, this is a good point.  Let's see what @arouinfar and @ariel-phet think.

**Comment by pixelzoom** [comment]
Another problem with the scenario in https://github.com/phetsims/bending-light/issues/325#issuecomment-163711476...  The only time that the meter body & probe move together is when they are dragged out of the toolbox.  After that, the body and probe(s) move independently.
Since the laser will never enter the space to the right of the toolbox, I would think that the user will eventually figure out that to the right of the toolbox is a good place to "park" the meter bodies.  Then they'll move the probes around as the laser beam changes position.

**Comment by pixelzoom** [comment]
Another problem with the scenario in https://github.com/phetsims/bending-light/issues/325#issuecomment-163711476...  The only time that the meter body & probe move together is when they are dragged out of the toolbox.  After that, the body and probe(s) move independently. Since the laser will never enter the space to the right of the toolbox, I would think that the user will eventually figure out that to the right of the toolbox is a good place to "park" the meter bodies.  Then they'll move the probes around as the laser beam changes position.  If that's the case, then it would make more sense to have the probes attached to the right edge of the meter bodies.

**Comment by samreid** [comment]
We could have the wires connect to the center of the meter body, with no spline control points, so it will look like it comes out of any part of the body.  Then it would accommodate either use case.

**Comment by ariel-phet** [comment]
@arouinfar's call

**Comment by arouinfar** [comment]
@pixelzoom makes some good points. This is typically how I use the probes. I always move them to the right side of the screen because the wire is on the left.
![image](https://cloud.githubusercontent.com/assets/8419308/11725517/67c48b8a-9f37-11e5-937c-30faccbcb50f.png)

>Since the laser will never enter the space to the right of the toolbox, I would think that the user will eventually figure out that to the right of the toolbox is a good place to "park" the meter bodies. Then they'll move the probes around as the laser beam changes position.

I agree with @pixelzoom that this seems like a natural place to park the tools.

>We could have the wires connect to the center of the meter body, with no spline control points, so it will look like it comes out of any part of the body. Then it would accommodate either use case.

@samreid's solution would give users more flexibility, but I'm worried that it would look a bit too strange. If this is a quick thing to try, I'd like to see it before making the final decision. If not, we can simply relocate the probes to the right side of the tool body.

**Comment by samreid** [comment]
Things to decide:
1. Should the probe start on the left or right of the body?
2. Should wire body attachments have spline control points, or flexible?
3. If the body doesn't have a fixed attachment point, which direction should the control points on the probes lead?

Perhaps we should commandeer some <5 minutes from CCK design meeting to discuss these issues.

**Comment by arouinfar** [comment]
> Perhaps we should commandeer some <5 minutes from CCK design meeting to discuss these issues.

I'd be okay with that if @ariel-phet is.

**Comment by arouinfar** [comment]
As decided in the quickie design meeting with @ariel-phet, @kathy-phet, @samreid and @arouinfar, let's anchor the wires on the right side of the meter bodies and flip the icon in the toolbox to match.

**Comment by samreid** [comment]
After this, I'll create a dev testing task.

**Comment by samreid** [comment]
Published here: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.50/bending-light_en.html

**Comment by samreid** [comment]
I spot tested dev.50 and it seemed OK.  @ariel-phet can you test it for a minute or two before giving it to the dev testers?  I'll create a tasks issue as well.

**Comment by ariel-phet** [comment]
Looks good, closing
