### ISSUE TITLE
Move the hot spot on sensors probe node and wave sensor

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#326]
So the hot spot is on the body, not the probe.

**Comment by samreid** [comment]
Fix published here for testing: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.51/bending-light_en.html

**Comment by arouinfar** [comment]
Looks good to me! Thanks @samreid.

**Comment by samreid** [comment]
Excellent, thanks! Closing.
