### ISSUE TITLE
All of wave does not terminate when measured

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/bending-light#328]
Test device: Mac, personal

Operating System: OS X 10.10.5

Browser: Safari 9.0.2 (10601.3.9)

Problem description: Not all of the wave is terminated when the intensity is measured. Is this a design decision? All is terminated for the ray.

Steps to reproduce: Drag generator as close to the horizontal as possible with wave mode. Measure intensity of entire light (i.e. it will measure 100%). 

Severity:

Screenshots: 
![screen shot 2015-12-16 at 4 10 31 pm](https://cloud.githubusercontent.com/assets/12610678/11856695/05486002-a410-11e5-873d-962d7d60c405.jpg)

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.51/bending-light_en.html
Version: 1.0.0-dev.51 2015-12-10 22:05:11 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
Language: en-us
Window: 1238x660
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.6.33)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"60075be9","branch":"master"},"babel":{"sha":"469a6f46","branch":"master"},"bending-light":{"sha":"007d4f70","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"d18a2538","branch":"master"},"dot":{"sha":"24f07fa0","branch":"master"},"joist":{"sha":"f73eef15","branch":"master"},"kite":{"sha":"a4907ccc","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"d712ace0","branch":"master"},"scenery":{"sha":"98ea2eeb","branch":"master"},"scenery-phet":{"sha":"a62aafce","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"1b39dfc5","branch":"master"},"tandem":{"sha":"87f3d2ab","branch":"master"}}

**Comment by samreid** [comment]
This problem was known to me, though I don't recall if I discussed it explicitly with @ariel-phet and @arouinfar.  Visualizing the alternative (arresting the incident ray if that outer triangle hits the sensor), I am not sure which option is superior.  @arouinfar and @ariel-phet what do you think?

**Comment by ariel-phet** [comment]
I think the ray and wave behavior match acceptably in this case. A couple comments:

1. This is definitely a corner case, since you have to work hard to get in to the situation
2. Mostly people will tend to use the probe more centered on the ray wave, so this case is unlikely to come up during normal use.

Good observation from @elisemorgan, but lets leave as is.
