### ISSUE TITLE
Speed sensor boundaries for read out

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#33]
Speed sensor boundaries to be adjusted for read out in wave mode. Please see image below.

![image](https://cloud.githubusercontent.com/assets/3147499/7407357/c047dafa-ef2e-11e4-8151-263619615148.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
