### ISSUE TITLE
Index of refraction slider resizes box

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/bending-light#333]
In stringTest=double and stringTest=rtl,  moving the index of refraction slider all the way to the right causes the box to resize slightly on the right edge.

[Index_resize_win8_Chrome.zip](https://github.com/phetsims/bending-light/files/68804/Index_resize_win8_Chrome.zip)

Issue occurs on all 3 screens.

**Comment by amyh-phet** [comment]
Issue also occurs with stringTest=X in Win 8 FF.   Wben moving slider to the left, box expands slightly to the right.

**Comment by amyh-phet** [comment]
Issue also occurs with stringTest=X on Win 8 with FF.   The resizing only happens in the lower part of the screen, but it occurs on all 3 screens.
[Index_resize_win8_FF_stringTest=X.zip](https://github.com/phetsims/bending-light/files/68839/Index_resize_win8_FF_stringTest.X.zip)

**Comment by arouinfar** [comment]
Also observed in OSX 10.11.2 in all browsers.

**Comment by samreid** [comment]
Fixed above, the change was minor and non-intrusive.  Spot testing on 1 platform will confirm the change.

**Comment by arouinfar** [comment]
Looks great! Closing.
