### ISSUE TITLE
Panel size for index of refraction- Prism screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/bending-light#334]
In stringTest=long, the index of refraction  panels seem to resize strangely on the Prism screen.  The panels seem much larger than needed to accommodate the strings, making the lower panel go off screen. 
![win_8_ie_stringtest long_panel_size](https://cloud.githubusercontent.com/assets/13650180/11939550/100827ce-a7e0-11e5-9685-1b28d731f513.png)

Not sure that this is a huge concern as I'm not sure strings will ever be this long, but the panel behavior seems strange.

**Comment by amyh-phet** [comment]
Observed similar behavior on Mac OS X 10.9.5 on Intro and More Tools screens.
![mac_os10 9 5 stringtest long_intro](https://cloud.githubusercontent.com/assets/13650180/11940057/5304b8a0-a7e3-11e5-9036-10eb95603b08.png)
![mac-os10 9 5_stringtest long_tools](https://cloud.githubusercontent.com/assets/13650180/11940067/6756c474-a7e3-11e5-943b-b1940d1861ed.png)

**Comment by arouinfar** [comment]
While stringTest=long is not really a realistic scenario, I find it strange that the panels expand so much. In general, panels should only expand up to 50px before text is scaled down. I wonder if there's a minimum allowed font size that competes with maximum panel width.

**Comment by samreid** [comment]
The (often hidden) "what is n?" text was throwing off the layout.  I've constrained the width and everything appears OK.  I'll push changes to the 1.0 branch and master and this will require a spot test on 1 platform.

**Comment by samreid** [comment]
Fixed above.

**Comment by arouinfar** [comment]
It looks like the panel is resizing appropriately in rc.2, so I'll go ahead and close this issue. Good catch @amyh-phet, and thanks @samreid!
