### ISSUE TITLE
Publish 1.0.0

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#336]
RC2 testing was good, this sim is ready to publish.

**Comment by samreid** [comment]
OK I ran grunt deploy-production and the sim appeared at http://phet.colorado.edu/sims/html/bending-light/latest/

Next step is for @arouinfar to make it visible on the website and add any appropriate website metadata.

**Comment by arouinfar** [comment]
@samreid @ariel-phet Bending Light is now live!!
