### ISSUE TITLE
Create a new screenshot

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#337]
Some visual elements have changed size since the last screenshot.  I considered just "sticking with it" since it would be OK as a thumbnail, but for consistency I decided to create a new screenshot since we may use it for other purposes in the future.  For #336

**Comment by samreid** [comment]
With the smaller intensity probe, the rest of the configuration looks odd (light spilling out of the probe), so I'm going to move a few other things around as well.

**Comment by samreid** [comment]
Here's a sneak peek of the new screenshot.  @arouinfar please let me know if you recommend any changes:

![image](https://cloud.githubusercontent.com/assets/679486/11981153/379e7d82-a95d-11e5-8ef7-65d7ca9eae0f.png)

**Comment by samreid** [comment]
Committed above, reassigning to @arouinfar for review.

**Comment by samreid** [comment]
This new screenshot does not do too good of a job showing the transparency of the transmitted and reflected beams.  Perhaps we can do better?

**Comment by samreid** [comment]
I've improved the screenshot in the above commit, here's a visual difference:

https://github.com/phetsims/bending-light/commit/e3ef9d43185c872f36d97b5a56b4ba534885e81f

This seems like it solves the problems in the previous version, and I just had the light extend across the probe, and it doesn't look too odd.  It would still be good for @arouinfar to double check it though.

**Comment by samreid** [comment]
Moving forward with publishing in #336...

**Comment by arouinfar** [comment]
Looks good @samreid. Closing.
