### ISSUE TITLE
replace LaserNode with scenery-phet.LaserPointerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#339]
... as recommended in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2.

When `options.hasKnob`, you'll need to add the knob as a decoration, as you've done for the prisms that can be rotated (see PrismNode). 

Remember to delete related images and assets.

**Comment by samreid** [comment]
@ariel-phet this issue could be given to another developer if desired--not too much bending-light knowledge required.  Can you help prioritize and assign?  The main point is to use the new scenery-phet LaserPointerNode @pixelzoom developed for Models of the Hydrogen atom in Bending Light instead of custom raster images.

**Comment by ariel-phet** [comment]
@samreid since bending light is published, this seems fairly lowly priority, agreed?

**Comment by samreid** [comment]
Yes, it would not significantly change the user experience, it is mainly an internal maintenance issue.

**Comment by ariel-phet** [comment]
Ok, going to clear assignee for the moment, will revisit when appropriate. This sim is actually a very good candidate for phet-io work at some point, to see if we can deal with a complicated sim. I am guessing the work could be wrapped into that effort.

**Comment by samreid** [comment]
Thanks to the changes in the referenced issues, this has been completed.  @pixelzoom do you have time for a quick review?  If not, we may need to leave this for a "review right before publication" sort of thing.

**Comment by pixelzoom** [comment]
Changes and behavior in bending-light look good, so I'll go ahead and close this.  But note the regression in https://github.com/phetsims/scenery-phet/issues/660#issuecomment-770478770, which does not appear to affect bending-light, since its LaserPointerNode uses the default `hasGlass: false`.
