### ISSUE TITLE
"Time - graph plotter" sensor boundaries to be adjusted

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#34]
Time - graph plotter sensor boundaries to be adjusted for read out in wave mode. Please see image below.
The black probe is reading the wave although its outside wave and white probe is not reading the wave although its inside the wave.

![image](https://cloud.githubusercontent.com/assets/3147499/7407426/6f15f634-ef2f-11e4-9041-e884dfc2ff6d.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing.
