### ISSUE TITLE
Several strings are no longer used

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#340]
In working on #50 I discovered that several strings in Bending Light are unused.  They should be removed and perhaps we should publish a patch version so the translated strings in babel are correct as well.

**Comment by samreid** [comment]
I removed the unused strings in master in the above commit.  Still need to backport this to the published branch and redeploy.

**Comment by samreid** [comment]
@ariel-phet can you help prioritize this?  There were 10 strings appearing in the file that don't appear in the sim.  Also, even though this problem was my fault, it doesn't require any knowledge specific to bending light, so you could delegate to someone else if you wish.  The problem shouldn't occur in future sims since we have added a check for this in the code review checklist.

**Comment by ariel-phet** [comment]
@jbphet could you take care of this? much appreciated

**Comment by jbphet** [comment]
I started working through this, but after digging into it I started to believe that Rosetta isn't presenting unused English strings to the users of the translation utility, see
https://github.com/phetsims/tasks/issues/460#issuecomment-170680504.  Unless my conclusions are incorrect, I think it makes this issue about doing a maintenance release to clean up strings rather unnecessary.  I've already propagated the fixes to the strings to the 1.0 branch, so perhaps we should just leave it at this.  

We probably want to revert the version number bump if we decide to just leave this as is.

Assigning back to @samreid.  If he concurs that a maintenance release isn't really warranted, he should manually revert the bump of the version number and close this issue.

**Comment by samreid** [comment]
I agree the main reason for republishing was to prevent showing unused strings to the translator.  According to @jbphet's conclusions as well as the Rosetta documentation, the string keys are extracted from the used keys in the simulation.

**Comment by samreid** [comment]
There is trouble in deploying a maintenance release of a translated sim, see https://github.com/phetsims/beers-law-lab/issues/147.

We should not proceed until that problem is solved. And I'm happy to leave this as-is since (a) the unused strings don't appear in the HTML file and (b) the unused strings are not presented to the translator.  @jbphet should we confer with other team members or just revert the version and close issue?

**Comment by jbphet** [comment]
Based on today's discussion at dev meeting, I have reverted the version number and am closing this issue.
