### ISSUE TITLE
Migrate Java strings

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#341]
From https://github.com/phetsims/bending-light/issues/50 we should migrate the Java strings to Babel.

**Comment by ariel-phet** [comment]
@samreid note that a number of translations have occurred already. I would highly suggest that when you do this migration, only now move over strings for locales which have NOT yet been translated (we would not want to wipe out or change any work done in the current translations)

**Comment by samreid** [comment]
Sounds great @ariel-phet, will do.

**Comment by samreid** [comment]
I know some key names have changed during the port, so I compared them to see if it is worth any effort here.  Here are the shared keys:

> ["intro", "air", "water", "glass", "custom", "prisms", "mysteryA", "mysteryB", "material", "miss", "indexOfRefraction", "objects", "environment", "intensity", "ray", "wave", "diamond", "time", "moreTools"]

This is 19/33 keys that will be portable.

**Comment by samreid** [comment]
Also, based on previous discussions it seemed like it would be nice but not essential to filter out the unused keys.  I do not have time at the moment to write a robust reusable filter so I am planning to proceed with just moving all of the strings including the unused ones.

**Comment by samreid** [comment]
Pushed to babel above.  I'll create a chipper or issue about filtering the unused strings.
