### ISSUE TITLE
User reported issue: wrong reflective ray angle with window resize

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/bending-light#343]
Reported via phethelp 1/20/2016. @phet-steele can you attempt to reproduce?

"The reflective ray should have the same angle as the incident ray. I obtain the right angle if the window is small but with a large window it does not do the right reflection.
I use the last version of Firefox on Linux and the html5 simulation."

"It seems to work fine if screen width is 452 or less OR if screen height is 296 or less but if screen width is higher than 452 and screen height is higher than 296 the reflective ray is not shown with the right angle."

**Comment by oliver-phet** [comment]
User screenshot:
![capture-1](https://cloud.githubusercontent.com/assets/5090275/12489603/5bb260ca-c02e-11e5-977e-de772ba9f18f.png)

**Comment by ariel-phet** [comment]
@oliver-phet notice he said "on Linux"....

**Comment by oliver-phet** [comment]
Yes, I saw that he was on Linux. Does that mean we aren't investigating?

**Comment by ariel-phet** [comment]
@oliver-phet We should investigate and see if we can reproduce, but if it only happens on Linux I think we have to tell the user that we don't officially support Linux in HTML5 (not part of our test matrix so I don't think we can claim to officially support).

@phet-steele is looking into it.

**Comment by phet-steele** [comment]
@ariel-phet @oliver-phet I could not duplicate this on any Windows 8.1 browsers. How much more time should be spent, should I at least try on OS X?

**Comment by ariel-phet** [comment]
@phet-steele yes please try on OS X (but only FF).

**Comment by phet-steele** [comment]
@ariel-phet nothing reproduced.

**Comment by ariel-phet** [comment]
Thanks @phet-steele!

@oliver-phet lets go ahead and email back the user and let them know this appears to be a linux specific bug, and although many of our HTML5 resources run well on Linux, we do not "officially" support it (and cannot afford to do to the limited number of Linux users and the cost of testing/maintenance). Please close this issue after emailing.

**Comment by samreid** [comment]
One last thought: if you could ask them to open the console, there may be some information there that could help us understand the underlying problem.  Even though we do not support Linux, this information (if present) may still help us make the code more robust.

**Comment by oliver-phet** [comment]
Email to user sent requesting console output.

**Comment by ariel-phet** [comment]
good thought, thanks @samreid

**Comment by oliver-phet** [comment]
Still no response from user. Closing for now and will reopen if we receive a response.

**Comment by oliver-phet** [comment]
We had a second report of this bug from another Linux user. Asking for console output.
