### ISSUE TITLE
Edge 25 normal lines on prisms screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#344]
Probably this: https://github.com/phetsims/scenery/issues/510, but the normal lines on the Prisms screen show as solid. @samreid, note the normal lines on other screens appear correctly.

![normalprisms](https://cloud.githubusercontent.com/assets/5863899/13262548/a67ec3f6-da22-11e5-825d-5d3fd4212190.PNG)

Seen on the production version and @jonathanolson's maintenance release (2/22). Discovered during phetsims/tasks/issues/523

**Comment by jonathanolson** [comment]
@ariel-phet and @samreid, any objections to patching https://github.com/phetsims/scenery/issues/510 also for this maintenance release?

**Comment by samreid** [comment]
I can't think of any reason not to patch https://github.com/phetsims/scenery/issues/510 while we are here.

**Comment by ariel-phet** [comment]
no objections.

**Comment by phet-steele** [comment]
@jonathanolson fixed here http://www.colorado.edu/physics/phet/dev/olsonjb/maintenance2/bending-light_en.html
