### ISSUE TITLE
User reported issue: not all components visible

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/bending-light#346]
Hi,
 
I am trying this simulation at work using the live link you provided in an earlier email. The Prism screen will not load at all. This is what I see when I click on the Intro icon:
 
![image002](https://cloud.githubusercontent.com/assets/5090275/15941698/95338526-2e3e-11e6-8bb9-6c66a936bb85.jpg)
 
This is what I see when I click on the More Tools screen:
 
![image005](https://cloud.githubusercontent.com/assets/5090275/15941701/9874d744-2e3e-11e6-95eb-3667eee85ba5.jpg)
 
Here is the debugging information:
Report a Problem
Please copy and paste the information below into an email to phethelp@colorado.edu, and then fill in the blanks.

Test device: PC
 
Operating System: Windows 7
 
Browser:  IE 10
 
Problem description: As discussed and noted above.
 
Steps to reproduce: Click on live link and then click on any of the three icons (Intro, More Tools, Prisms)
 
Severity: Cannot use Sim
 
Screenshots: (Above)
 
Troubleshooting information (do not edit):
Name: ‪Bending Light
URL: http://phet.colorado.edu/sims/html/bending-light/latest/bending-light_en.html
Version: 1.0.4 2016-06-05 16:56:09 UTC
Features missing: touch, webgl, fullscreen
Flags: msPointerEnabled
User Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; InfoPath.3)
Window: 1440x845
Pixel Ratio: 1/1
WebGL: unsupported
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"60075be9","branch":"HEAD"},"babel":{"sha":"3ff83b7e","branch":"master"},"bending-light":{"sha":"4ecea985","branch":"HEAD"},"brand":{"sha":"156c1ac9","branch":"HEAD"},"chipper":{"sha":"df033891","branch":"HEAD"},"dot":{"sha":"24f07fa0","branch":"HEAD"},"joist":{"sha":"17c5a281","branch":"HEAD"},"kite":{"sha":"a4907ccc","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d71dc9ef","branch":"HEAD"},"scenery":{"sha":"ad956984","branch":"HEAD"},"scenery-phet":{"sha":"a62aafce","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"1b39dfc5","branch":"HEAD"},"tandem":{"sha":"87f3d2ab","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
@oliver-phet - we no longer support IE 10, please tell customer to upgrade browser or use chrome

**Comment by oliver-phet** [comment]
User emailed.
