### ISSUE TITLE
Testing with mock-up overlay

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#35]
There are several positional changes and size changes to be done across all three sims to replicate the mock-ups. Please refer to the attached images.

Intro sim - 
![image](https://cloud.githubusercontent.com/assets/3147499/7407580/ae029ae4-ef31-11e4-9f4c-a312ef535406.png)

Prisms sim -
![image](https://cloud.githubusercontent.com/assets/3147499/7407584/b9c0f2c2-ef31-11e4-870b-675345b4df71.png)

More tools sim - 
![image](https://cloud.githubusercontent.com/assets/3147499/7407590/c4c3c8a2-ef31-11e4-9615-0e44be0ef9c4.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
There are still some minor issues that need to be corrected. Please try to match them as closely as possible.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing.
