### ISSUE TITLE
Wave mode not captured by screenshots

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#350]
The screenshot feature in the PhET menu. Ray mode is fine.
![-bending light- screenshot 3](https://cloud.githubusercontent.com/assets/5863899/17440827/8b30d16c-5aeb-11e6-9ff2-d693c9baf1c6.png)

**Comment by samreid** [comment]
Which browsers exhibit the problem?  Do any browsers do the screen shot properly?

**Comment by phet-steele** [comment]
All OSX 10.11.6 browsers have the issue, then I tried Win 10 Chrome and iOS 10 Beta which also had the problem.

**Comment by phet-steele** [comment]
@samreid @jbphet this issue does NOT exist on master.

**Comment by phet-steele** [comment]
Assigning to @ariel-phet for the reasons described in phetsims/neuron/issues/125:

>I just tested this on master, and the screenshot feature works fine. Probably the easiest way to resolve this issue would be to just do a new RC branch and release off of master. This would require roughly an hour or two of developer time and a fair amount of QA time to do a full test cycle, so I will assign to @ariel-phet to decide whether this should be done.

**Comment by ariel-phet** [comment]
Yes @phet-steele , lets go ahead and get both of these sims in the QA testing queue. Priority will be below sims we want to have first release of (so for instance if rutherford or charges and fields or such is being tested).

**Comment by samreid** [comment]
I'll create a new issue for publishing a new version of the sim.

**Comment by samreid** [comment]
Will be fixed in #351

**Comment by phet-steele** [comment]
@samreid this has been working on our supported platforms.
