### ISSUE TITLE
adjust touchArea options for HSlider thumb

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#355]
In https://github.com/phetsims/sun/issues/254, the touchArea defaults for HSlider thumb were changed so that they default to pixels, not a percentage of the thumb size.  Sims that use HSlider's `thumbSize` option will therefore need to also specify `thumbTouchAreaXDilation` and `thumbTouchAreaYDilation`.

**Comment by samreid** [comment]
There is a bit of pointer area overlap in the medium control panels:

![image](https://cloud.githubusercontent.com/assets/679486/18117207/59b82698-6f0a-11e6-87fe-ce1807c52c68.png)

**Comment by samreid** [comment]
Reduced from 11 to 8 and it seems better:

![image](https://cloud.githubusercontent.com/assets/679486/18117250/a19aa99a-6f0a-11e6-9ee6-728646d12589.png)

**Comment by samreid** [comment]
Fixed, closing.
