### ISSUE TITLE
PrismsModel is not instantiated on demand

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#356]
See PrismScreen constructor:

```js
  function PrismsScreen( tandem ) {

    var options = {
      name: prismsString,
      homeScreenIcon: new Image( iconImage ),
      navigationBarIcon: new Image( navbarIconImage ),
      tandem: tandem
    };

39  var prismModel = new PrismsModel();

    Screen.call( this,
42    function() { return prismModel; },
      function( model ) { return new PrismsView( model ); },
      options );
  }
```

Note that `PrismsModel` is instantiated in the constructor (line 39), instead of in the `createModel` function argument (line 42)  to `Screen`.   This doesn't match the pattern used throughout PhET sims.  Is there a reason for this deviation, or is it accidental?

**Comment by pixelzoom** [comment]
Unless there's a reason to do things differently, the model should be instantiated in the `createModel` argument, like this:

```js
function PrismsScreen( tandem ) {

  var options = {
      name: prismsString,
      homeScreenIcon: new Image( iconImage ),
      navigationBarIcon: new Image( navbarIconImage ),
      tandem: tandem
    };

  Screen.call( this,
    function() { return new PrismsModel(); }, 
    function( model ) { return new PrismsView( model ); }, 
    options );
}
```

**Comment by samreid** [comment]
Yes, this looks like a problem, I'll work on it this week.

**Comment by pixelzoom** [comment]
FYI, similar problems in other sims: https://github.com/phetsims/neuron/issues/129, https://github.com/phetsims/resistance-in-a-wire/issues/76.

**Comment by samreid** [comment]
Those problems will interfere with the loading bar (if nothing else), we should address them.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/bending-light/issues/356#issuecomment-245826609, @samreid said:
> Those problems will interfere with the loading bar (if nothing else), we should address them.

**Comment by samreid** [comment]
Fixed above.  I realized that the loading bar now goes by screen, so this would not have interfered.  But if we break up the loading bar to load models and views separately, then this could have shown up as odd.

I tested the app by launching it after making this change, and all seems well.

Closing.
