### ISSUE TITLE
Single ray switch shows extended length of ray in firefox

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#36]
In Firefox browser, the single ray switch shows extended length of ray. Please see image below

![image](https://cloud.githubusercontent.com/assets/3147499/7407744/da207776-ef32-11e4-9b66-9fc8ea1ca718.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
I am still seeing this issue in firefox.

**Comment by kmsravindra** [comment]
Updated comment - This issue #36 seems to be happen only on Windows8.1 - firefox combination and doesn't happen on other OS platforms.

**Comment by ChandrashekarBemagoni** [comment]
This commit will fix the issue: https://github.com/phetsims/bending-light/commit/02dd3b20e2455dbb40071a63574e98c2084dfe3d. Assigning to  @kmsravindra  for verification

**Comment by kmsravindra** [comment]
Looks good. Closing.
