### ISSUE TITLE
1.1.0 rc.1 String Testing 

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/bending-light#360]
String Testing Issues

Browsers: Chrome, Edge, Firefox

OS: Windows 10

The double string test results in three separate bounding issues in the Prisms and More Tools screens 
![bending light stringtest double 1](https://cloud.githubusercontent.com/assets/22551096/19578190/e8027602-96d7-11e6-9f69-cf623a83e876.PNG)
Frequency bounds outside of the box
![bending light stringtest double 3](https://cloud.githubusercontent.com/assets/22551096/19578248/1aacc792-96d8-11e6-8377-563c43a3603a.PNG)

![bending light stringtest double 2](https://cloud.githubusercontent.com/assets/22551096/19578249/1f4cf7ae-96d8-11e6-8c39-a8acb8b60c20.PNG)
And the speed of the wave on the sensor bounds significantly out of the box as well. This incorrect bounding for the speed sensor is also present for the long stringtest. 

No other stringtests brought up any issues.

Related to: https://github.com/phetsims/tasks/issues/682

Debug Information

Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.1.0-rc.1/bending-light_en.html
Version: 1.1.0-rc.1 2016-08-22 20:48:08 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"5e625a61","branch":"master"},"bending-light":{"sha":"09962afa","branch":"HEAD"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"136b1d30","branch":"HEAD"},"dot":{"sha":"6e8a26f2","branch":"HEAD"},"joist":{"sha":"ab5582ab","branch":"HEAD"},"kite":{"sha":"88f0c3a0","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"scenery":{"sha":"0ab22ac3","branch":"HEAD"},"scenery-phet":{"sha":"04cec216","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"061f2ea9","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

**Comment by samreid** [comment]
Unassigning until I'm devoting time to bending light.

**Comment by ariel-phet** [comment]
@EthanWJohnson note that for these types of strings (readouts) a longer string will actually be very unlikely to occur (unless someone types out the abbreviation for the units as a full word such as "nanometers"). However, we trust our translators not to do those types of things.

Closing
