### ISSUE TITLE
Reflected Wave Doesn't Render

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/bending-light#361]
Test device: Yvgotsky

Operating System: Chrome.OS Snow

Browser: Chrome

The reflected wave, in wave mode on the intro and more tools screen, doesn't properly render, instead displaying a black box 

![bending light screenshot 1](https://cloud.githubusercontent.com/assets/22551096/19663240/69bc1400-99f8-11e6-9eb2-84255babfbdf.png)

This issue occurs on the Snow firmware but does NOT occur on Peppy; their versions are both up to date otherwise. This also occurs on the published version on the website.

Related To: https://github.com/phetsims/tasks/issues/682

Troubleshooting information (do not edit):
Name: ‪Bending Light‬
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.1.0-rc.1/bending-light_en.html
Version: 1.1.0-rc.1 2016-08-22 20:48:08 UTC
Features missing: touch
User Agent: Mozilla/5.0 (X11; CrOS armv7l 8530.96.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.154 Safari/537.36
Language: en-US
Window: 1366x655
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 96)
Max viewport: 8192x8192
OES_texture_float: false
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"5e625a61","branch":"master"},"bending-light":{"sha":"09962afa","branch":"HEAD"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"136b1d30","branch":"HEAD"},"dot":{"sha":"6e8a26f2","branch":"HEAD"},"joist":{"sha":"ab5582ab","branch":"HEAD"},"kite":{"sha":"88f0c3a0","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"scenery":{"sha":"0ab22ac3","branch":"HEAD"},"scenery-phet":{"sha":"04cec216","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"061f2ea9","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
Marking priority deferred for the moment, we need to find a chunk of time for @samreid to work on this sim

**Comment by samreid** [comment]
The reflection is rendering ok on my mac chrome at the moment:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/679486/189269830-6e6e7986-98f1-4563-926e-90a00e97601b.png">

We can reopen if we see errant platforms in the dev test, closing for now.
