### ISSUE TITLE
User Reported issue: inaccurate time oscilloscope 

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/bending-light#364]
> Test device: Compaq Laptop
> 
> Operating System: Windows 7
> 
> Browser: Google Chrome
> 
> Problem description: In More Tools menu, Time oscilloscope shows
> inaccurate wave speed when comparing speed 1C and 0,75C. The
> Oscilloscope show same speed waves.
> 
> Steps to reproduce: Set wave probe to in air ray and the other to in
> water ray, the time oscilloscope will show sama speed of waves.
> 
> Severity: Fatal, since speed difference wil bend the ray.
> 
> Screenshots: attached
> 
> Troubleshooting information (do not edit):
> Name: ‪Bending Light‬
> URL: https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_en.html
> Version: 1.1.0 2016-10-26 20:19:52 UTC
> Features missing: touch
> User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36
> (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
> Language: en-US
> Window: 1304x653
> Pixel Ratio: 1/1
> WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
> GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
> Vendor: WebKit (WebKit WebGL)
> Vertex: attribs: 16 varying: 9 uniform: 253
> Texture: size: 4096 imageUnits: 16 (vertex: 4, combined: 20)
> Max viewport: 4096x4096
> OES_texture_float: true
> Dependencies JSON:
> {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"a106d6f8","branch":"master"},"bending-light":{"sha":"05192111","branch":"HEAD"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"136b1d30","branch":"HEAD"},"dot":{"sha":"6e8a26f2","branch":"HEAD"},"joist":{"sha":"ab5582ab","branch":"HEAD"},"kite":{"sha":"88f0c3a0","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"scenery":{"sha":"0ab22ac3","branch":"HEAD"},"scenery-phet":{"sha":"04cec216","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"061f2ea9","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

**Comment by oliver-phet** [comment]
![bending light problem](https://cloud.githubusercontent.com/assets/5090275/20068629/9101bd56-a4d6-11e6-87f4-f53f1bfab1ee.png)

**Comment by ariel-phet** [comment]
@oliver-phet this is not a bug. I can explain to the user if you like, but basically the frequency/period of the wave is independent of speed (this is why the color of light does not change the wave goes into a medium with a different index of refraction).

**Comment by oliver-phet** [comment]
Will forward original email to you. Closing this.
