### ISSUE TITLE
WebGL Wave View is too Gray

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#367]
@kathy-phet said:

In the original simulation, you could see the reflected wave propogating in color in the wave view. I forget whether it was an explicit design decision to not have this any more - or if this is a new bug that the reflected wave is just gray. 

![image](https://cloud.githubusercontent.com/assets/679486/22223593/d5365548-e178-11e6-8236-d3c8096920b8.png)

I now suspect it is a new bug - because I just saw in the HTML screenshot on our website it isn't grey.

**Comment by samreid** [comment]
I think this is a WebGL bug, because running with ?webgl=false, I do not see this issue.

**Comment by kathy-phet** [comment]
Also, with webgl active, I see if I go all the way to glass --- to get a stronger reflected beam --- you can actually see that the moving wave form is there. It seems like their is a layering problem and the grey is on top, instead of perhaps on the bottom layer.

**Comment by samreid** [comment]
@ariel-phet would you like to review/prioritize/schedule this issue?

**Comment by samreid** [comment]
I put a reminder on my personal calendar for July 12, 2017.

**Comment by samreid** [comment]
By the way, I should mention that @jonathanolson would probably be great at solving this webgl problem, and I wouldn't mind if he worked on it instead of me.

**Comment by jonathanolson** [comment]
I saw that the color (in addition to the transparency) was being modified by the power level. I made a patch above that I believe improves the appearance (no gray), but is still slightly different than the CanvasNode approach (which may not be using just transparency).

@samreid and @kathy-phet, does this look correct?

**Comment by jonathanolson** [comment]
New WebGL:
![bending-webgl](https://cloud.githubusercontent.com/assets/480878/22344286/d97fc890-e3b8-11e6-8f3a-0c51b3a6bdaf.PNG)

Current Canvas:
![bending-canvas](https://cloud.githubusercontent.com/assets/480878/22344290/dcad8e76-e3b8-11e6-9381-0be7ceab4e57.PNG)

**Comment by samreid** [comment]
The canvas node uses step functions for improved performance, the appearance in the WebGL version seems good to me.  Would be great for @kathy-phet or possibly @ariel-phet to confirm.

**Comment by kathy-phet** [comment]
The new WebGL image above looks great! It's a big improvement in my opinion. I would favor re-release -- but in need of testing so just in the queue there somewhere lowish.

**Comment by samreid** [comment]
@jonathanolson will publish a maintenance release soon.

**Comment by jonathanolson** [comment]
Correct, 1.1.2 deployed with the fix.

**Comment by samreid** [comment]
In testing on iOS, I noticed #368, @mattpen is checking to see if this is a problem on iPad too.

**Comment by samreid** [comment]
Testing will need to be done in https://github.com/phetsims/tasks/issues/786

**Comment by phet-steele** [comment]
@samreid @jonathanolson this looks great! Thanks.
