### ISSUE TITLE
User request: Add 1 more triangular prism

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/bending-light#369]
Hello,

In the old (Java) version of "Bending light" one could add up to 6 prisms and create this:
![kobffgknlcgcodac](https://cloud.githubusercontent.com/assets/5090275/22894573/b4d3e018-f1d6-11e6-9ec8-8c8ec4de1681.png)

![gakadbhhionogpic](https://cloud.githubusercontent.com/assets/5090275/22894579/b98aab6e-f1d6-11e6-9ddf-5864e1ef724e.png)
which is a very good example to how increasing the surface area of crystals increases the amount of light scattered from them.
In the new (HTML5) version, there is a limit of 5 triangular prisms, and the above does not work (if the hexagon is incomplete, a lot of new internal reflections arise).

Is it possible to add 1 more triangular prisms to the HTML5 simulation?

Thank you,

**Comment by ariel-phet** [comment]
@samreid I believe we limited the number of items due to performance concerns. My guess is it would be trivial to up the number of items on the prisms screen to 6 each. Is that correct?

**Comment by ariel-phet** [comment]
@samreid no action necessary right now I should clarify, just asking what this change would take.

**Comment by samreid** [comment]
Currently the code limits the number of prisms to 5 each for all of the types.  It would be trivial to increase it to 6 max for all types.  Slightly more complex to cap it at 5 for some types and 6 for others.  I haven't tested performance lately, so not sure how much a concern that is.

**Comment by ariel-phet** [comment]
@samreid please go ahead and increase to 6 for all types and reissue the the rc testing task when you get a chance, not a huge rush.

**Comment by ariel-phet** [comment]
Note - I believe 5 was a somewhat arbitrary choice so things did not get too crazy, but since a user has a specific reason for 6 it seems totally reasonable to increase the number

**Comment by samreid** [comment]
Sounds good, I will probably get to this Thursday or later.

**Comment by samreid** [comment]
Fixed above, I'll create an RC.

**Comment by samreid** [comment]
RC.3 is published here: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.1.4-rc.3/bending-light_en.html 

I'll create a test task.

**Comment by samreid** [comment]
Ready for testing in https://github.com/phetsims/tasks/issues/786

**Comment by phet-steele** [comment]
Assigning to @oliver-phet. This inclusion does not seem to have any adverse effects.

**Comment by oliver-phet** [comment]
This has been published. Closing.
