### ISSUE TITLE
Single light mode - Ray doesn't change color - firefox specific issue

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#37]
Single light mode - Ray doesn't change color on firefox. It only changes at the tip of the torch. Pls see image below -

![image](https://cloud.githubusercontent.com/assets/3147499/7407827/767c09b4-ef33-11e4-92dc-1a055a296339.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
