### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#370]
Testing in https://github.com/phetsims/tasks/issues/786 completed, it is ready to publish.

**Comment by samreid** [comment]
The new bending light is live.  @oliver-phet can you please notify our customer that requested more prisms?

**Comment by samreid** [comment]
I emailed the PhET Team

PhET Team,

Bending Light 1.1.4 was published today.  Thanks to Jon for fixing the webgl wave view, and to Steele for his good QA testing!  This also includes 6 of each type of prism (instead of 5) based on a customer request.

Best Regards,
Sam

**Comment by oliver-phet** [comment]
Email to user sent. Closing.
