### ISSUE TITLE
User request: customized prisms

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/bending-light#371]
> I have just see the PHET and I am very impressed with the tools. I was seeing
> the refraction of light through prisms. Can the prism be customized? It would be 
> great, if one can customize the prism and can create a personalized waveguide.

**Comment by ariel-phet** [comment]
@oliver-phet please reply to the user that although we appreciate the feedback and suggestion, this request is outside the scope of the sim.

**Comment by oliver-phet** [comment]
Done. Closing.
