### ISSUE TITLE
Prisms get away from the mouse

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#372]
Noted in master: go to 2nd screen, drag a prism from the toolbox.  Depending on your screen size, the prism will go faster than the mouse.

**Comment by samreid** [comment]
Still happening to this day.

**Comment by samreid** [comment]
Observed again today.  This would block republication.

**Comment by KatieWoe** [comment]
Found again today while testing https://github.com/phetsims/QA/issues/226.  Assuming it is unrelated due to the age of the issue.

**Comment by pixelzoom** [comment]
Sounds like an incorrect coordinate transform in a drag handler, maybe confusion between `globalToParentPosition` and `globalToLocalPosition` (or something like that...)

**Comment by KatieWoe** [comment]
Found again during ES6 Testing

**Comment by samreid** [comment]
Unassigning until I return to bending light.

**Comment by samreid** [comment]
I tested master in a wide variety of screen sizes, and tried dragging prisms from the toolbox and in the play area.  Nothing got away from the mouse.  I'm not sure how this was corrected, but I don't see obvious commits in bending-light that would explain it.  Closing... (for now?)

**Comment by samreid** [comment]
Reopening based on the 3 TODOs marking this issue in the code, they seem like they need attention.

**Comment by samreid** [comment]
The remaining TODOs are about drag bounds, which will be addressed in https://github.com/phetsims/bending-light/issues/419. Closing.
