### ISSUE TITLE
Check boxes larger than standard on prisms screen

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/bending-light#375]
One the prisms screen the check boxes are much larger than standard (normally we match them to about the size of the text. The text "Normal, Reflections, Protrator" also seems to be a bit small.

Might be a good pixel polish to make next time we republish this sim. 

![bl](https://user-images.githubusercontent.com/4051174/27118150-349fb802-5097-11e7-81dc-653360adc584.PNG)

**Comment by samreid** [comment]
Fixed in the commit, closing.
