### ISSUE TITLE
Use SCENERY_PHET/WireNode

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#377]
WireNode was generalized for Wave Interference, Bending Light should use it too.

**Comment by samreid** [comment]
Fixed, but will need testing and review before publication.

**Comment by samreid** [comment]
Perhaps we should wait for https://github.com/phetsims/scenery-phet/issues/395 review to complete.

**Comment by samreid** [comment]
@pixelzoom volunteered to take a look, thanks!

**Comment by pixelzoom** [comment]
Review completed. I don't see any problem with the above commit, or when running the sim.  

Back to @samreid in case there's more to be done here.  Feel free to close.

**Comment by samreid** [comment]
Thanks, closing.
