### ISSUE TITLE
Rotating/Translating prism shapes in firefox

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#38]
While rotating the prisms under light rays, the rays seem to get broken or distorted at times. Some of the broken light rays are permanent on the screen (doesnt get reset as in second image below).

Please see images below for example - 
![image](https://cloud.githubusercontent.com/assets/3147499/7407867/f5cf47b2-ef33-11e4-87f1-d388dd1745be.png)

![image](https://cloud.githubusercontent.com/assets/3147499/7407920/c2f21a6c-ef34-11e4-9c25-c3c47c87d73e.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing.
