### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#384]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Radio buttons may be difficult (don't seem to contain the word
* Maybe enlarge step through button area

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56162845-2ad15c00-5f8a-11e9-8eff-77c126510b94.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56162846-2ad15c00-5f8a-11e9-9840-44a9017ee5ab.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56162848-2ad15c00-5f8a-11e9-969f-d4c36a48883b.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56162849-2ad15c00-5f8a-11e9-95bd-cd5a9d93f7c2.png)

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

@samreid can you include the text label in the touch area for Ray/Wave, as was done for Normal/Slow Motion?

**Comment by samreid** [comment]
Unassigning until I'm working on bending light again.

**Comment by samreid** [comment]
After the commit, the touch areas look like this:

![image](https://user-images.githubusercontent.com/679486/106626485-fea71680-6534-11eb-9946-4c2987e66df8.png)

@arouinfar anything else for this issue?

**Comment by arouinfar** [comment]
Everything looks good with `showPointerAreas`. I also tested on my phone, and didn't notice any other issues.

**Comment by samreid** [comment]
Thanks, we will deploy this with the upcoming phet-io release.  Closing.
