### ISSUE TITLE
use SCENERY_PHET/TimeControlNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#386]
Noticed while working on https://github.com/phetsims/scenery-phet/issues/575.

bending-light currently has its own implementation, see BENDING_LIGHT/TimeControlNode.  It should be using common code SCENERY_PHET/TimeControlNode.

One notable difference is that bending-light uses "Slow Motion", where common code uses "Slow". Another difference is the position of the radio buttons.

This is important for phet-io and a11y.

**Comment by samreid** [comment]
Fixed in the commit.  @arouinfar is it OK that the new button says "Slow" instead of "Slow Motion"?  I don't see an option in the common code TimeControlNode to change this, and I didn't recall the design discussions around whether that would be supported.

**Comment by pixelzoom** [comment]
"Slow" (and other speed labels) were standardized in https://github.com/phetsims/scenery-phet/issues/575#issuecomment-585424270.   And the associated enumeration is:

`const TimeSpeed = Enumeration.byKeys( [ 'FAST', 'NORMAL', 'SLOW' ] );`

Unless there's a really good reason to deviate with "Slow Motion", I think we should try to stick to the standard labels, and not add yet-another option to TimeControlNode.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! That saved me from trying to find the old discussion.

@samreid the desired design is to use the fast/normal/slow labels in all sims.

**Comment by samreid** [comment]
Sounds good, closing.
