### ISSUE TITLE
Intensity sensor read out boundaries to be adjusted

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#39]
Please see images below - 

![image](https://cloud.githubusercontent.com/assets/3147499/7407895/6807ded4-ef34-11e4-9ade-5c6a239298c8.png)

![image](https://cloud.githubusercontent.com/assets/3147499/7407900/7ca7fcfc-ef34-11e4-906e-4101f9a4fde8.png)

**Comment by ChandrashekarBemagoni** [comment]
Intensity meter intersect with ray only not with the wave shape. A similar issue exists in the Java version as well.

**Comment by kmsravindra** [comment]
@ChandrashekarBemagoni, you are correct. Closing this issue as the behavior is same as in Java version.
