### ISSUE TITLE
all screens are drawing outside of the layoutBounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#394]
In master and [1.2.0-dev.1](https://phet-dev.colorado.edu/html/bending-light/1.2.0-dev.1/phet/bending-light_en_phet.html?dev), all screens are drawing outside of the layoutBounds.  For example, here's the _Prisms_ screen with `?dev`:

<img width="1114" alt="screenshot_399" src="https://user-images.githubusercontent.com/3046552/84938533-a6510080-b09a-11ea-965e-c59d0ebfdc30.png">

**Comment by pixelzoom** [comment]
Actually, all 3 screens are drawing outside of the layoutBounds.

**Comment by pixelzoom** [comment]
Hmmm....  I see that the published version (1.1.20) is behaving the same way.  So maybe this is sim is designed to make full use of the browser window?

**Comment by samreid** [comment]
Unassigning until we return focus to this sim.

**Comment by samreid** [comment]
Yes this sim uses a floating layout that can go outside the dev bounds, closing.
