### ISSUE TITLE
Interference in objects

### ISSUE THREAD

**Issue by masoud-shahpoori** [phetsims/bending-light#395]
Hi Phet developers
I have some problems with **`Bending-light`** simulation **`version: "1.2.0-dev.1"`**
As you see in the image that it has been attached, When I've used `Prisms simulation` and brought 2 same objects it has shown me some problems.
When I want make rotation for each of them, another object rotates too.
The first shape is only superficially correct, but the point of refraction of the light changes.
<img width="959" alt="phet-bug" src="https://user-images.githubusercontent.com/62710542/96459428-f8638780-122e-11eb-846c-15dd3d3282dc.png">

**Comment by samreid** [comment]
I'm seeing the same problem, rotating the 2nd prism incorrectly changes the light path:

![image](https://user-images.githubusercontent.com/679486/106507077-cb5a7e00-6487-11eb-9a3f-ece5b0834efd.png)

Thanks for this report @masoud-shahpoori, I'll label this issue accordingly.

**Comment by samreid** [comment]
I believe this issue was fixed by https://github.com/phetsims/bending-light/issues/403, thanks for the report.  Closing.
