### ISSUE TITLE
Rename Circle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#399]
Would it be possible to rename bending-light's Circle class?  Maybe BendingLightCircle? It obvious conflicts with scenery, and I believe the PhET convention is to try to avoid this kind of name collision.   I can't tell you how many times WebStorm has auto-added a bad import to bending-light.

**Comment by samreid** [comment]
I renamed it in the commit, @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Thanks! Closing.
