### ISSUE TITLE
Wave emitter can't go horizontal

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#4]
Don't know if this is intentional or not, but I noticed that when wave is selected for the laser view, the laser is not able to be dragged to 0 degrees from horizontal. It's stuck here:
![wave](https://cloud.githubusercontent.com/assets/5863899/5744793/fae34bbe-9be0-11e4-904f-b6f248a9dfd6.png)
 As opposed to where it should be able to go:
![ray](https://cloud.githubusercontent.com/assets/5863899/5744820/3234d4b6-9be1-11e4-9d3a-6c4f7b9e47f3.png)

**Comment by ariel-phet** [comment]
I believe this is intended functionality for the wave mode, since the wave representation would look odd at 90 degrees
