### ISSUE TITLE
Color of the medium not appearing properly - firefox

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#40]
Please see the image below. The purple color doesnt fill up the entire medium space on firefox. 

![image](https://cloud.githubusercontent.com/assets/3147499/7407966/4f4a420a-ef35-11e4-91b0-f82f1d42c06a.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above  commits.Assigning to @kmsravindra for verification

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code.Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing.
