### ISSUE TITLE
Zooming function enabled in bending light

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/bending-light#400]
**Test device** 
MacBook Air

**Operating System**
macOS 11.4

**Browser**
safari and also happens in chrome (slightly differently)

**Problem description**
Found on published version of bending light. Zooming shouldn't be enabled in published sim (before zooming available). Screen freezes once zoomed in Safari only and visible portion of screen was off-center. In Chrome, zooming occurred, no freeze, panning happened, and there was a console error.  

**Steps to reproduce**
1. Use track pad to zoom in and out. 

**Visuals**
https://drive.google.com/file/d/1sL5t2mTmJtT17eugVSTyiB8RJkDBTsD0/view?usp=sharing 
<img width="353" alt="whathappened" src="https://user-images.githubusercontent.com/87318828/125346314-94866f00-e327-11eb-822a-d4fc3100eb6b.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Bending Light‬
URL: https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_en.html
Version: 1.1.21 2021-07-01 15:56:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Language: en-us
Window: 1277x711
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"01d41d41","branch":"master"},"bending-light":{"sha":"409bfee1","branch":"HEAD"},"brand":{"sha":"ef5d6907","branch":"HEAD"},"chipper":{"sha":"f7485f51","branch":"HEAD"},"dot":{"sha":"6e8a26f2","branch":"HEAD"},"joist":{"sha":"76d3177e","branch":"HEAD"},"kite":{"sha":"88f0c3a0","branch":"HEAD"},"phet-core":{"sha":"36d116de","branch":"HEAD"},"phetcommon":{"sha":"28e26216","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"fc862bf1","branch":"HEAD"},"scenery-phet":{"sha":"d26758d4","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"061f2ea9","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

**Comment by arouinfar** [comment]
What a strange find! Nice work @Nancy-Salpepi.

Aside from the console error, pan/zoom using the trackpad seems functional in Mac/Chrome.

Troubleshooting info:
> Name: ‪Bending Light‬
URL: https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_en.html
Version: 1.1.21 2021-07-01 15:56:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1440x789
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"01d41d41","branch":"master"},"bending-light":{"sha":"409bfee1","branch":"HEAD"},"brand":{"sha":"ef5d6907","branch":"HEAD"},"chipper":{"sha":"f7485f51","branch":"HEAD"},"dot":{"sha":"6e8a26f2","branch":"HEAD"},"joist":{"sha":"76d3177e","branch":"HEAD"},"kite":{"sha":"88f0c3a0","branch":"HEAD"},"phet-core":{"sha":"36d116de","branch":"HEAD"},"phetcommon":{"sha":"28e26216","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"fc862bf1","branch":"HEAD"},"scenery-phet":{"sha":"d26758d4","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"061f2ea9","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi - This is not specific to bending-light, and is an issue for all sims published before we added our own pan and zoom support (seeing this in capacitor-lab-basics, bending-light, build-an-atom). Moving to a more common code repo since it is not sim specific.

**Comment by jessegreenberg** [comment]
General issue made in joist, will be continuing this issue there.
