### ISSUE TITLE
TS2345: missing required options to WavelengthSlider.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#405]
After converting scenery-phet.WavelengthSlider to TypeScript, bending-light is failing in WavelengthControl.ts.    See screenshot below.

The hierarchy for WavelengthSlider is as follows:
* class WavelengthSlider extends SpectrumSlider
* class SpectrumSlider extends AccessibleSlider( Node, 0 )
* AccessibleSlider is a trait that extends AccessibleValueHandler 

2 options required by AccessibleValueHandlerSelfOptions are missing: `valueProperty` and `enabledRangeProperty`.   Based on these assertion in AccessibleValueHandler, I'm not sure how this was working previously:

```js
256      assert && assert( providedOptions.enabledRangeProperty, 'enabledRangeProperty is a required option' );
257      assert && assert( providedOptions.valueProperty, 'valueProperty is a required option' );
```  

The missing `valueProperty` can be addressed by adding `valueProperty: wavelengthProperty`.  But I don't know how to address `enabledRangeProperty`.

Assigning to @samreid, the responsible dev for this sim.

<img width="909" alt="screenshot_1639" src="https://user-images.githubusercontent.com/3046552/160722168-75d39d37-269d-4e01-aba8-2fa163ba4ad5.png">

**Comment by samreid** [comment]
@chrisklus and I collaborated on the above solution.  @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
👍🏻
