### ISSUE TITLE
Suspicions devDependencies in package.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#409]
Why does bending-light have these `devDependencies` in package.json?  I don't see anything like this in package.json for other sims.

```
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
...
    "typescript": "^4.4.4"
```

**Comment by samreid** [comment]
Thanks, I think @zepumph found an extra installation of node_modules/typescript in bending-light this week.

**Comment by samreid** [comment]
I also wrote to slack:

> There were erroneous entries for dev dependencies in bending light, please pull and npm prune in that directory.  Details in https://github.com/phetsims/bending-light/issues/409
