### ISSUE TITLE
Dragging the Intensity sensor on firefox causes color rending issues (specific to firefox). 

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#41]
Dragging the Intensity sensor on firefox causes color rending issues. Once this dragging is done, then 
other related issues seem to appear - This white distortion doesnt get reset, Switching on the torch produces broken rays etc.,

Please see image below. 
![image](https://cloud.githubusercontent.com/assets/3147499/7408053/2ab2fe5e-ef36-11e4-9d8a-f87efefc909a.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
