### ISSUE TITLE
WebGL wave view is missing from screenshots

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#410]
See https://github.com/phetsims/bending-light/issues/353, the "wave" webgl node does not render in the screenshot.  It is implemented with WebGLNode.  @jonathanolson recently applied fixes in https://github.com/phetsims/joist/issues/664#issuecomment-1234692007 for WebGL screenshots--I did not fully understand the commits.  But maybe WebGLNode has a similar problem.  @jonathanolson can you please take a look?

**Comment by samreid** [comment]
The published version 1.1.35 on the main site does screenshot with the wave: https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_all.html

**Comment by samreid** [comment]
I saw that the WebGL canvas was missing `canvasBounds` and when I added them, the screenshots started working. @Nancy-Salpepi or @KatieWoe can you please test this on a few different platforms on main? To test:

1. Show the wave view
2. Turn on the laser
3. Generate a screenshot

**Comment by KatieWoe** [comment]
Looks ok on Win 11 Chrome and Firefox
