### ISSUE TITLE
Consider converting to default layoutBounds before PhET-iO publication

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#415]
This sim currently uses non-default `layoutBounds`.  In BendingLightConstants.ts:

```ts
    layoutBounds: new Bounds2( 0, 0, 834, 504 )
```

Per https://github.com/phetsims/phet-io/issues/1939...  `layoutBounds` should not be changed for published PhET-iO sims because doing so may disrupt client customizations. So evaluate whether to change `layoutBounds` before publishing a PhET-iO version. 

If you decide not to change layoutBounds, document why in BendingLightConstants.ts, and refer to this issue.

**Comment by marlitas** [comment]
Closing per dev meeting request 12/7/23.
