### ISSUE TITLE
The medium boundaries doesnt seem properly aligned on firefox

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#42]
Pls see image below
![image](https://cloud.githubusercontent.com/assets/3147499/7408065/666ae45c-ef36-11e4-8854-ca0e13c7b234.png)

**Comment by notsiddhartha** [comment]
The colors are also incorrect.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code.Assigning to @kmsravindra forr verification

**Comment by kmsravindra** [comment]
Looks good. Closing.
