### ISSUE TITLE
Memory Leak test for 1.2

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#423]
Test memory leaks for 1.2 release:

Looks like trouble:
<img width="455" alt="image" src="https://github.com/user-attachments/assets/05413b27-55b6-4931-a32e-947241b7395e">

**Comment by samreid** [comment]
Wow, this may be a new personal record for most memory leaked:

<img width="452" alt="image" src="https://github.com/user-attachments/assets/44628a07-f2c1-4a6c-9199-2fc2c9bfb161">

**Comment by samreid** [comment]
Looking more stable after the commits above:

<img width="367" alt="image" src="https://github.com/user-attachments/assets/5c98616c-5dbd-4658-bd3f-9e7eaca39fe4">

**Comment by Nancy-Salpepi** [comment]
Memory test looks good for https://github.com/phetsims/qa/issues/1183. I think this issue can be closed!
<img width="208" alt="Screenshot 2024-12-04 at 9 33 29 AM" src="https://github.com/user-attachments/assets/7dc7ed1a-9edc-4f05-b8a0-d458b41edfc7">

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
