### ISSUE TITLE
Some text goes outside of the panels

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#424]
Like so, seen during fuzzing:

<img width="415" alt="image" src="https://github.com/user-attachments/assets/d3b81edd-57dc-48ef-9a2b-1d0a7aaeaf90">

**Comment by samreid** [comment]
I labeled this for QA testing in the dev test. I don't feel all maxWidths are perfectly optimized, please point out the ones that would be most important to adjust for RC.1. Thanks!

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/1183, the "air" label on the scale can extend to the edge of the panel with some locales:
<img width="209" alt="Screenshot 2024-12-03 at 4 44 37 PM" src="https://github.com/user-attachments/assets/03533bfb-a300-4564-8723-3c79bc5c3be7"> <img width="209" alt="Screenshot 2024-12-03 at 4 38 34 PM" src="https://github.com/user-attachments/assets/125b1cdc-f4d0-43db-a19b-4056c464f6ff">

**Comment by Nancy-Salpepi** [comment]
The checkboxes in the lower left and speed controls also need max widths.  

<img width="610" alt="Screenshot 2024-12-03 at 4 53 50 PM" src="https://github.com/user-attachments/assets/92a0abd7-cf08-424b-b692-fdf5389d0e82">

<img width="214" alt="Screenshot 2024-12-03 at 4 52 08 PM" src="https://github.com/user-attachments/assets/c60a0eb0-7197-4d4a-8929-4f9ba944dbb3">

**Comment by Nancy-Salpepi** [comment]
A few more things that need max width:
1. The wavelength in the display is too long on all screens
<img width="223" alt="Screenshot 2024-12-03 at 7 39 43 PM" src="https://github.com/user-attachments/assets/7797ee15-b335-4ee7-9c35-256efa0da726">

2. The combo box on the Prisms screen
<img width="259" alt="Screenshot 2024-12-03 at 7 39 28 PM" src="https://github.com/user-attachments/assets/41facf9d-0e0f-45ec-939d-941dde9ec7e8">

3. The materials on the index of refraction scale on the Prisms screen
<img width="223" alt="Screenshot 2024-12-03 at 7 40 08 PM" src="https://github.com/user-attachments/assets/1ddb4333-44e0-45c4-b920-6677ae9bbebd">

**Comment by samreid** [comment]
Thanks for the helpful reports. Things are looking much better after the commits. I'm not attempting to fully rewrite all the layout code, but just to improve parts as necessary. So things will likely not be perfect but let's aim for good enough. Can you please test after the changes?

**Comment by Nancy-Salpepi** [comment]
Things are looking much better @samreid! 
The only thing that still needs a max width is the speed display in the sensor. This is most easily seen with ?stringTest=dynamic, but it is also an issue for 2 locales: 
<img width="44" alt="Screenshot 2024-12-06 at 9 18 33 AM" src="https://github.com/user-attachments/assets/c266560d-e619-433c-9b4f-99a4e7b263f5"> <img width="136" alt="Screenshot 2024-12-06 at 9 16 51 AM" src="https://github.com/user-attachments/assets/94a10707-8713-4c9b-9850-b89d17c758f8">

<img width="55" alt="Screenshot 2024-12-06 at 9 16 32 AM" src="https://github.com/user-attachments/assets/50c906a3-cb6f-466f-b9b8-4373d000376b"> <img width="225" alt="Screenshot 2024-12-06 at 9 16 14 AM" src="https://github.com/user-attachments/assets/f47de437-8c63-4ddc-9705-6d1282aff58b">

**Comment by samreid** [comment]
Good catch, should be fixed in the commit. Can you please test and close if it's ok?

**Comment by Nancy-Salpepi** [comment]
Looks fixed on main! Closing.

**Comment by Nancy-Salpepi** [comment]
Looking at @KatieWoe"s https://github.com/phetsims/bending-light/issues/424#issuecomment-2518483821, with dynamic string test, it is possible for the text to extend outside the panel when a mystery material is used.
<img width="301" alt="Screenshot 2024-12-09 at 12 40 23 PM" src="https://github.com/user-attachments/assets/ffad97a7-9009-4567-b43a-0f3d5c4b9190">

**Comment by samreid** [comment]
Fixed, can you please verify on phettest? If OK please label "ready for cherry pick" so I can bring it to RC.2.

**Comment by KatieWoe** [comment]
This does seem to be fixed on main.

**Comment by KatieWoe** [comment]
Looks ok in rc.2
