### ISSUE TITLE
Time and Speed labels on measurement tools aren't translatable 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/bending-light#425]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1183, on the More Tools screen, the word 'Intensity' is translatable but 'speed' and 'time' aren't. 

**Visuals**
<img width="325" alt="Screenshot 2024-12-03 at 4 57 26 PM" src="https://github.com/user-attachments/assets/eb364827-1ea1-42b1-8d26-8b5f38d79f4e">

**Comment by Nancy-Salpepi** [comment]
Here is the Published sim in Italian vs. the dev version:
<img width="471" alt="Screenshot 2024-12-03 at 7 02 06 PM" src="https://github.com/user-attachments/assets/138f67f3-c95d-493c-970f-36dc71c5c44b"> <img width="448" alt="Screenshot 2024-12-03 at 7 02 40 PM" src="https://github.com/user-attachments/assets/99a8b992-2593-4541-baa6-3b4ece30b536">

**Comment by samreid** [comment]
Thanks @Nancy-Salpepi, good error to find. It's fixed in the commit, can you please verify/test?

**Comment by Nancy-Salpepi** [comment]
Looks good on main!
