### ISSUE TITLE
Intensity probe does not collect data until probe is dragged

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#426]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1183. The Intensity probe does not begin collecting data until the probe part has been interacted with. This is in contrast to the published behavior where it collects data as soon as the probe passes through light, even if the probe has not been dragged.

**Visuals**
![meterworking](https://github.com/user-attachments/assets/b0ce1c63-d12d-4068-94b4-66c057843450)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Bending Light‬
URL: https://phet-dev.colorado.edu/html/bending-light/1.2.0-dev.2/phet/bending-light_all_phet.html
Version: 1.2.0-dev.2 2024-12-03 20:43:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Good error report, thanks @KatieWoe. I think it is corrected in the commit, can you please verify on phettest?
