### ISSUE TITLE
Drag arrows present when they shouldn't be

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/bending-light#427]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1183, on all screens when my pointer is hovering over the on/off switch on the laser, the green drag arrows are present even though drag isn't possible. This is different than published. 

**Visuals**
Published vs Dev version:
<img width="239" alt="Screenshot 2024-12-04 at 10 08 30 AM" src="https://github.com/user-attachments/assets/0dfadf55-7237-4b02-80e4-46dc86ae5435"> <img width="239" alt="Screenshot 2024-12-04 at 10 08 46 AM" src="https://github.com/user-attachments/assets/8ce2936b-0611-4abf-98ef-f205b6485e16">

**Comment by Nancy-Salpepi** [comment]
Also, on the Prisms screen, when my pointer hovers over the back knob of the laser, I see both the rotation arrows and the drag arrows, even though I can only rotate the laser with that knob. When I click on the knob, the extra arrows go away. 
In published, only the rotation arrows are present. 
<img width="220" alt="Screenshot 2024-12-04 at 4 03 47 PM" src="https://github.com/user-attachments/assets/05b56371-ba88-4565-9c55-e4b64c59c6e5">

**Comment by samreid** [comment]
Good error report, thanks. I pushed a proposed fix in the commit. It's working in my testing, but was a significant refactor, so please test thoroughly and let me know how it goes.

**Comment by Nancy-Salpepi** [comment]
Working nicely on main! Closing.
