### ISSUE TITLE
Possible for probes to get stuck behind panels

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/bending-light#428]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1183, on the Intro and More Tools Screens when I pull the Intensity and Time sensors out of the toolbox and drop them behind the Materials panel, the body of the sensor 'bumps out" like in https://github.com/phetsims/bending-light/issues/200, but the probes get stuck behind. This behavior is different than in published, where both the body and the probe get bumped out.

**Steps to reproduce**
1. On the More Tools screen, grab the Intensity tool and drop it behind either Materials panel. 

**Visuals**

https://github.com/user-attachments/assets/237fb147-5717-4e3d-824d-63fee47feea2

**Comment by samreid** [comment]
Good discovery @Nancy-Salpepi, thanks. I pushed a proposed fix in the commit, @Nancy-Salpepi can you please test? Please also check at different zoom levels and different window aspect ratios.

**Comment by Nancy-Salpepi** [comment]
@sam, I am unable to verify that this issue is fixed when zoomed in because the screen doesn't pan after taking an object out of the toolbox. It will pan if I grab it once it is in the play area. 
I created https://github.com/phetsims/bending-light/issues/430 and will wait until that is addressed to verify this one.

**Comment by samreid** [comment]
Good idea @Nancy-Salpepi, I added that in the commit. Can you please test? Close if ok.

**Comment by Nancy-Salpepi** [comment]
Looks good!!!
