### ISSUE TITLE
Dragging "Time-Graph" plotter in Safari browser makes the torch disappear for a moment

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#43]
The torch disappears for a moment while dragging the Time-Graph plotter in safari bowser on Mac.

**Comment by ChandrashekarBemagoni** [comment]
Not able to replicate the issue with the latest code. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
This is not appearing for me as well in the latest code that I tested with. Closing.
