### ISSUE TITLE
Pan doesn't work when taking a sensor out of toolbox

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/bending-light#430]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
Seen while trying to verify https://github.com/phetsims/bending-light/issues/428, if I take a tool out of the toolbox while zoomed in, the screen doesn't pan. 
This is similar to https://github.com/phetsims/equality-explorer/issues/179.

**Steps to reproduce**
1. On the intro screen, zoom in  so part of the play area is off screen
2. Grab the Intensity sensor and move it to the right or up, to try and get the screen to pan

**Comment by samreid** [comment]
Thanks @Nancy-Salpepi, I applied the fix from https://github.com/phetsims/equality-explorer/issues/179. Can you please verify and close if ok?
