### ISSUE TITLE
Update screenshots for 1.2 release

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/bending-light#432]
The current screenshots show the old nav bar with the Home screen on the right.
@arouinfar I'm going to go ahead and create new ones.

**Comment by Nancy-Salpepi** [comment]
Screenshots have been updated. @KatieWoe would you mind making the commits when you have a minute?

https://o365coloradoedu-my.sharepoint.com/:f:/g/personal/nasa9473_colorado_edu/Em-uhIfukrFEu5_iBuYWOl8Bi0xCmWg0yE-3q2rqUc87ug?e=FT9jx6

**Comment by KatieWoe** [comment]
Added in the above commits

**Comment by samreid** [comment]
@arouinfar and I agreed this issue is ready to close. Thanks @Nancy-Salpepi and @KatieWoe!
