### ISSUE TITLE
Short sliders when non-dynamic strings are short

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/bending-light#434]
**Test device**
Dell and iPad
**Operating System**
Win 11 and iPadOS 18
**Browser**
Chrome and Safari
**Problem description**
For https://github.com/phetsims/qa/issues/1185. In published version as well.
When strings are short non-dynamically, such as with `?stringTest=X`, the sliders can become very short.

**Visuals**
<img width="488" alt="shortslider" src="https://github.com/user-attachments/assets/4fb6fdfa-df35-409a-bd82-de8ec3e22b54">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: x
URL: https://phet-dev.colorado.edu/html/bending-light/1.2.0-rc.1/phet/bending-light_all_phet.html?stringTest=x
Version: 1.2.0-rc.1 2024-12-06 16:40:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language: en-US
Window: 1280x631
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This is fixed on slider, but all the others still have the issue. 
![moresliders](https://github.com/user-attachments/assets/8a1511a7-2da8-491e-b356-da2ff695051f)

**Comment by KatieWoe** [comment]
If we aren't worried about the slider changing sizes than we can move on, but I found it odd the sliders size changed at all. A designer may have a more informed opinion on if it needs to be addressed.

**Comment by samreid** [comment]
Yes, for this release, I was picturing that the initial slider width is set by the initial translation and the sliders do not resize dynamically as the language changes. So it would be easiest if we could just pick a good minimum. I chose the 120 to match up with English in the prisms screen. I'd prefer not to have a different minimum on each screen (same code is used for all Medium Panels).

**Comment by samreid** [comment]
>  I found it odd the sliders size changed at all. 

Good point, I'll investigate making those more constant.

**Comment by samreid** [comment]
I made the slider widths independent of the initial locale, and they remain constant. It seems OK in my testing. @KatieWoe can you please test on phettest? If it's ok, please label for cherry picking.

**Comment by KatieWoe** [comment]
Looks good on main

**Comment by KatieWoe** [comment]
Looks good in rc.2
