### ISSUE TITLE
Prisms detach from handle 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/bending-light#436]
Related to the fix for https://github.com/phetsims/bending-light/issues/433, the prisms now detach from the handle:

<img width="440" alt="Screenshot 2024-12-12 at 10 52 20 AM" src="https://github.com/user-attachments/assets/ee43e86d-4af1-4df1-8100-67cd07877797" />

**Comment by Nancy-Salpepi** [comment]
Now rotating the prism doesn't cause any refraction:

https://github.com/user-attachments/assets/ef93cf62-d002-41dc-ba54-67758f72c2b3

**Comment by samreid** [comment]
Proposed fix is pushed to main, @Nancy-Salpepi can you please test on phettest? If it is good I will cherry pick and create next RC.

**Comment by Nancy-Salpepi** [comment]
Looks good!

**Comment by Nancy-Salpepi** [comment]
Looks fixed in rc.4. Closing!
