### ISSUE TITLE
The intensity sensor gets bigger when pressing "reset all"

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#45]
The intensity sensor gets bigger when pressing "reset all", even if it had not been moved previously.  It should remain the same size when reset all is pressed in that case.  Here's a movie:

![bigger-sensor](https://cloud.githubusercontent.com/assets/679486/7435774/ed1a9128-f003-11e4-8975-5c1a82278c60.gif)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit .Assigning to @samreid for verification

**Comment by samreid** [comment]
Can @pixelzoom or @jbphet review this?

**Comment by samreid** [comment]
Or we can save this testing until QA test time.

**Comment by pixelzoom** [comment]
Looks like the fix was effective, and I see where the proper scale is now being set in the rest function. Closing.
