### ISSUE TITLE
White light ray appears broken before hitting the prism shape

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#46]
Pls refere the highlighted box to see what this broken affect looks like.

![scr3](https://cloud.githubusercontent.com/assets/3147499/7530858/a2dadb4e-f56d-11e4-9031-3c3fd0380b5c.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
