### ISSUE TITLE
Sometimes it is noticed that the rotation of prism gets stuck

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/bending-light#47]
Sometimes it is noticed that the rotation of the prism gets stuck for no specific reason even if there was a single prism. I couldn't find a step by step method to re-generate the scenario. Seems to happen more frequently for white light mode (although it happens in one color mode as well but less frequently). Please check.

**Comment by ChandrashekarBemagoni** [comment]
It's because of protractor node covering the prism ,in this case the protractor is in visible mode .

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit . Assigning to @kmsravindra for verification

**Comment by kmsravindra** [comment]
Looks good. Closing
