### ISSUE TITLE
constrainBounds is deprecated

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/bending-light#49]
We decided in https://github.com/phetsims/charges-and-fields/issues/39 to deprecate constrainBounds and add a method to Bounds2 "closestPointTo".

This should be used in the future instead of ```ConstraintBounds.constrainLocation``` and eventually we should get rid of the file ConstraintBounds altogether.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ @aaronsamuel137 for review

**Comment by aaronsamuel137** [comment]
Looks great! Closing
