### ISSUE TITLE
Wave still moves while sim is paused

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#5]
Starting on the More Tools tab:
1. Click the wave option for the laser view.
2. Turn on the laser.
3. Pause the sim.
4. Switch to either of the two other tabs.
5. Go back to the More Tools tab, and the wave will start moving while the sim is still paused.

I'm using Windows 8.1

**Comment by ariel-phet** [comment]
@phet-steele can you try to produce this on a Win 7 or Mac?

**Comment by phet-steele** [comment]
I can't, and I also can't get it to reproduce on my computer where I first saw it. I must have missed something in the original set up when writing this issue and didn't include it. I would think to tentatively close this because I know for sure it was happening but haven't been able to get it to happen in the past hour. I'll let @ariel-phet decide if more time should be spent on this or if it should just be closed. Maybe we should see if it happens in the ported version once it's out?

**Comment by phet-steele** [comment]
I don't believe this is an issue in 1.0.0-dev.3.
