### ISSUE TITLE
Environment Dropdown selection covered by white/color light choice 

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#52]
The dropdown environment selection on the Prisms Screen is covered by the tool box for white/color light choice.
![screen shot 2015-06-01 at 10 14 51 am](https://cloud.githubusercontent.com/assets/5631059/7917386/4a7bbeb8-0847-11e5-8094-da48d052d7e6.png)

Troubleshooting information (do not edit):
Name: Bending Light
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.3/bending-light_en.html
Version: 1.0.0-dev.3 2015-05-31 01:07:46 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25
Language: en-us
Window: 1224x647
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.19)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"comment":"# bending-light 1.0.0-dev.3 Sat May 30 2015 19:07:45 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"4875945b5eb9027d4994f6ffa990b664979c1d86","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"bending-light":{"sha":"e99296da4f6ca1fff8fc142e89c34f7352c87eb4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"60c6645455a0692ec65c701c462399822599b1ef","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"ee8f44af90bd8dfd7d13399ecb429348c94e8dd5","branch":"master"}}

**Comment by orejolaphet** [comment]
Seen on OSX 10.10.1 Chrome 42 & Safari 8

**Comment by arouinfar** [comment]
Also seen on OSX 10.9.5 and Chrome 43. The drop down should be layered above the panel.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @orejolaphet for verification

**Comment by samreid** [comment]
Looks fixed, thanks:

![image](https://cloud.githubusercontent.com/assets/679486/9152033/9f525022-3dd6-11e5-97dd-22521899e372.png)

Closing.
