### ISSUE TITLE
Why is there not a value reading slider for index of refraction in 'Prism' mode?

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#55]
I am not sure if this was intentional or not but the 'Into' and 'More Tools' tabs both have value reading sliders as shown below while the 'Prisms' tab does not

![bendinglightscreenshot3](https://cloud.githubusercontent.com/assets/7717368/7918025/b9050642-084b-11e5-8674-eb2672695d93.png)

This is on the Prisms tab

![bendlinglightscreenshot4](https://cloud.githubusercontent.com/assets/7717368/7918027/bce11f8a-084b-11e5-835f-21bd28e74a5a.png)

**Comment by arouinfar** [comment]
This was an intentional design decision, @bryo5363. Instructors may wish to have their students calculate n, or work more qualitatively on this screen.
