### ISSUE TITLE
Time tool does not reflect wave speed?

### ISSUE THREAD

**Issue by arnabp** [phetsims/bending-light#58]
The "Time" tool that shows the waveforms for the different light waves shows two waves, which are said to have different speed by the Speed tool, traveling at the same speed with the same wavelength (only amplitude and phase shift are different).

![wave speed](https://cloud.githubusercontent.com/assets/8583364/7924002/1f0927e2-0875-11e5-9a50-fa7db0bf9318.png)

**Comment by arouinfar** [comment]
Great observation, @arnabp! 

The wavelength of light is affected by the index of refraction of the medium, but the frequency is not, resulting in a changing speed. The spacing of the bright and dark spots (corresponding to peaks and valleys of the wave) are more closely spaced with a higher n, indicating a shorter wavelength. However, this change in wavelength is minute (for example, red light will still look red inside of a prism) and does not register on the wave detector. The wave detector was designed to demonstrate that the amplitude is proportional to intensity, the relative phase difference of the probes, and that frequency is inversely proportional to wavelength (seen using different colors).

![image](https://cloud.githubusercontent.com/assets/8419308/7942895/5d916322-091e-11e5-9920-ee9269a27ce1.png) ![image](https://cloud.githubusercontent.com/assets/8419308/7942902/6b928a6e-091e-11e5-9428-304b0c13c6ec.png)
