### ISSUE TITLE
Laser and beam are not in same plane

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#60]
When dragging the laser towards the environment and light selection boxes I noticed that the laser will be placed on top of the boxes while the beam will be behind the boxes. 

![screen shot 2015-06-02 at 10 15 05 am](https://cloud.githubusercontent.com/assets/7717368/7940775/4988efe8-0910-11e5-913c-30f95b2fa42f.png)

**Comment by arouinfar** [comment]
This behavior is present in the Java sim. 

While it makes sense for the laser and beams to live the same layer, I think it's best if beams stay behind the panels. For example, this would look pretty messy if the beams were layered above the panel:

![image](https://cloud.githubusercontent.com/assets/8419308/7945303/1c4fbc60-092d-11e5-8dc5-56c8279281d7.png)

I also prefer that the laser is layered above the panels so it doesn't get lost. While it looks quite strange to have the beams and laser live in separate layers, it's unlikely that users will drag the laser on top of the panel. This issue should be taken to the design team to make a decision. Self-assigning for now.

**Comment by arouinfar** [comment]
This issue is being addressed in #178. Closing.
