### ISSUE TITLE
Different amount of significant digits for intro and more tools

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#61]
For indices of refraction, the Intro tab has one less significant digit than the 'More Tools' tab. Not sure if this was intentional or not.

**Comment by arouinfar** [comment]
Nice catch, @bryo5363! Having an additional decimal place on the More Tools screen was an intentional design decision, since it functions as a Lab screen. I'll close this issue once I'm added as a collaborator to this repo.
