### ISSUE TITLE
White light is not rendered the extent of the entire screen

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#63]
The white light laser is not rendered for the length of the screen as opposed to any other color laser

Normal Red laser:
![screen shot 2015-06-02 at 10 41 42 am](https://cloud.githubusercontent.com/assets/5631059/7941394/378a7a6a-0914-11e5-98ac-88a232031537.png)

White light laser:
![screen shot 2015-06-02 at 10 41 53 am](https://cloud.githubusercontent.com/assets/5631059/7941403/3cb85c46-0914-11e5-94fb-a89a64c267b4.png)

Troubleshooting information (do not edit):
Name: Bending Light
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.3/bending-light_en.html
Version: 1.0.0-dev.3 2015-05-31 01:07:46 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Language: en-US
Window: 1114x1235
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"comment":"# bending-light 1.0.0-dev.3 Sat May 30 2015 19:07:45 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"4875945b5eb9027d4994f6ffa990b664979c1d86","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"bending-light":{"sha":"e99296da4f6ca1fff8fc142e89c34f7352c87eb4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"60c6645455a0692ec65c701c462399822599b1ef","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"ee8f44af90bd8dfd7d13399ecb429348c94e8dd5","branch":"master"}}

**Comment by bryo5363** [comment]
We also noticed that the white line comes out quite pixelated 
![screen shot 2015-06-02 at 10 51 16 am](https://cloud.githubusercontent.com/assets/7717368/7941557/52f3d5f2-0915-11e5-94ce-bf4e4ea4dd78.png)

**Comment by bryo5363** [comment]
Here is a picture of dispersed white light

![screen shot 2015-06-02 at 11 07 51 am](https://cloud.githubusercontent.com/assets/7717368/7941908/b09da1f4-0917-11e5-8f3b-79ce574e0271.png)

Here is the same setup with red light

![screen shot 2015-06-02 at 11 08 37 am](https://cloud.githubusercontent.com/assets/7717368/7941918/bfc619f4-0917-11e5-96a2-deedd3c0cbab.png)

**Comment by arouinfar** [comment]
It looks like white light is restricted to the dev boundary, but it should extend to the viewable area of the screen. I suspect this may be related to performance issues related to white light (#53), but the behavior should be consistent with monochromatic light.

**Comment by ChandrashekarBemagoni** [comment]
Present behavior matching java version

**Comment by arouinfar** [comment]
The behavior is present in the Java sim, but I think that we should address this before publicaiton, so assigning to @ariel-phet. To summarize this thread, there are two issues:
- [ ] White light is very pixelated compared to the monochromatic beam.
![image](https://cloud.githubusercontent.com/assets/8419308/8138165/9f684772-1105-11e5-81ac-b1266ee35f49.png)    ![image](https://cloud.githubusercontent.com/assets/8419308/8138168/a8b3f484-1105-11e5-86aa-2dab00c01982.png)

- [ ] White light is confined to dev, but monochromatic light extends to the viewable area of the screen. Ideally, white light would have the same boundaries as monochromatic light.

**Comment by samreid** [comment]
Hopefully we can fix the pixellation with #161, we will have to change the size of the canvas to match the screen bounds to make sure it doesn't truncate.

**Comment by samreid** [comment]
I'm going to separate checkbox 1 from https://github.com/phetsims/bending-light/issues/63#issuecomment-111593777 into a separate issue, and let this issue be specifically about the canvas bounds.

**Comment by samreid** [comment]
I converted single color rays to use canvas in #162 and also demonstrated how to fit the canvas to the visible bounds in that implementation.  We can reuse that strategy for white light as well.

**Comment by samreid** [comment]
The WebGL implementation fits the visible bounds.  I can reshape the canvas to fit the bounds but since it is a large 2D histogram this would actually be very difficult to fit the bounds for the case where webGL is not allowed.  Perhaps we should discuss whether we can allow this restriction for when webGL is not available in order to keep the computations tractable.  *or* we could bail on the histogram approach and come up with some other canvas way of drawing the light that doesn't suffer from this problem.  I guess I'm inclined to see where we go with #53 before deciding here.

**Comment by samreid** [comment]
We are going to continue with WebGL for white light in #53 and @ariel-phet already said its ok for the white light to be somewhat pixellated when webgl is not available in #180.  So the next question is whether it is OK for the white light to be bounded when webgl is not available.  If that's OK then we can close this issue.  If it's not OK then we will likely need to come up with a novel algorithm for rendering the white light using canvas, which may be tricky to support gray white light.

**Comment by ariel-phet** [comment]
Bounded to the dev-bounds would be OK...is that the bounds you mean @samreid?

**Comment by samreid** [comment]
White light with webgl=false is buggered up in master, but I tested against dev.15 and it is bounded to the dev-bounds:

![image](https://cloud.githubusercontent.com/assets/679486/9510362/09dbc662-4c28-11e5-9953-339c8ca03d61.png)

So I'll close this issue.
