### ISSUE TITLE
Intensity meter only works on small section of wave

### ISSUE THREAD

**Issue by arnabp** [phetsims/bending-light#65]
When the light hits a strong dense medium at a sharp angle, the total area covered by the wave is larger, but the area where the intensity meters works is not, making it so that you can cover the entire intensity meter in the wave and still have it detect nothing. This is not true for the speed and time meters.

![wave intensity measurement](https://cloud.githubusercontent.com/assets/8583364/7947982/e61aa00e-093d-11e5-9e23-c299f5ef2f3e.jpg)

**Comment by arouinfar** [comment]
It looks like the intensity meter is pickier about being more centrally located in the beam. These screenshots show closet the meter can get to the edge of the beam before it ceases to work:
![image](https://cloud.githubusercontent.com/assets/8419308/7964518/5ce1c900-09d5-11e5-9fce-9732663a8ca6.png) ![image](https://cloud.githubusercontent.com/assets/8419308/7964532/6e00e4be-09d5-11e5-80f3-d6557582d640.png)

**Comment by ChandrashekarBemagoni** [comment]
Currently it's matching java version.Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
@ChandrashekarBemagoni is correct. The behavior currently matches the Java sim.

@ariel-phet, is this something we would like to address when PhET takes over the development?

**Comment by arouinfar** [comment]
@ariel-phet, do you think this is something worth assigning to @samreid to handle before publication?

**Comment by samreid** [comment]
@arouinfar are you thinking that it would be best for the beam to be intercepted if *any part of it* hits the intensity meter?  What do you recommend specifically?

**Comment by arouinfar** [comment]
Yes, I was thinking along those lines @samreid. The current behavior isn't sensitive enough, and users may think the sim is buggy in the scenario shown in @arnabp's screenshot.

**Comment by samreid** [comment]
It looks like one way to reach this goal will be to simulate multiple parallel rays when in wave mode and check each for intersections in addAndAbsorb.  Alternatively, we could try for a shape/shape intersection, but that may be more difficult to decide where to truncate the wave.

**Comment by samreid** [comment]
I thought it would work to change like so:

```js
    getIntersections: function( sensorRegion, flipRay ) {
      var ray = flipRay ?
                new Ray2( this.tip, Vector2.createPolar( 1, this.getAngle() + Math.PI ) ) :
                new Ray2( this.tail, Vector2.createPolar( 1, this.getAngle() ) );
      if ( this.waveShape ) {
        return this.waveShape.intersection( ray );
      }
      else {
        return sensorRegion.intersection( ray );
      }
    },
```

and 
```js
    addAndAbsorb: function( ray ) {

      // find intersection points with the intensity sensor
      var intersects = ray.getIntersections( this.intensityMeter.getSensorShape(), false );

      // if it intersected, then absorb the ray
      var rayAbsorbed = intersects.length > 0;
      if ( rayAbsorbed ) {
        var x;
        var y;
        if ( intersects.length === 1 ) {

          var intersectPointAtSensorStart = ray.getIntersections( this.intensityMeter.getSensorShape(), true );
          
          // intersect point at sensor shape start position when laser within sensor region
          x = intersectPointAtSensorStart[ 0 ].point.x + intersects[ 0 ].point.x;
          y = intersectPointAtSensorStart[ 0 ].point.y + intersects[ 0 ].point.y;
        }
```

But it is not working properly.

**Comment by samreid** [comment]
My mistake.  To use the above, I would have to do a shape/shape intersection, not shape/ray.  I'm not sure if kite shapes support shape/shape intersections at the moment.

**Comment by samreid** [comment]
Basic support is above.  Next steps necessary:

1. find the intersection closest to the ray tail (not closest to center of ray)--this should address discontinuities when dragging the sensor across a wide wave
2. test performance on iPad and fine tune the number of parallel rays to keep performance acceptable.

**Comment by samreid** [comment]
I found an analytic solution, and implemented it above (I should note that the iterative approach was fast enough on the iPad3, so the analytic solution probably is as well.).  Now there is just a problem where the incoming ray is being intercepted past the origin.

**Comment by samreid** [comment]
I think I have it working well now with the exception of one discontinuity when the sensor regions goes from one to two intersections, here's a movie about it:

![discontinuity](https://cloud.githubusercontent.com/assets/679486/9571167/8472fda6-4f56-11e5-91ae-2359f282982f.gif)

Notice that the light ray jumps from the edge of the sensor to the middle of the sensor.  I think it may be technically feasible to solve this, with a couple of hours of work, but I'm not sure that it is justified since I don't believe the discontinuity will cause any distractions or misconceptions.  Reassigned to @ariel-phet to get another opinion.  Here's a testable link:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.18/bending-light_en.html

Please review the behvaior in the 1st screen only, the 3nd screen still has issues from #171

**Comment by ariel-phet** [comment]
It feels a touch buggy, but I think the use case you are showing is pretty rare. Lets close the issue and see if one of the testers reports it (or an issue related that requires tweaking).
