### ISSUE TITLE
Laser button looks depressed when turned off

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#67]
The button on the laser looks depressed even when the laser is turned off:
![image](https://cloud.githubusercontent.com/assets/8419308/7964682/4e6431c8-09d6-11e5-8cf1-739123b6844c.png)

Color Vision uses a similar button on the flashlight and the button:
![image](https://cloud.githubusercontent.com/assets/8419308/7964704/6830c5e4-09d6-11e5-806f-64f67b12fdbb.png)

The button from Color Vision should be used in Bending Light, but I don't think that is currently true. Perhaps the laser button is upside down? The white highlight should be on the top left, not the bottom right.

**Comment by ChandrashekarBemagoni** [comment]
Now  laser button as same as color vision

**Comment by arouinfar** [comment]
Thanks, @ChandrashekarBemagoni. The button now matches Color Vision, but it appears to be upside down. At the default position, the highlight should be in the upper left corner.

The laser in the latest pull has the white highlight on the bottom.
![image](https://cloud.githubusercontent.com/assets/8419308/7989902/40022b74-0aaa-11e5-9b5b-ded05dceec54.png)

Color vision has the highlight in the upper left corner.
![image](https://cloud.githubusercontent.com/assets/8419308/7989906/47467228-0aaa-11e5-80a8-6863ced0bb10.png)

The Java version of Bending Light also has the highlight at the top.
![image](https://cloud.githubusercontent.com/assets/8419308/7989924/700c5b14-0aaa-11e5-9570-db017e2ef4ef.png)

Reassigning to @ChandrashekarBemagoni.

**Comment by phet-steele** [comment]
Also, as a thought for @ariel-phet, how important would it be to introduce a way for the highlight on the button to be dynamic when, for instance on the prism screen, the user can flip the laser a full 180 degrees? This would mean the highlight on the button would have to rotate around too and always be pointing towards the top left.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Looks great @ChandrashekarBemagoni! Closing.
