### ISSUE TITLE
Spacing between Reflections, Normal, Protractor checkboxes does not match mockup

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#68]
On the Prisms screen, the checkboxes for Reflections, Normal, and Protractor should be equally spaced.

dev. 3:
![image](https://cloud.githubusercontent.com/assets/8419308/7964816/14de7dd6-09d7-11e5-8eb2-67928e482c58.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/7964949/a43075ca-09d7-11e5-9209-2b11635c0ad7.png)

**Comment by ChandrashekarBemagoni** [comment]
Spacing between Reflections, Normal, Protractor check boxes is different , it's because protractor check box height includes icon  dimensions also. So Reduced protractor icon scale  to maintain equal space between.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Thanks, @ChandrashekarBemagoni! Closing.
