### ISSUE TITLE
Laser in single/multi beam scene selection buttons does not match mockup

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#69]
The artwork for the laser in the single/multi beam scene selection buttons does not match the mockup.It looks like all four corners of both rectangles have been rounded, but only those on the right side should be rounded.

dev.3:
![image](https://cloud.githubusercontent.com/assets/8419308/7965028/14d95c1a-09d8-11e5-8d9f-8df5caebbb05.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/7965017/059d56ac-09d8-11e5-9c21-4587463c3c52.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar  for verification

**Comment by arouinfar** [comment]
Looks great, @ChandrashekarBemagoni! Closing.
