### ISSUE TITLE
No limit for the amount of prisms a user can place on screen in "Prism Break"

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#7]
I imagine we would like to place some limit on the amount of prisms of any given type the user can place on the screen? Otherwise I suspect there would be some performance issues. Related to https://github.com/phetsims/bending-light/issues/6

![bendinglightjava](https://cloud.githubusercontent.com/assets/5631059/5762050/a4f05e60-9c9c-11e4-970f-41a1a1bc33f2.PNG)

![bendinglightjava2](https://cloud.githubusercontent.com/assets/5631059/5762058/aad5769e-9c9c-11e4-8791-bdd1697b6038.PNG)

**Comment by phet-steele** [comment]
To keep this up to date, still no limit in HTML5 1.0.0-dev.3

**Comment by samreid** [comment]
@arouinfar can you please suggest a design for the limit on prisms?  Should it be limited by type (say, 5 of each)?  What happens when the user runs out? Etc. etc.

**Comment by arouinfar** [comment]
@samreid, I discussed this issue with @ariel-phet and we decided that allowing 5 of each type of prism seems sufficient. If a user drags out all five of a given object, it will disappear from the panel:

![image](https://cloud.githubusercontent.com/assets/8419308/9185418/ef2f0f42-3f78-11e5-88c2-d9b23d102f2a.png)

**Comment by samreid** [comment]
I'm still deciding whether to do #166 or not.  That decision will determine how we implement this limit.

**Comment by samreid** [comment]
How did @ariel-phet and @arouinfar decide on "5 of each type"?  I just tried dragging 5 of each type into the play area and it looked like so:

![image](https://cloud.githubusercontent.com/assets/679486/9312648/2e1e110a-44db-11e5-8aa1-284cc561b7a4.png)

Isn't that still a bit too many?

**Comment by arouinfar** [comment]
That seems a bit crowded to me. Perhaps a better solution would be to limit the total number of prisms to say, 15 or so (the max should still be a large number). If that's the case, the user can have 15 of the same object, or a mixture. Once the limit is reached, all prisms must disappear from the panel. When one object is returned, all five options will reappear.

Something similar is done in the mobile WebGL implementation of Charges & Fields. Once the max number of charges have been dragged out, both the positive and negative charges disappear from the selection panel. There haven't been any notable usability issues found in interviews with that implementation.

What do you think, @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar I think 5 of each type is an easy rule. If someone really wants to drag this many things out, so be it. and if performance lags under those circumstances, I don't think user should be particularly surprised.

In addition the 5 of each type allows a very simple feedback, the moment you drag the 5th out, no more are available. I think the 15 max objects could get strange if someone is near that limit.

**Comment by ariel-phet** [comment]
And back to you @arouinfar

**Comment by arouinfar** [comment]
@ariel-phet makes an excellent point. For ease of implementation, let's stick with 5 of each type of object. The only thing I see missing from @samreid's screenshot is
> If a user drags out all five of a given object, it will disappear from the panel

**Comment by samreid** [comment]
Fixed in http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.9/bending-light_en.html
@arouinfar can you take a look and let me know if this issue is good to go?  Also, note that in #167 the prisms are now getting cut off on the sides of the play area--that is a separate issue.

**Comment by arouinfar** [comment]
Looks good! Thanks, @samreid. Closing.
