### ISSUE TITLE
Touch areas do not match spec

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#72]
There are a few issues with the touch areas in dev.3.

- [x] There are overlapping touch areas on the wavelength sliders on the Prisms and More Tools screens. The touch areas on the tweakers should be reduced in height so they do not overlap the slider bar.

dev.3 (left) and Mockup (right):
![image](https://cloud.githubusercontent.com/assets/8419308/7967129/89c4a3d8-09e5-11e5-98ba-778b21c32945.png) ![image](https://cloud.githubusercontent.com/assets/8419308/7967145/9ac14614-09e5-11e5-97de-694d600a9461.png)

- [x] The touch (and click) areas of the intensity meter and wave detector only include the body and probe. This is problematic, because if I hover the mouse over the center of either of these tools (where the wires are) I am unable to click them. The touch/click areas should include the entire tool.

dev.3 (left) and Mockup (right):
![image](https://cloud.githubusercontent.com/assets/8419308/7967258/1af232bc-09e6-11e5-8f48-cba31d865aa7.png)   ![image](https://cloud.githubusercontent.com/assets/8419308/7967228/f92ea098-09e5-11e5-809d-ac4852120194.png)

- [x] It is difficult to rotate the prisms on an iPad. The touch area for the rotation handle does not appear when using ?showPointerAreas, so I'm not sure how it is currently specified in dev.3. Please make the touch area more generous along the lines of:

![image](https://cloud.githubusercontent.com/assets/8419308/7967327/a794d56c-09e6-11e5-8f18-59d33fe6cb26.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
The first and third issues appear to have been addressed; however, I'm still unable to retrieve the Wave Detector (Time) and Intensity tools if I click anywhere other than the tool body or probes.

The boxes representing the touch areas have been appropriately updated, but it does not appear that the touch areas themselves have actually been changed. When testing on an iPad, the tools do not expand if I touch the wires in the middle. The same issue exists on a computer.  For example, if I hover over the middle of the tools, the cursor remains an arrow and I cannot retrieve the tool:
![image](https://cloud.githubusercontent.com/assets/8419308/8063675/6fa7ef52-0e93-11e5-98eb-f6b4ad1a4125.png)

I should be able to click ANYWHERE on the tool-- including the wires-- to retrieve it (as in the Java sim). I should also be able to touch anywhere within the box.
![image](https://cloud.githubusercontent.com/assets/8419308/8063787/e4e731e2-0e93-11e5-8691-9878f90735de.png)

Reassigning to @ChandrashekarBemagoni.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Thanks! Looks good, so closing.
