### ISSUE TITLE
When wave is perpendicular to boundary, can measure different vectors for velocity

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#73]
This is a recurring issue on many other sims that have the ability to drag some sort of "hose". 

![screen shot 2015-06-03 at 1 26 14 pm](https://cloud.githubusercontent.com/assets/7717368/7969455/2dceb424-09f4-11e5-9a90-e9d37ecb3d69.png)

when dragging the meter downwards, the vector will flip up

![screen shot 2015-06-03 at 1 26 23 pm](https://cloud.githubusercontent.com/assets/7717368/7969491/69fcd296-09f4-11e5-834b-e422ee62a73c.png)

I know this is due to the reflected wave off of the boundary but this could come off confusing to the user.

**Comment by ChandrashekarBemagoni** [comment]
Fixed here https://github.com/phetsims/kite/commit/0d61997d59a020553e367cbe0e936b53ffb35f9c. Assigning to @bryo5363 for verification

**Comment by samreid** [comment]
@ariel-phet is @bryo5363 available to verify these issues?  If not, can you suggest someone else?

**Comment by bryo5363** [comment]
@samreid This issue seems to be resolved in the latest version of bending light

**Comment by samreid** [comment]
Thanks @bryo5363, I'll close the issue.
