### ISSUE TITLE
Intensity Tool gets stuck under protractor

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/bending-light#75]
Test device: iPad2

Operating System: iOS 8.3

Browser: Safari

Problem description: The intensity tool can be placed under the protractor, but then is stuck. The protractor must be moved out of the way.

Steps to reproduce: Drag protractor into window then drag intensity meter. The intensity tool will be layered underneath it. Now the intensity tool in undraggable, even the parts that are not directly under the protractor. This happens both when the protractor is small and when it's enlarged. 

Severity: Minor

Screenshots:
![image](https://cloud.githubusercontent.com/assets/12610678/8016075/0bc6de52-0b9c-11e5-9b1d-e48347c2d5ea.jpg)

Troubleshooting information (do not edit):
Name: Bending Light
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.3/bending-light_en.html?showPointerAreas
Version: 1.0.0-dev.3 2015-05-31 01:07:46 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"comment":"# bending-light 1.0.0-dev.3 Sat May 30 2015 19:07:45 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"4875945b5eb9027d4994f6ffa990b664979c1d86","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"bending-light":{"sha":"e99296da4f6ca1fff8fc142e89c34f7352c87eb4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"60c6645455a0692ec65c701c462399822599b1ef","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"ee8f44af90bd8dfd7d13399ecb429348c94e8dd5","branch":"master"}}

**Comment by arouinfar** [comment]
This also happens in OSX 10.9.5/Chrome 43. In the Java version, the Intensity meter can be clicked through either of the protractor's openings. This behavior should also exist in the HTML5 version.

The intensity meter should be able to be clicked on anywhere that the meter is not obscured by the protractor.
![image](https://cloud.githubusercontent.com/assets/8419308/8042746/845c3724-0dde-11e5-97e5-7ea52d4b0a96.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Fixed! Thanks, @ChandrashekarBemagoni. Closing.
