### ISSUE TITLE
Clicking on index of refraction arrows do not change the value of the index

### ISSUE THREAD

**Issue by bryo5363** [phetsims/bending-light#76]
I noticed this issue on Windows 7 w/ Chrome 43

I set the index of refraction to glass on the 'More Tools' section of the simulation. I pressed the right arrow one time and noticed that the value of the refraction did not change but the settings immediately changed to custom rather than glass.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @bryo5363 for verification

**Comment by samreid** [comment]
@ariel-phet is @bryo5363 available to verify these issues?  If not, can you suggest someone else?

**Comment by bryo5363** [comment]
@samreid I will test this issue today when I get my hands on a Windows device.

**Comment by bryo5363** [comment]
@samreid This issue is fixed in the latest release

**Comment by bryo5363** [comment]
Tested on Windows 7 w/ Chrome 44.0.2403.130 m

**Comment by ariel-phet** [comment]
Closing since reported as fixed.
