### ISSUE TITLE
Invisible Prisms

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#79]
To my knowledge this would only be possible on touch screens:
1. Go to the Prisms screen, turn on the laser (single or multiple beam, doesn't matter).
2. Place out some prisms that bend the light.
3. Drag out another prism (not the circle) and place it anywhere. Now with two fingers, use one finger to grab the shape like you are going to translate it and use another finger to grab the knob like you are going to rotate it.
4. Without releasing either finger, move and rotate the prism to make sure you have actually grabbed both parts.
5. Now drag the prism, with both fingers, back to the tool box and release.
6. One of the prisms from step 2 should have disappeared while the light still bends as if it is there. Enable normal lines at this point and you will see the lines with no associated shape.

Disclaimer: may not happen on the first try, keep going until it does!

Video
https://drive.google.com/file/d/0B3HJopSo_QqLOG9LSXN3YVhWcW8/view?usp=sharing

![img_0015](https://cloud.githubusercontent.com/assets/5863899/8041411/44faf114-0dd5-11e5-99fa-669babfbe08e.PNG)

Tested on iPad Air 2, iOS 8.3

**Comment by phet-steele** [comment]
Report a Problem

Please copy and paste the information below into an email to phethelp@colorado.edu, and then fill in the blanks. 

Test device:

Operating System:

Browser:

Problem description:

Steps to reproduce:

Severity:

Screenshots:

Troubleshooting information:
Name: Bending Light
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.3/bending-light_en.html
Version: 1.0.0-dev.3 2015-05-31 01:07:46 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"comment":"# bending-light 1.0.0-dev.3 Sat May 30 2015 19:07:45 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"4875945b5eb9027d4994f6ffa990b664979c1d86","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"bending-light":{"sha":"e99296da4f6ca1fff8fc142e89c34f7352c87eb4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"60c6645455a0692ec65c701c462399822599b1ef","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"ee8f44af90bd8dfd7d13399ecb429348c94e8dd5","branch":"master"}}

**Comment by arouinfar** [comment]
Hey @phet-steele, can you update the video link to the sharable version? I am unable to access the video.

**Comment by phet-steele** [comment]
Officially shared.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @phet-steele for verification

**Comment by phet-steele** [comment]
:+1:
