### ISSUE TITLE
There are no boundaries for movable objects.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#8]
It is fairly easy to remove objects  from the screen in view by the dragging of the object and re-sizing of window. This includes the prisms, tools, and laser pointer in the "Prism Break" scene.
![prismbrek](https://cloud.githubusercontent.com/assets/5631059/5762254/278a6338-9c9e-11e4-8194-de720c3e0050.PNG)
![moretool](https://cloud.githubusercontent.com/assets/5631059/5762258/2df966ec-9c9e-11e4-95a2-60ffc81d4513.PNG)

**Comment by phet-steele** [comment]
The intensity meter could have a better lower bound, and the velocity meter needs a better upper bound. Everything else stays in the bounds.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @phet-steele  for verification

**Comment by arouinfar** [comment]
The tools should never be able to completely leave the visible area of the screen. Some tools are able to leave dev boundaries even if those areas of the screen are not visible. There are also some tools with inconsistent behavior when comparing left vs. right, top vs. bottom dev boundaries. Specifically: 
- [ ] The body of the intensity meter can leave the right and bottom dev borders (even when this is off-screen). It should match the behavior of at the left and right boundaries, respectively.
- [ ] The body of the wave detector can leave the top dev boundary. It should match the behavior at the bottom boundary.
- [ ] The speed detector can escape the top dev boundary. It should match the behavior at the bottom boundary.
- [ ] When completely vertical, the laser on the Prisms screen can escape the top dev boundary.  It should match the behavior at the bottom boundary. See #54.
- [ ] When horizontal, the laser on the Prisms screen can escape the left dev boundary. It should match the behavior at the right boundary.

**Comment by arouinfar** [comment]
I didn't see @ChandrashekarBemagoni's comment when making this list, sorry about that. @phet-steele  please use the checklist I created when verifying the the issue.

**Comment by phet-steele** [comment]
All the tools are correctly bound now, but there's an inconsistency in that they used to be bound at the side of the tool itself but now appear to be bound at their centers'. The intensity meter as an example:
The new behavior:
![git-boundaries](https://cloud.githubusercontent.com/assets/5863899/7990241/f57ee878-0aac-11e5-9b98-c1f712c5b7f4.PNG)

As opposed to the old behavior of the meter being bound at its sides:

![dev-boundaries](https://cloud.githubusercontent.com/assets/5863899/7990274/394703ec-0aad-11e5-82d8-f7d6eb55dc4b.PNG)


Now the lasers on the prism screen are kept slightly more inside the dev lines in both vertical and horizontal cases:

new:
![git-laser](https://cloud.githubusercontent.com/assets/5863899/7990560/0ae9d536-0aaf-11e5-93bc-cfe7c43aa79f.PNG)


old:
![dev-laser](https://cloud.githubusercontent.com/assets/5863899/7990568/11ca9e1c-0aaf-11e5-85b3-8756ae106a67.PNG)

**Comment by arouinfar** [comment]
I think that should work @phet-steele. Closing.
