### ISSUE TITLE
Terminating light

### ISSUE THREAD

**Issue by phet-steele** [phetsims/bending-light#80]
In some cases, the light on the Prisms screen will terminate early I'm assuming in order to save performance during large amounts of internal reflection. @arouinfar has volunteered to make a note of this in teacher tips if this is not a bug.

![terminating light arrow](https://cloud.githubusercontent.com/assets/5863899/8043185/847fe676-0de1-11e5-93b7-97f1ac552124.png)

![terminating light](https://cloud.githubusercontent.com/assets/5863899/8042975/143ea240-0de0-11e5-9504-f024076717bb.PNG)

**Comment by arouinfar** [comment]
I don't think it is a bug. It looks like there is a maximum allowable optical path length at which the beam will terminate. I was able to generate a terminating beam by using several prisms, but it is perhaps more noticeable if you are able to generate total internal reflection as @phet-steele did in his original post. 

![image](https://cloud.githubusercontent.com/assets/8419308/8047332/17fa2a6e-0e01-11e5-923b-aa6fcc01db02.png)

I will leave this issue opened and self-assigned until the teacher tips have been created.

**Comment by arouinfar** [comment]
According to model.md: 
>When showing multiple reflections in the Prism Break tab, light rays are terminated after 50 reflections/refractions to ensure computability.

**Comment by samreid** [comment]
@arouinfar can this be closed?

**Comment by arouinfar** [comment]
@samreid, this issue needs to remain open until I've written the teacher tips. I will close it once I've documented this behavior in the Model Simplifications.

**Comment by arouinfar** [comment]
Note to self -- Document this in the model simplifications too. 
![image](https://cloud.githubusercontent.com/assets/8419308/10901936/32eeb7f0-81b4-11e5-9b4f-b84750426689.png)

**Comment by arouinfar** [comment]
> When showing multiple reflections in the Prism Break tab, light rays are terminated after 50 reflections/refractions to ensure computability.

This has been added to the Model Simplification section of the Teacher Tips.

> Note to self -- Document this in the model simplifications too. 

Absence of reflections of reflected beams must have been a glitch in an earlier version. Reflections of reflections are shown in the Java version and in the latest dev (dev.45), so need need to document this in the tips.
