### ISSUE TITLE
Panels should expand up to 50px before resizing text for translations

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#82]
The design doc specifies that the Material panels on the Intro and More Tools screens should expand by 50px (on the left side) to accommodate long strings before decreasing the font size. When doubling the string length, it looks like the panels are not expanding.

![image](https://cloud.githubusercontent.com/assets/8419308/8045190/ec7c7bd8-0dee-11e5-8d5b-38b1d3cdadf6.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Looks great! Closing.

**Comment by arouinfar** [comment]
The design doc also specified that the Environment panel on the Prisms screen should also expand by 50px to allow for long strings. It appears that the panel is not expanding appropriately. 
![image](https://cloud.githubusercontent.com/assets/8419308/8314929/05d9e720-19aa-11e5-855f-d41144abf6b1.png)

Re-opening and assigning to @ChandrashekarBemagoni.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Thanks, @ChandrashekarBemagoni. Looks great! Closing.
