### ISSUE TITLE
Tools do not gracefully handle long strings

### ISSUE THREAD

**Issue by arouinfar** [phetsims/bending-light#83]
When doubling the string length, the Speed and Intensity labels expand beyond the tool boundaries. The strings on all tools should shrink to fit within the body of the tool. 

![image](https://cloud.githubusercontent.com/assets/8419308/8045502/012eb288-0df1-11e5-8ae4-b5d6033baf09.png)

While we typically shrink long strings to fit by default, this behavior was not specified in the design doc. I'm not sure who is responsible for this issue, so assigning to @ariel-phet.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Looks great! Closing.
