### ISSUE TITLE
Some text is very tiny with ?stringTest=double

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#84]
During code review #44 I tested with ?stringTest=double at full screen in presentation mode (to maximize window size) on my 11" Macbook Air, and some of the text was very difficult to see, particularly the tick mark labels on the slider.  @ariel-phet can you suggest a solution?

![image](https://cloud.githubusercontent.com/assets/679486/8257699/df2855d4-166c-11e5-8806-89dfb4138604.png)

**Comment by samreid** [comment]
@ariel-phet do you want me to assign design question issues for Bending Light review to you or someone else?

**Comment by ariel-phet** [comment]
@samreid - assign them to @arouinfar - she will consult me if she wants another opinion/advice

**Comment by arouinfar** [comment]
The Material panels on the Intro and More Tools screens expand up to 50px to allow for longer strings. We could do the same for all panels on the Prisms Screen. Expanding all panels by 50px still allows for plenty of room in the playspace.
![image](https://cloud.githubusercontent.com/assets/8419308/8260239/76c598ae-167f-11e5-99aa-7ca3ad153acd.png)


I've noticed that the text on the slider in the Material panels is also a bit small, but if the slider would also be allowed to increase its length by 50px, the text could be larger.
![image](https://cloud.githubusercontent.com/assets/8419308/8260155/00b99eb2-167f-11e5-809c-b866cc318b53.png)

@samreid do you know if the sliders can expand with the panels?

**Comment by arouinfar** [comment]
It looks like @ChandrashekarBemagoni has addressed these issues in #82. I think the text is now more readable on an iPad. What do you think, @samreid?
![image](https://cloud.githubusercontent.com/assets/8419308/8335370/734387e8-1a5a-11e5-89d1-e63a0677efa7.jpg)

**Comment by samreid** [comment]
I compared before and after 1c99e1fe13373f86923dac2cb559b22d048ab3da and the tick mark labels and other texts are much more legible.  Closing.
