### ISSUE TITLE
Very little leeway in units readout layout

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#85]
During #44 when I tested with ?stringTest=double I noticed there is not much layout leeway for the nm readout.  @ariel-phet do you think this will need to accommodate longer strings in other languages?  Do you want me to look through our Java translations for translations of "nm" and see how long they get?

![image](https://cloud.githubusercontent.com/assets/679486/8257789/5fcf5f8e-166d-11e5-8996-1658b6a188e8.png)

**Comment by ariel-phet** [comment]
@samreid - can the box be scaled to allow longer strings? This readout could grow quite a bit before it is a problem.

**Comment by arouinfar** [comment]
I opened a dozen or so translations (including those with non-Latin characters), and it looks like the "nm" is not translated. I second @ariel-phet's suggestion, but I doubt that long strings will be an issue in this case.

**Comment by samreid** [comment]
I didn't see "nm" in the Java bending light sim strings--perhaps it is coming from common code.  The Bound States Java translation for 'nm' is: نانومتر

In `kk` locale, it is: ננומטר

In `tk` it is: nanometr

In zh_tw it is: nm[奈米]

So perhaps we should just increase the width of the box a bit to accommodate the longest of these strings (or hedge our bets and go slightly wider).

**Comment by samreid** [comment]
@ChandrashekarBemagoni I saw you committed on this issue above.  Is it ready for review?

**Comment by ChandrashekarBemagoni** [comment]
It's Fixed . Assigning to @samreid for verification

**Comment by samreid** [comment]
It seems like there is a bit more room now:

![image](https://cloud.githubusercontent.com/assets/679486/9053548/85f4f932-3a33-11e5-9dc5-cdbc84fc8b87.png)

I'll leave it up to @arouinfar to decide if this is good enough.

**Comment by arouinfar** [comment]
It looks sufficiently large to me. Thanks, @ChandrashekarBemagoni! Closing.
