### ISSUE TITLE
The reset all button is a different size on different screens

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#86]
While I was reviewing the simulation for the code review for #44, I noticed the reset all button is different sizes on the different screens.  @kmsravindra can your team resolve this?  Also, for future issues like this, would you like me to assign them to @kmsravindra @notsiddhartha @ChandrashekarBemagoni or someone else?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid  for verification

**Comment by ChandrashekarBemagoni** [comment]
Sam u  can assign the future issues to @ChandrashekarBemagoni

**Comment by samreid** [comment]
> Sam you can assign the future issues to @ChandrashekarBemagoni

Will do, thanks!

**Comment by samreid** [comment]
Looks great, nice work @ChandrashekarBemagoni.  Closing.
