### ISSUE TITLE
Different fonts within the combo box

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#87]
At a recent Developer Meeting, we discussed the problems with shrinking individual UI elements by using minWidth or equivalent.  Ultimately, we decided that the strategy for coping with i18n layout must be decided on a case by case basis.  With this in mind, I saw this ComboBox in Bending light during code review #44 

![image](https://cloud.githubusercontent.com/assets/679486/8295915/e187d47a-1906-11e5-827e-e8974fb18041.png)

@arouinfar can you look at this and comment?  I'm not sure why it was done this way--was it in the specification to do so?  How do you think the layout should accommodate longer strings here?

**Comment by arouinfar** [comment]
I'm not sure I understand your question, @samreid. In the design doc,  we specified that the Material panels on the Intro/More Tools screens and the Environment panel on the Prisms screen should expand up to 50px before shrinking the font to fit. It looks like the Environment panel isn't expanding as specified. 

For example, here is a screenshot of the appropriately-expanded Materials panel. The drop-down menu also expanded by 50px, so there is plenty of room for longer strings. The same should be done for the Environment panel.
![image](https://cloud.githubusercontent.com/assets/8419308/8314706/6a27c9b0-19a8-11e5-89d0-1bff4b4a521d.png)

**Comment by samreid** [comment]
This is looking better to me after @ChandrashekarBemagoni's changes above.  @arouinfar it now looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/8666245/f5caea48-29ab-11e5-8309-03eb523760e5.png)

Does that seem good to you?

**Comment by arouinfar** [comment]
Looks good to me, @samreid. Closing.
