### ISSUE TITLE
Add homescreen & navbar icons

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#88]
The simulation is just using mockups for the homescreen & navbar icons.  These mockups should be replaced with custom icons.  When the custom icons have been added, we can delete the mockup-images from the images/ directory (they are currently weighing in around 600kb).

**Comment by samreid** [comment]
I noticed this during #44 review.

**Comment by arouinfar** [comment]
I've noticed that I have two homescreen/navbar icon issues currently assigned to me. Looks like this is a duplicate of #104, which has more information regarding icon size, so closing this issue.
