### ISSUE TITLE
Add vector artwork

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#89]
During #44 I noticed there is no vector artwork checked in for this simulation.  We either need to track it down or create new.  @arouinfar can you discuss with @ariel-phet how to proceed?

Here are the images:
knob.png author=phet notes=NP, taken from laser_knob.png
laser.png author=phet notes=NP
laser_knob.png author=phet notes=NP
protractor.png author=phet notes=SR generated with software
wave_detector_probe_dark.png author=phet notes=NP
wave_detector_probe_light.png author=phet notes=NP

**Comment by arouinfar** [comment]
I was able to find asset files for the original Java sim on Unfuddle. I've emailed them @samreid.

**Comment by samreid** [comment]
Thanks, I added those AI files in the commit above.  I also noted that @arouinfar provided AI files for intensity-meter-box and intensity-meter-probe, but it looks like those are actually being drawn in code now.  Therefore I will leave the AI files out of github, unless @pixelzoom or @ariel-phet suggests otherwise.

**Comment by pixelzoom** [comment]
I don't have a strong opinion on whether AI files that are used as reference for programmatic drawing should be included in the assets/ directory.  @ariel-phet's call.

**Comment by ariel-phet** [comment]
Seems unnecessary if being drawn in code
