### ISSUE TITLE
Add Credits

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#90]
@arouinfar can you help me write up the credits for this sim?  I need entries for:

leadDesign
softwareDevelopment
team
qualityAssurance
graphicArts
thanks

**Comment by samreid** [comment]
Linking back to #44, where I discovered this issue.

**Comment by arouinfar** [comment]
I've emailed the credits to @samreid to implement.

**Comment by samreid** [comment]
I added the credits above, closing.
