### ISSUE TITLE
Unlabeled tick mark seems odd

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#91]
@arouinfar I noticed the unlabeled tick mark on the right seems odd (kind of out of place and clutter-y) here:

![image](https://cloud.githubusercontent.com/assets/679486/8336005/9775c12c-1a5e-11e5-8381-2b992066acf8.png)

What do you think?

**Comment by arouinfar** [comment]
I originally included the tick mark on the end to make the slider look more balanced. Here's an example of what it would look like without the extra tick mark.
![image](https://cloud.githubusercontent.com/assets/8419308/8338516/b47915c0-1a6e-11e5-9a46-bbecba6f563b.png)

I don't mind the look without the tick mark. @ariel-phet, what do you think?

**Comment by samreid** [comment]
Thanks for that mock-up.  It also seems pretty unbalanced to me.  I'm not sure what the best solution is here.

**Comment by ariel-phet** [comment]
The unlabelled tick mark is a bit odd, but I think it is fine, and not a concern. Closing.
