### ISSUE TITLE
replace toFixed with dot.Util.toFixed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/bending-light#92]
This sim uses JavaScript's built-in toFixed. This function should not be used directly; it is notoriously buggy, and behavior differs depending on browser, because the spec doesn't specify whether to round or floor. Use dot.Util.toFixed, see its doc for details.

Assigning to @samreid since he's the developer liaison.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @pixelzoom for verification

**Comment by pixelzoom** [comment]
Looks good. I took the liberty of renaming @param format to decimalPlaces in MediumControlPane, since that's more descriptive and matches the parameter name in dot.Util.fixed.

Closing.
