### ISSUE TITLE
Add the correct @author annotations

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#93]
As I was working on the code review for #44 I saw the file BendingLightModel.js listed the author as `@author Sam Reid`.  It is okay to leave that name there since he developed the original Java file, but you should also add the primary developer name and affiliation, like so:

```js
@author Chandrashekar Bemagoni (Actual Concepts)
```

I actually saw that attribution in 35/61 source files, but with differing whitespace (sometimes 0 or 2 whitespace between i and (.  It should appear as above.  And I recommend to put Chandrashekar before Sam in all of these files since Chandrashekar was the primary author of the JS and Sam was the primary author of the other Java version.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks much better, thanks!  I made a few minor fixes in the above commit as well.  Closing.
