### ISSUE TITLE
Documentation for @param in JSDoc

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#94]
Discovered in code review #44.  There are 381 `@param` annotations in the sim JSDoc and many of them need a description (or additional description).  For instance, the BendingLightModel.js looks like:

```js
  /**
   * Main constructor for BendingLightModel, which contains all of the model logic for the entire sim screen.
   *
   * @param {number} laserAngle
   * @param {boolean} topLeftQuadrant
   * @param {number} laserDistanceFromPivot
   * @param {boolean} centerOffsetLeft
   * @constructor
   */
  function BendingLightModel( laserAngle, topLeftQuadrant, laserDistanceFromPivot, centerOffsetLeft ) {
```

These parameters need more explanation.  For the laserAngle, what is it relative to?  Is it in radians?  What is the allowed range?  For the topLeftQuadrant param, why is that important to the model? Etc.

The `@param` annotations need explanation of context, importance, relationship to other code, units, or any other information to help the maintaining developer understand what is happening.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in  above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
This is looking much better, but I still saw a few cases that could use some help.

For IntroModel.js, getWaveValue has an `@return` value attribution like this:

```js
    /**
     * Determine the wave value of the topmost light ray at the specified position, or None if none exists
     * @public
     * @param {Vector2} position
     * @returns {[]}
     */
```
But it is unclear what the values of the returned array are.  Also, I think we annotate arrays like `@returns array.<number>`

Also what does `reference` mean in this phrase?
```js
* @param {number} referenceIndexOfRefraction
```

In LightRay.js
```js
* @param {number} trapeziumWidth
```
what is the trapezium?

In IntensityMeterNode.js I see:
```js
    /**
     * @private
     * @param {Object} startPoint
     * @param {Object} endPoint
     */
    init: function( startPoint, endPoint ) {
```
What is this initing?  Could use some more explanation.

In LaserNode.js, I see:
```js
* @param {function} clampDragAngle
```

In SemiCircle.js I see:
```js
* @param {Vector2[]} points
```

But again this should be of the form {array.<Vector2>}

In LaserControlPanelNode.js I see:
```js
{Property<string>}
```
But occurrences like this should be Property.<string>.  More about this in our style guidelines: https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.1oxr3ptyo50w

In WhiteLightNode.js there are some:
```js
* @param {Object} map
```

Can you describe the keys and values and the relationship in that map?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @samreid for review

**Comment by samreid** [comment]
The occurrences I mentioned above have been addressed nicely, with the exception of the init() functions.  But I'm seeing the init() pattern across many files and I'm going to create a separate issue for it.  So I think the general issue of documenting `@param` is looking much nicer and I'll create separate new issues if I see any other problems as I continue the review.
