### ISSUE TITLE
Why is float texture required?

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#97]
During #44 I saw this code:

```js
    // The unlimited-particle implementation will work only with OES_texture_float where writing to
    // float textures is supported.
```

Can you add some explanation about *why* floating point texture is required and how it is used?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
I can see that the floating point texture requirement and references were removed.  Thanks!  Closing.
